# Step 1 ? Initial raw-data audit

This notebook reads competition source files without changing them. It reports file inventory, schemas, previews, missing values, exact duplicate rows within each file, memory usage, and observed code frequencies. No timestamp parsing, joins, cleaning, imputation, feature engineering, splits, or modelling are performed.

Taxi files are audited sequentially to limit memory use. The combined shape is calculated from compatible source schemas; no combined dataset is saved. Duplicate counts are exact **within each source file**; their sum does not include duplicates across different files.

In [1]:
from pathlib import Path
import gc
import pandas as pd
from IPython.display import display, Markdown

ROOT = next(p for p in [Path.cwd(), *Path.cwd().parents] if (p / "data" / "raw").is_dir())
RAW = ROOT / "data" / "raw"
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
print("pandas:", pd.__version__)
print("Raw directory:", RAW)

pandas: 3.0.5
Raw directory: C:\Users\Shanujen\Desktop\urban-flow-datathon-2026\data\raw

## 1. Source inventory

Recursively inspect `data/raw/`. Ignore `__MACOSX` directories, Apple metadata entries beginning with `._`, and `.gitkeep` placeholders. Classify taxi and reference files using their actual filenames. Any unclassified files are shown for manual review. File sizes use decimal MB (1 MB = 1,000,000 bytes).

In [2]:
all_files = sorted(p for p in RAW.rglob("*") if p.is_file())
ignored = [p for p in all_files if "__MACOSX" in p.relative_to(RAW).parts or any(part.startswith("._") for part in p.relative_to(RAW).parts) or p.name == ".gitkeep"]
source_files = [p for p in all_files if p not in ignored]
supported = {".csv", ".parquet", ".xlsx", ".xls", ".json", ".jsonl", ".feather"}
usable = [p for p in source_files if p.suffix.lower() in supported]
taxi_files = [p for p in usable if p.name.lower().startswith("urban_flow_analytics_taxi_dataset_")]
reference_files = [p for p in usable if p not in taxi_files and any(word in p.stem.lower() for word in ("zone", "reference", "lookup"))]
unclassified = [p for p in source_files if p not in taxi_files + reference_files]
for path in source_files:
    role = "taxi" if path in taxi_files else "zone/reference" if path in reference_files else "UNCLASSIFIED"
    print(f"{path.relative_to(ROOT)} | {role} | {path.stat().st_size:,} bytes | {path.stat().st_size / 1e6:,.3f} MB")
print("Ignored metadata/placeholders:", [str(p.relative_to(RAW)) for p in ignored])
print("Taxi file count:", len(taxi_files))
print("Taxi data split across multiple files:", len(taxi_files) > 1)
print("Combined taxi source size (MB):", sum(p.stat().st_size for p in taxi_files) / 1e6)
print("Reference files:", [str(p.relative_to(ROOT)) for p in reference_files])
if not reference_files:
    print("MISSING: zone/reference dataset. Its shape and audit cannot be reported until supplied.")
if unclassified:
    print("WARNING: review unclassified sources:", [str(p.relative_to(ROOT)) for p in unclassified])
source_snapshot = {str(p): (p.stat().st_size, p.stat().st_mtime_ns) for p in source_files}

data\raw\Urban_Flow_Analytics_Taxi_Dataset_2025-04.csv | taxi | 429,662,745 bytes | 429.663 MB
data\raw\Urban_Flow_Analytics_Taxi_Dataset_2025-05.csv | taxi | 492,535,780 bytes | 492.536 MB
data\raw\Urban_Flow_Analytics_Taxi_Dataset_2025-06.csv | taxi | 462,646,895 bytes | 462.647 MB
data\raw\Urban_Flow_Analytics_Taxi_Dataset_2025-07.csv | taxi | 418,006,505 bytes | 418.007 MB
data\raw\Urban_Flow_Analytics_Taxi_Dataset_2025-08.csv | taxi | 383,928,038 bytes | 383.928 MB
data\raw\Urban_Flow_Analytics_Taxi_Dataset_2025-09.csv | taxi | 456,686,968 bytes | 456.687 MB
data\raw\Urban_Flow_Analytics_Taxi_Dataset_2025-10.csv | taxi | 477,118,702 bytes | 477.119 MB
data\raw\Urban_Flow_Analytics_Taxi_Dataset_2025-11.csv | taxi | 449,095,149 bytes | 449.095 MB
data\raw\Urban_Flow_Analytics_Taxi_Dataset_2025-12.csv | taxi | 460,962,917 bytes | 460.963 MB
data\raw\Urban_Flow_Analytics_Taxi_Dataset_2026-01.csv | taxi | 397,895,400 bytes | 397.895 MB
data\raw\Urban_Flow_Analytics_Taxi_Dataset_2026-02.csv | taxi | 362,760,959 bytes | 362.761 MB
data\raw\Urban_Flow_Analytics_Taxi_Dataset_2026-03.csv | taxi | 424,665,352 bytes | 424.665 MB
Ignored metadata/placeholders: ['.gitkeep']
Taxi file count: 12
Taxi data split across multiple files: True
Combined taxi source size (MB): 5215.96541
Reference files: []
MISSING: zone/reference dataset. Its shape and audit cannot be reported until supplied.

## 2. Read-only audit helpers

CSV files use `pandas.read_csv` with `parse_dates=False`; timestamps remain strings. Arrow-backed pandas columns reduce memory use without changing values. Standard pandas missing-value recognition is used at load time; no additional missing markers or cleaning rules are applied. Other formats use the matching pandas reader, with every Excel sheet audited separately.

Every dataset shows its exact source name, shape, complete column list and dtypes, first five rows, all-column missing counts, exact full-row duplicate count, and deep memory usage. Code frequency tables are selected only from columns actually present, using names containing code/flag or ending in `_id`, `_method`, or `_count`, plus low-cardinality text columns. These are observed values, not interpretations of undocumented codes.

In [3]:
def read_source(path):
    suffix = path.suffix.lower()
    if suffix == ".csv":
        yield path.name, pd.read_csv(path, parse_dates=False, dtype_backend="pyarrow")
    elif suffix == ".parquet":
        yield path.name, pd.read_parquet(path)
    elif suffix in {".xlsx", ".xls"}:
        with pd.ExcelFile(path) as book:
            for sheet in book.sheet_names:
                yield f"{path.name} :: sheet={sheet}", pd.read_excel(book, sheet_name=sheet, parse_dates=False)
    elif suffix in {".json", ".jsonl"}:
        yield path.name, pd.read_json(path, lines=suffix == ".jsonl", convert_dates=False)
    elif suffix == ".feather":
        yield path.name, pd.read_feather(path)
    else:
        raise ValueError(f"Unsupported source: {path}")


def audit_frame(path, label, frame):
    display(Markdown(f"### `{label}`"))
    print("Exact source:", path.relative_to(ROOT))
    print("Shape:", frame.shape)
    print("All columns:", frame.columns.tolist())
    print("Data types:")
    print(frame.dtypes.to_string())
    print("First 5 rows:")
    display(frame.head(5))
    missing = frame.isna().sum()
    print("Missing-value counts (every column):")
    print(missing.to_string())
    duplicates = int(frame.duplicated().sum())
    memory_mb = float(frame.memory_usage(index=True, deep=True).sum() / 1e6)
    print("Exact duplicate rows within this dataset (after first occurrence):", duplicates)
    print("Total deep memory usage (MB):", memory_mb)
    categorical = []
    for column in frame.columns:
        name = str(column).lower()
        named_code = "code" in name or "flag" in name or name.endswith(("_id", "_method", "_count"))
        low_cardinality_text = (pd.api.types.is_string_dtype(frame[column].dtype) or pd.api.types.is_object_dtype(frame[column].dtype)) and frame[column].nunique(dropna=False) <= 30
        if named_code or low_cardinality_text:
            categorical.append(column)
    frequencies = {}
    print("Observed categorical/code columns:", categorical)
    for column in categorical:
        counts = frame[column].value_counts(dropna=False)
        frequencies[column] = counts
        print(f"\nValue counts: {column} (including missing; {len(counts)} distinct values)")
        print(counts.to_string())
    return {"source": str(path.relative_to(ROOT)), "dataset": label, "rows": len(frame),
            "columns": frame.columns.tolist(), "dtypes": frame.dtypes.astype(str).to_dict(),
            "missing": missing, "duplicates": duplicates, "memory_mb": memory_mb,
            "frequencies": frequencies}

## 3. Taxi source audits

Load and audit each real monthly taxi file separately. Release each dataframe after collecting small audit summaries. No source files or processed datasets are written.

In [4]:
taxi_audits = []
for path in taxi_files:
    print("Loading:", path.name, flush=True)
    for label, frame in read_source(path):
        taxi_audits.append(audit_frame(path, label, frame))
        del frame
    gc.collect()

Loading: Urban_Flow_Analytics_Taxi_Dataset_2025-04.csv

### `Urban_Flow_Analytics_Taxi_Dataset_2025-04.csv`

Exact source: data\raw\Urban_Flow_Analytics_Taxi_Dataset_2025-04.csv
Shape: (3970553, 20)
All columns: ['provider_code', 'pickup_timestamp', 'dropoff_timestamp', 'rider_count', 'distance_miles', 'rate_class_id', 'offline_record_flag', 'origin_loc_id', 'dest_loc_id', 'fare_settlement_method', 'base_fare', 'surcharge_misc', 'transit_tax', 'driver_tip_payment', 'toll_total', 'service_improvement_fee', 'charge_total', 'zone_congestion_fee', 'Airport_fee', 'congestion_relief_fee']
Data types:
provider_code               int64[pyarrow]
pickup_timestamp           string[pyarrow]
dropoff_timestamp          string[pyarrow]
rider_count                double[pyarrow]
distance_miles             double[pyarrow]
rate_class_id              double[pyarrow]
offline_record_flag        string[pyarrow]
origin_loc_id               int64[pyarrow]
dest_loc_id                 int64[pyarrow]
fare_settlement_method      int64[pyarrow]
base_fare                  double[pyarrow]
surcharge_misc             double[pyarrow]
transit_tax                double[pyarrow]
driver_tip_payment         double[pyarrow]
toll_total                 double[pyarrow]
service_improvement_fee    double[pyarrow]
charge_total               double[pyarrow]
zone_congestion_fee        double[pyarrow]
Airport_fee                double[pyarrow]
congestion_relief_fee      double[pyarrow]
First 5 rows:

,provider_code,pickup_timestamp,dropoff_timestamp,rider_count,distance_miles,rate_class_id,offline_record_flag,origin_loc_id,dest_loc_id,fare_settlement_method,base_fare,surcharge_misc,transit_tax,driver_tip_payment,toll_total,service_improvement_fee,charge_total,zone_congestion_fee,Airport_fee,congestion_relief_fee
0,1,2025-04-01 00:47:06,2025-04-01 01:13:25,1.0,9.5,1.0,N,138,230,1,38.7,11.0,0.5,11.65,6.94,1.0,69.79,2.5,1.75,0.75
1,2,2025-04-01 00:27:35,2025-04-01 00:38:19,2.0,3.77,1.0,N,138,92,1,17.0,6.0,0.5,4.9,0.0,1.0,31.15,0.0,1.75,0.0
2,2,2025-04-01 00:24:07,2025-04-01 00:35:12,1.0,5.41,1.0,N,132,130,1,22.6,1.0,0.5,5.37,0.0,1.0,32.22,0.0,1.75,0.0
3,1,2025-04-01 00:56:30,2025-04-01 01:00:49,2.0,0.6,1.0,N,79,4,1,6.5,4.25,0.5,2.45,0.0,1.0,14.7,2.5,0.0,0.75
4,2,2025-04-01 00:00:17,2025-04-01 00:16:19,1.0,0.43,1.0,N,161,229,2,4.4,1.0,0.5,0.0,0.0,1.0,10.15,2.5,0.0,0.75

Missing-value counts (every column):
provider_code                   0
pickup_timestamp                0
dropoff_timestamp               0
rider_count                745730
distance_miles                  0
rate_class_id              745730
offline_record_flag        745730
origin_loc_id                   0
dest_loc_id                     0
fare_settlement_method          0
base_fare                       0
surcharge_misc                  0
transit_tax                     0
driver_tip_payment              0
toll_total                      0
service_improvement_fee         0
charge_total                    0
zone_congestion_fee        745730
Airport_fee                745730
congestion_relief_fee           0
Exact duplicate rows within this dataset (after first occurrence): 0
Total deep memory usage (MB): 742.222373
Observed categorical/code columns: ['provider_code', 'rider_count', 'rate_class_id', 'offline_record_flag', 'origin_loc_id', 'dest_loc_id', 'fare_settlement_method']

Value counts: provider_code (including missing; 4 distinct values)
provider_code
2    3135417
1     800747
7      33844
6        545

Value counts: rider_count (including missing; 11 distinct values)
rider_count
1.0     2543892
<NA>     745730
2.0      442205
3.0      108670
4.0       79082
0.0       23101
5.0       18778
6.0        9081
8.0           9
9.0           3
7.0           2

Value counts: rate_class_id (including missing; 8 distinct values)
rate_class_id
1.0     3013813
<NA>     745730
2.0      111623
99.0      45293
5.0       34157
3.0       11394
4.0        8537
6.0           6

Value counts: offline_record_flag (including missing; 3 distinct values)
offline_record_flag
N       3217141
<NA>     745730
Y          7682

Value counts: origin_loc_id (including missing; 261 distinct values)
origin_loc_id
237    185505
161    183586
236    162530
132    160280
230    134155
186    127533
162    124639
142    116410
138    109234
234    107044
163    105721
170    105468
239    103731
68     101533
48      95644
79      93033
249     88171
164     84059
141     83370
140     74842
107     73447
238     73208
263     69376
246     67768
90      60342
229     60088
114     57897
43      57853
113     57332
100     55608
262     54091
231     53966
148     45819
143     43700
144     43379
158     42286
233     41334
137     40319
211     34079
151     31111
75      28497
13      24886
50      24667
87      24575
166     24181
261     21584
125     20820
41      16288
74      14631
88      12918
70      12640
4       11120
24      10867
42      10667
232      8773
209      8077
45       7993
224      7527
264      7356
255      7141
244      6582
116      6430
61       6314
145      6306
226      6200
7        6070
256      5374
65       4942
66       4755
33       4676
37       4668
152      4644
76       4576
97       4527
80       4401
130      4227
25       4218
112      4189
181      4050
129      3942
188      3829
89       3558
225      3525
216      3333
36       3311
17       3277
39       3032
146      2881
197      2881
168      2835
49       2799
243      2748
35       2636
82       2576
260      2549
72       2517
193      2342
179      2223
177      2207
95       2187
71       2098
91       2068
247      1972
223      1878
10       1876
62       1840
198      1826
157      1735
189      1651
265      1635
12       1574
215      1546
85       1536
69       1478
228      1392
40       1383
52       1365
159      1344
258      1281
14       1266
63       1258
205      1238
195      1236
77       1182
213      1141
127      1120
93       1115
196      1092
28       1091
167      1080
134      1066
169      1052
106      1026
182      1016
92       1011
254       995
51        980
191       963
235       963
83        938
55        930
219       929
155       897
56        871
119       863
26        831
78        827
218       826
18        801
222       788
212       779
160       778
133       773
86        760
165       743
250       734
117       719
259       714
241       709
210       686
126       677
47        674
131       673
242       668
174       665
102       629
248       623
217       619
124       613
220       612
180       605
22        588
121       588
81        584
147       564
173       556
227       537
208       533
60        532
257       504
136       491
34        486
123       480
1         473
21        468
135       466
20        456
32        448
190       443
122       438
185       400
139       396
149       394
29        393
203       386
94        386
54        378
38        371
200       363
3         362
202       359
108       332
67        332
19        316
171       289
53        286
150       262
16        250
194       250
252       244
101       228
11        223
192       223
98        216
183       211
207       211
201       210
178       205
175       183
153       151
73        148
9         134
64        126
15        121
31        107
240        94
6          90
128        85
154        78
57         76
96         71
58         62
221        62
120        61
253        49
46         45
118        32
214        32
23         31
184        31
8          28
115        26
59         25
30         24
251        15
27         14
206        11
111        10
2           9
156         8
109         7
245         6
84          5
44          5
204         4
172         4
176         4
199         3
5           3
187         2
105         1

Value counts: dest_loc_id (including missing; 261 distinct values)
dest_loc_id
236    171435
237    168757
161    149471
230    124791
170    110878
162    107268
142    103361
239    103307
68     102416
163     97227
141     96176
234     94640
48      92358
186     85789
238     82583
79      81549
164     81256
229     76812
140     75365
263     74618
246     74148
107     72992
249     68651
231     65094
90      56361
262     56294
233     56114
143     55984
113     51727
100     49265
137     47838
75      45298
148     45039
158     42409
43      42034
114     41514
50      40574
138     40193
144     39952
132     39668
87      35828
211     35136
151     32895
166     31187
13      29836
74      29022
41      25211
125     21894
261     21155
232     20144
42      19647
244     17208
88      17174
4       16931
265     15662
224     15531
24      12436
45      12240
116     11492
209     11302
181     11074
255     10615
243     10575
145     10403
33      10312
7        9819
112      9732
61       9380
264      9230
256      8872
1        7939
25       6959
37       6935
152      6921
226      6871
65       6306
66       6163
49       6086
80       6065
97       5924
95       5845
129      5741
225      5618
17       5590
216      5497
76       5469
89       5319
188      5206
223      5145
127      4641
130      4484
36       4449
10       4118
82       4028
189      3870
39       3707
179      3668
198      3643
40       3462
14       3400
146      3278
260      3257
168      3029
92       2951
197      2910
93       2906
193      2890
228      2878
35       2718
52       2668
62       2597
12       2484
72       2476
177      2364
71       2283
70       2203
91       2160
157      2119
247      2115
205      2102
28       2064
56       2019
215      1948
202      1931
219      1899
196      1872
69       1865
257      1861
195      1798
85       1784
258      1762
220      1720
26       1719
134      1717
106      1654
63       1652
159      1636
160      1617
155      1589
55       1525
165      1496
191      1483
77       1461
217      1454
83       1406
135      1405
200      1370
218      1369
213      1351
121      1337
133      1325
51       1316
124      1306
169      1271
102      1263
119      1259
254      1248
242      1233
86       1233
227      1204
210      1194
235      1177
131      1168
22       1158
18       1151
174      1136
78       1099
173      1098
167      1067
241      1046
123      1029
208      1022
139      1018
203       990
20        964
16        955
194       949
180       945
54        937
149       930
182       904
38        903
171       895
222       888
47        880
21        859
126       856
185       855
252       848
117       838
53        831
250       820
29        791
67        771
136       771
212       755
190       732
259       714
19        698
81        688
98        684
34        666
248       661
147       651
32        625
60        606
192       584
3         575
64        562
201       543
122       540
94        535
175       534
108       525
101       524
15        509
150       503
128       500
9         471
178       465
11        458
154       418
73        404
31        351
183       344
120       297
153       275
240       224
96        219
207       182
46        134
58        130
6         108
57        106
214       100
253       100
221       100
23         82
27         77
206        77
118        77
8          61
172        60
184        60
30         50
115        50
109        45
251        42
111        39
187        39
245        37
84         35
156        35
59         30
204        24
44         18
176        16
5          15
2          11
199         1
99          1

Value counts: fare_settlement_method (including missing; 5 distinct values)
fare_settlement_method
1    2686812
0     745730
2     412754
4      97491
3      27766
Loading: Urban_Flow_Analytics_Taxi_Dataset_2025-05.csv

### `Urban_Flow_Analytics_Taxi_Dataset_2025-05.csv`

Exact source: data\raw\Urban_Flow_Analytics_Taxi_Dataset_2025-05.csv
Shape: (4591845, 20)
All columns: ['provider_code', 'pickup_timestamp', 'dropoff_timestamp', 'rider_count', 'distance_miles', 'rate_class_id', 'offline_record_flag', 'origin_loc_id', 'dest_loc_id', 'fare_settlement_method', 'base_fare', 'surcharge_misc', 'transit_tax', 'driver_tip_payment', 'toll_total', 'service_improvement_fee', 'charge_total', 'zone_congestion_fee', 'Airport_fee', 'congestion_relief_fee']
Data types:
provider_code               int64[pyarrow]
pickup_timestamp           string[pyarrow]
dropoff_timestamp          string[pyarrow]
rider_count                double[pyarrow]
distance_miles             double[pyarrow]
rate_class_id              double[pyarrow]
offline_record_flag        string[pyarrow]
origin_loc_id               int64[pyarrow]
dest_loc_id                 int64[pyarrow]
fare_settlement_method      int64[pyarrow]
base_fare                  double[pyarrow]
surcharge_misc             double[pyarrow]
transit_tax                double[pyarrow]
driver_tip_payment         double[pyarrow]
toll_total                 double[pyarrow]
service_improvement_fee    double[pyarrow]
charge_total               double[pyarrow]
zone_congestion_fee        double[pyarrow]
Airport_fee                double[pyarrow]
congestion_relief_fee      double[pyarrow]
First 5 rows:

,provider_code,pickup_timestamp,dropoff_timestamp,rider_count,distance_miles,rate_class_id,offline_record_flag,origin_loc_id,dest_loc_id,fare_settlement_method,base_fare,surcharge_misc,transit_tax,driver_tip_payment,toll_total,service_improvement_fee,charge_total,zone_congestion_fee,Airport_fee,congestion_relief_fee
0,1,2025-05-01 00:07:06,2025-05-01 00:24:15,1.0,3.7,1.0,N,140,202,1,18.4,4.25,0.5,4.85,0.0,1.0,29.0,2.5,0.0,0.75
1,2,2025-05-01 00:07:44,2025-05-01 00:14:27,1.0,1.03,1.0,N,234,161,1,8.6,1.0,0.5,4.3,0.0,1.0,18.65,2.5,0.0,0.75
2,2,2025-05-01 00:15:56,2025-05-01 00:23:53,1.0,1.57,1.0,N,161,234,2,10.0,1.0,0.5,0.0,0.0,1.0,15.75,2.5,0.0,0.75
3,2,2025-05-01 00:00:09,2025-05-01 00:25:29,1.0,9.48,1.0,N,138,90,1,40.8,6.0,0.5,11.7,6.94,1.0,71.94,2.5,1.75,0.75
4,2,2025-05-01 00:45:07,2025-05-01 00:52:45,1.0,1.8,1.0,N,90,231,1,10.0,1.0,0.5,1.5,0.0,1.0,17.25,2.5,0.0,0.75

Missing-value counts (every column):
provider_code                    0
pickup_timestamp                 0
dropoff_timestamp                0
rider_count                1196176
distance_miles                   0
rate_class_id              1196176
offline_record_flag        1196176
origin_loc_id                    0
dest_loc_id                      0
fare_settlement_method           0
base_fare                        0
surcharge_misc                   0
transit_tax                      0
driver_tip_payment               0
toll_total                       0
service_improvement_fee          0
charge_total                     0
zone_congestion_fee        1196176
Airport_fee                1196176
congestion_relief_fee            0
Exact duplicate rows within this dataset (after first occurrence): 0
Total deep memory usage (MB): 858.239436
Observed categorical/code columns: ['provider_code', 'rider_count', 'rate_class_id', 'offline_record_flag', 'origin_loc_id', 'dest_loc_id', 'fare_settlement_method']

Value counts: provider_code (including missing; 4 distinct values)
provider_code
2    3639117
1     889031
7      63261
6        436

Value counts: rider_count (including missing; 10 distinct values)
rider_count
1.0     2680957
<NA>    1196176
2.0      487777
3.0      107372
4.0       68093
0.0       23967
5.0       17736
6.0        9755
8.0          10
9.0           2

Value counts: rate_class_id (including missing; 8 distinct values)
rate_class_id
1.0     3154399
<NA>    1196176
2.0      130689
99.0      46056
5.0       40191
3.0       13369
4.0       10960
6.0           5

Value counts: offline_record_flag (including missing; 3 distinct values)
offline_record_flag
N       3387410
<NA>    1196176
Y          8259

Value counts: origin_loc_id (including missing; 260 distinct values)
origin_loc_id
237    207287
132    194518
161    185671
236    182316
230    137594
142    137319
162    133083
186    130285
138    126712
234    119851
170    118644
163    116601
239    114611
79     114007
68     113835
48     106837
249     97917
164     96267
141     94193
107     85937
140     83542
238     82873
263     79746
246     79190
229     70055
90      69604
231     65881
114     65542
113     64576
43      61741
100     61027
262     59343
148     56942
143     53429
144     50549
158     50137
233     48318
137     48313
211     39824
151     35716
75      33696
87      33433
50      33305
166     30430
13      28547
125     23980
261     23589
41      21996
74      19173
88      16126
4       15215
42      14364
70      13204
24      13192
232     12586
244     11427
209     10974
7       10960
145     10345
224     10266
255     10208
116      9984
45       9971
226      9785
256      8438
61       8083
264      7596
112      7389
37       7016
65       6851
152      6748
33       6685
80       6577
97       6566
181      6565
66       6175
129      6069
25       5972
76       5398
130      5373
225      5197
146      5117
188      5025
17       5010
89       4965
243      4817
36       4731
49       4459
260      4321
216      4276
82       3995
179      3976
39       3567
197      3553
168      3524
95       3299
223      3187
193      3177
35       2986
198      2969
72       2855
228      2764
91       2678
157      2669
177      2644
71       2605
62       2443
10       2401
189      2310
14       2302
247      2183
127      2182
40       2143
265      2091
195      2041
52       1992
85       1967
159      1811
258      1810
215      1793
63       1767
12       1739
69       1720
196      1623
106      1599
92       1582
83       1564
28       1519
213      1507
26       1472
134      1453
56       1416
93       1407
77       1407
205      1385
133      1384
169      1374
51       1320
167      1255
254      1234
155      1231
55       1230
165      1207
182      1189
78       1171
191      1154
235      1148
219      1127
18       1105
210      1104
212      1092
160      1085
22       1051
241       989
248       985
119       969
123       968
250       958
173       927
257       923
102       923
174       922
220       908
227       901
218       891
217       888
47        884
242       864
126       828
121       822
180       814
34        810
222       805
208       803
131       801
147       789
86        766
135       753
21        724
124       720
149       715
81        712
117       701
60        694
259       687
29        679
136       669
185       604
20        595
94        591
54        589
32        584
67        579
108       571
200       568
1         532
139       526
19        525
3         522
202       514
203       492
122       489
190       468
53        462
171       431
38        407
11        402
252       398
16        393
150       378
178       356
207       342
192       327
98        318
101       304
183       301
175       259
201       257
153       242
9         234
194       217
15        199
73        196
64        170
240       156
128       149
31        146
96        128
6         106
120       105
154       102
57         80
221        79
46         77
58         71
184        67
115        53
214        53
23         47
8          41
253        39
118        34
59         31
206        25
27         24
111        23
251        23
30         19
172        18
156        16
176        14
187        11
109         9
245         8
204         3
2           3
44          2
5           1
99          1
84          1

Value counts: dest_loc_id (including missing; 261 distinct values)
dest_loc_id
237    188616
236    188080
161    159729
230    137055
170    123241
142    117791
162    117692
239    114552
68     113817
163    106611
141    105881
234    105540
48     103606
79      97563
164     94044
186     93013
246     90673
238     90454
229     85342
263     85039
140     84007
107     80898
249     79297
231     77188
143     63626
90      63446
233     62391
262     62151
148     57495
113     56201
137     54851
100     54395
75      52565
158     50291
132     48292
114     48220
50      48110
138     46816
144     46596
43      45323
87      44627
211     41728
151     37406
166     37344
74      35814
13      34263
41      31569
232     25953
42      25402
125     25253
261     24856
244     23949
4       21378
88      20710
265     20490
224     18131
116     16188
24      15127
45      14982
243     14838
181     14225
209     14115
7       14087
255     13653
112     13100
145     13034
61      12194
256     12007
33      11792
37      10163
264      9800
226      9064
152      9010
25       8817
1        8474
80       8223
225      7996
97       7919
129      7857
65       7840
17       7819
49       7780
66       7439
95       7343
223      7269
127      7022
89       6973
216      6745
188      6711
76       6693
36       6583
130      5920
82       5527
179      5294
10       5216
198      5200
14       5036
189      4843
39       4562
260      4513
92       4431
228      4420
146      4367
40       4117
168      4031
93       3734
197      3639
193      3610
62       3505
35       3428
157      3256
177      3112
72       3106
91       3077
52       3047
71       2988
195      2870
70       2854
56       2788
247      2694
205      2589
28       2552
258      2529
26       2477
196      2471
69       2443
12       2436
85       2419
219      2408
257      2369
106      2333
63       2254
55       2247
215      2244
202      2237
160      2184
220      2177
134      2167
155      2100
159      2014
165      1992
191      1970
217      1958
83       1871
22       1870
227      1837
133      1827
218      1812
213      1803
210      1789
51       1750
77       1748
200      1730
169      1730
174      1698
173      1684
102      1677
119      1670
254      1666
135      1655
235      1637
121      1635
18       1580
78       1575
124      1574
123      1520
242      1511
241      1471
131      1441
167      1438
86       1398
208      1392
21       1349
139      1341
20       1298
16       1287
29       1263
203      1241
185      1240
67       1236
126      1227
53       1219
180      1217
182      1210
171      1203
149      1192
47       1188
252      1145
38       1139
136      1119
54       1060
259      1030
222      1024
212       991
250       989
81        981
117       976
19        917
98        912
248       910
32        876
34        873
108       859
190       834
147       834
192       831
122       789
194       787
128       772
94        771
60        753
3         727
15        715
64        709
150       708
175       702
101       684
11        663
201       657
9         641
73        635
178       550
31        501
154       500
183       491
120       405
153       319
240       304
96        286
207       273
46        203
58        168
6         162
214       151
221       148
57        139
253       113
23        113
184       110
118       110
206       107
27        104
172        97
115        77
111        75
30         73
156        70
8          69
245        62
59         62
251        56
84         42
187        36
176        35
109        34
44         31
204        21
5          14
2          10
105         2
110         1

Value counts: fare_settlement_method (including missing; 5 distinct values)
fare_settlement_method
1    2842165
0    1196176
2     418529
4     105323
3      29652
Loading: Urban_Flow_Analytics_Taxi_Dataset_2025-06.csv

### `Urban_Flow_Analytics_Taxi_Dataset_2025-06.csv`

Exact source: data\raw\Urban_Flow_Analytics_Taxi_Dataset_2025-06.csv
Shape: (4322960, 20)
All columns: ['provider_code', 'pickup_timestamp', 'dropoff_timestamp', 'rider_count', 'distance_miles', 'rate_class_id', 'offline_record_flag', 'origin_loc_id', 'dest_loc_id', 'fare_settlement_method', 'base_fare', 'surcharge_misc', 'transit_tax', 'driver_tip_payment', 'toll_total', 'service_improvement_fee', 'charge_total', 'zone_congestion_fee', 'Airport_fee', 'congestion_relief_fee']
Data types:
provider_code               int64[pyarrow]
pickup_timestamp           string[pyarrow]
dropoff_timestamp          string[pyarrow]
rider_count                double[pyarrow]
distance_miles             double[pyarrow]
rate_class_id              double[pyarrow]
offline_record_flag        string[pyarrow]
origin_loc_id               int64[pyarrow]
dest_loc_id                 int64[pyarrow]
fare_settlement_method      int64[pyarrow]
base_fare                  double[pyarrow]
surcharge_misc             double[pyarrow]
transit_tax                double[pyarrow]
driver_tip_payment         double[pyarrow]
toll_total                 double[pyarrow]
service_improvement_fee    double[pyarrow]
charge_total               double[pyarrow]
zone_congestion_fee        double[pyarrow]
Airport_fee                double[pyarrow]
congestion_relief_fee      double[pyarrow]
First 5 rows:

,provider_code,pickup_timestamp,dropoff_timestamp,rider_count,distance_miles,rate_class_id,offline_record_flag,origin_loc_id,dest_loc_id,fare_settlement_method,base_fare,surcharge_misc,transit_tax,driver_tip_payment,toll_total,service_improvement_fee,charge_total,zone_congestion_fee,Airport_fee,congestion_relief_fee
0,1,2025-06-01 00:02:50,2025-06-01 00:39:51,1.0,10.0,1.0,N,138,50,1,47.8,11.0,0.5,20.15,6.94,1.0,87.39,2.5,1.75,0.75
1,2,2025-06-01 00:11:27,2025-06-01 00:35:35,1.0,3.93,1.0,N,158,237,1,24.7,1.0,0.5,6.09,0.0,1.0,36.54,2.5,0.0,0.75
2,1,2025-06-01 00:43:47,2025-06-01 00:49:16,0.0,0.7,1.0,N,230,163,1,7.2,4.25,0.5,2.59,0.0,1.0,15.54,2.5,0.0,0.75
3,1,2025-06-01 00:01:15,2025-06-01 00:42:16,1.0,17.0,2.0,N,132,232,1,70.0,3.25,0.5,5.0,0.0,1.0,79.75,2.5,0.0,0.75
4,7,2025-06-01 00:16:32,2025-06-01 00:16:32,1.0,2.22,1.0,N,48,234,1,20.5,0.0,0.5,5.25,0.0,1.0,31.5,2.5,0.0,0.75

Missing-value counts (every column):
provider_code                    0
pickup_timestamp                 0
dropoff_timestamp                0
rider_count                1212946
distance_miles                   0
rate_class_id              1212946
offline_record_flag        1212946
origin_loc_id                    0
dest_loc_id                      0
fare_settlement_method           0
base_fare                        0
surcharge_misc                   0
transit_tax                      0
driver_tip_payment               0
toll_total                       0
service_improvement_fee          0
charge_total                     0
zone_congestion_fee        1212946
Airport_fee                1212946
congestion_relief_fee            0
Exact duplicate rows within this dataset (after first occurrence): 0
Total deep memory usage (MB): 807.957436
Observed categorical/code columns: ['provider_code', 'rider_count', 'rate_class_id', 'offline_record_flag', 'origin_loc_id', 'dest_loc_id', 'fare_settlement_method']

Value counts: provider_code (including missing; 4 distinct values)
provider_code
2    3423020
1     830851
7      67573
6       1516

Value counts: rider_count (including missing; 11 distinct values)
rider_count
1.0     2458387
<NA>    1212946
2.0      431930
3.0      104573
4.0       68679
0.0       22791
5.0       14992
6.0        8651
8.0           6
9.0           3
7.0           2

Value counts: rate_class_id (including missing; 8 distinct values)
rate_class_id
1.0     2881409
<NA>    1212946
2.0      119754
99.0      47381
5.0       38456
3.0       12400
4.0       10610
6.0           4

Value counts: offline_record_flag (including missing; 3 distinct values)
offline_record_flag
N       3101709
<NA>    1212946
Y          8305

Value counts: origin_loc_id (including missing; 259 distinct values)
origin_loc_id
132    187468
237    180070
161    178638
236    156673
162    129938
230    129722
186    129310
138    115948
170    115490
142    115458
234    112581
79     111518
68     110399
163    105704
48     104919
239    103603
249     92833
164     90736
141     87791
107     80252
246     78611
140     77343
263     73374
238     72260
229     66095
90      65323
231     61894
114     59958
100     59730
113     58177
43      55804
148     55682
262     54026
144     48382
233     48050
143     47313
137     46397
158     46316
211     36226
87      33654
151     33175
50      33014
75      32089
13      29163
261     23191
125     22054
166     21685
41      20793
74      18539
88      15869
4       14541
42      14125
232     13193
70      12911
24      11728
145     11429
7       10999
209     10980
255     10653
244     10644
224      9896
45       9787
226      9766
116      9312
256      8962
61       8937
37       8037
112      7863
80       7301
65       6878
264      6634
66       6599
33       6563
181      6487
97       6386
25       6109
129      5992
130      5744
152      5697
76       5639
225      5557
17       5522
36       5371
188      5221
89       5010
243      4963
146      4958
49       4571
260      4252
216      4195
179      3963
82       3863
197      3820
193      3789
39       3651
168      3562
223      3531
95       3284
177      3058
228      3053
198      2988
35       2908
72       2866
91       2720
71       2630
157      2538
189      2519
62       2495
10       2393
247      2263
14       2241
127      2200
85       2158
195      2044
40       2001
265      1961
12       1919
52       1907
215      1867
63       1773
93       1747
258      1734
106      1722
83       1681
92       1618
159      1607
69       1576
56       1560
28       1536
196      1535
77       1522
134      1479
205      1462
26       1428
55       1416
133      1357
213      1338
254      1317
51       1250
165      1225
191      1193
219      1144
169      1131
155      1131
167      1101
182      1095
160      1077
22       1071
210      1033
235      1032
218      1021
78       1017
217       990
119       990
18        966
102       964
173       932
227       930
123       894
212       868
257       864
121       860
222       852
126       848
250       843
220       838
34        828
248       816
208       813
242       811
180       808
241       795
174       780
131       773
47        757
81        718
21        701
149       693
136       686
135       680
29        674
86        672
117       670
259       670
124       668
60        626
147       615
139       607
67        605
32        599
202       587
54        586
20        568
185       558
122       555
19        546
108       525
3         502
94        497
200       493
190       488
1         486
38        467
53        446
203       442
171       433
192       400
207       399
16        398
252       396
150       379
11        369
178       318
201       302
101       296
175       276
98        275
183       267
194       254
9         222
153       221
73        199
15        186
64        185
31        181
128       167
240       141
96        120
6         120
154       108
8         107
57        104
184       101
120        99
46         84
27         76
221        66
58         59
253        54
214        48
115        46
23         34
118        29
59         28
30         26
111        24
172        24
251        22
156        21
245        15
206        14
109        10
176        10
44          8
2           5
187         5
204         4
84          3
199         1

Value counts: dest_loc_id (including missing; 261 distinct values)
dest_loc_id
237    163708
236    162365
161    151427
230    131018
170    118375
162    116044
68     111257
239    103770
48     102828
142    102799
234    100160
141     98482
163     97748
79      93920
186     93018
164     88616
246     87907
238     80152
263     80082
140     79240
229     78103
107     75060
249     73742
231     71611
233     60613
90      58330
262     57368
143     56289
100     53745
148     53280
137     52901
113     49878
75      48790
158     47030
50      46758
144     45074
87      44006
138     43999
114     43942
132     43386
43      41237
211     37842
151     34894
13      33976
74      33875
41      28866
166     28415
232     24357
261     24101
42      24052
125     22629
244     22423
88      20470
4       20059
265     19982
224     17125
116     14762
45      14064
243     14046
7       13962
255     13833
24      13672
209     13462
145     13362
181     13295
112     13206
61      12509
256     12070
33      11575
37      11182
226      9270
264      9250
25       8729
80       8574
225      8290
17       7902
129      7893
152      7793
65       7775
49       7703
97       7641
66       7610
1        7539
36       7410
95       7241
89       7217
223      7165
216      7039
188      6992
76       6970
127      6469
130      6257
198      5625
179      5514
82       5503
10       5363
92       4959
14       4863
228      4802
189      4761
260      4631
39       4623
146      4593
193      4335
93       4166
168      4061
197      4004
40       3859
62       3538
35       3497
177      3332
72       3096
247      3090
157      3049
91       3016
71       2988
56       2979
52       2937
70       2774
12       2759
195      2723
205      2657
28       2631
258      2605
69       2553
26       2547
85       2531
55       2486
106      2448
219      2438
196      2405
257      2361
63       2304
202      2295
215      2279
134      2255
220      2143
155      2111
83       2068
160      1999
159      1987
191      1983
133      1959
165      1952
218      1908
227      1887
77       1876
22       1841
213      1768
217      1768
119      1750
51       1719
254      1716
210      1691
173      1682
169      1670
121      1666
235      1655
135      1628
200      1623
102      1611
18       1579
174      1572
124      1556
241      1549
242      1530
78       1510
123      1432
208      1425
131      1415
167      1405
21       1376
16       1372
38       1342
139      1320
53       1314
185      1298
182      1291
86       1266
203      1265
29       1259
180      1235
252      1222
171      1189
20       1174
149      1159
126      1155
67       1138
47       1134
54       1122
222      1084
136      1063
259      1056
250       974
117       951
81        945
212       928
98        924
248       913
34        909
19        907
32        902
192       893
190       875
108       833
147       815
122       755
60        752
3         746
9         720
194       718
150       717
175       702
94        701
101       694
201       675
11        665
15        665
64        665
128       651
73        623
178       582
183       514
154       491
31        422
120       417
153       330
207       319
240       307
96        271
46        189
57        182
27        169
58        167
184       152
6         150
214       143
221       142
8         136
118       107
253        94
206        90
23         88
172        74
59         72
251        64
245        60
30         59
115        59
111        55
156        49
109        48
84         38
176        36
187        33
44         25
204        22
5          16
2          12
105         1
99          1

Value counts: fare_settlement_method (including missing; 6 distinct values)
fare_settlement_method
1    2595374
0    1212946
2     386552
4     100163
3      27923
5          2
Loading: Urban_Flow_Analytics_Taxi_Dataset_2025-07.csv

### `Urban_Flow_Analytics_Taxi_Dataset_2025-07.csv`

Exact source: data\raw\Urban_Flow_Analytics_Taxi_Dataset_2025-07.csv
Shape: (3898963, 20)
All columns: ['provider_code', 'pickup_timestamp', 'dropoff_timestamp', 'rider_count', 'distance_miles', 'rate_class_id', 'offline_record_flag', 'origin_loc_id', 'dest_loc_id', 'fare_settlement_method', 'base_fare', 'surcharge_misc', 'transit_tax', 'driver_tip_payment', 'toll_total', 'service_improvement_fee', 'charge_total', 'zone_congestion_fee', 'Airport_fee', 'congestion_relief_fee']
Data types:
provider_code               int64[pyarrow]
pickup_timestamp           string[pyarrow]
dropoff_timestamp          string[pyarrow]
rider_count                double[pyarrow]
distance_miles             double[pyarrow]
rate_class_id              double[pyarrow]
offline_record_flag        string[pyarrow]
origin_loc_id               int64[pyarrow]
dest_loc_id                 int64[pyarrow]
fare_settlement_method      int64[pyarrow]
base_fare                  double[pyarrow]
surcharge_misc             double[pyarrow]
transit_tax                double[pyarrow]
driver_tip_payment         double[pyarrow]
toll_total                 double[pyarrow]
service_improvement_fee    double[pyarrow]
charge_total               double[pyarrow]
zone_congestion_fee        double[pyarrow]
Airport_fee                double[pyarrow]
congestion_relief_fee      double[pyarrow]
First 5 rows:

,provider_code,pickup_timestamp,dropoff_timestamp,rider_count,distance_miles,rate_class_id,offline_record_flag,origin_loc_id,dest_loc_id,fare_settlement_method,base_fare,surcharge_misc,transit_tax,driver_tip_payment,toll_total,service_improvement_fee,charge_total,zone_congestion_fee,Airport_fee,congestion_relief_fee
0,1,2025-07-01 00:29:37,2025-07-01 00:45:30,1.0,7.3,1.0,N,138,74,1,29.6,7.75,0.5,9.0,6.94,1.0,54.79,0.0,1.75,0.0
1,1,2025-07-01 00:23:28,2025-07-01 01:07:44,1.0,17.7,2.0,N,132,142,1,70.0,4.25,0.5,5.0,0.0,1.0,80.75,2.5,1.75,0.0
2,2,2025-07-01 00:53:50,2025-07-01 01:27:12,1.0,9.98,1.0,N,138,48,1,43.6,6.0,0.5,10.87,0.0,1.0,66.97,2.5,1.75,0.75
3,2,2025-07-01 00:58:49,2025-07-01 01:15:55,1.0,10.27,1.0,N,138,229,1,38.7,6.0,0.5,14.1,6.94,1.0,72.24,2.5,1.75,0.75
4,2,2025-07-01 00:09:22,2025-07-01 00:23:54,1.0,2.94,1.0,N,211,97,1,17.0,1.0,0.5,3.0,0.0,1.0,25.75,2.5,0.0,0.75

Missing-value counts (every column):
provider_code                    0
pickup_timestamp                 0
dropoff_timestamp                0
rider_count                1038755
distance_miles                   0
rate_class_id              1038755
offline_record_flag        1038755
origin_loc_id                    0
dest_loc_id                      0
fare_settlement_method           0
base_fare                        0
surcharge_misc                   0
transit_tax                      0
driver_tip_payment               0
toll_total                       0
service_improvement_fee          0
charge_total                     0
zone_congestion_fee        1038755
Airport_fee                1038755
congestion_relief_fee            0
Exact duplicate rows within this dataset (after first occurrence): 1
Total deep memory usage (MB): 728.722553
Observed categorical/code columns: ['provider_code', 'rider_count', 'rate_class_id', 'offline_record_flag', 'origin_loc_id', 'dest_loc_id', 'fare_settlement_method']

Value counts: provider_code (including missing; 4 distinct values)
provider_code
2    3116106
1     725095
7      55438
6       2324

Value counts: rider_count (including missing; 11 distinct values)
rider_count
1.0     2246693
<NA>    1038755
2.0      389469
3.0      103564
4.0       79918
0.0       20544
5.0       12389
6.0        7610
9.0          10
8.0           8
7.0           3

Value counts: rate_class_id (including missing; 8 distinct values)
rate_class_id
1.0     2637013
<NA>    1038755
2.0      106210
99.0      55307
5.0       37925
3.0       12305
4.0       11447
6.0           1

Value counts: offline_record_flag (including missing; 3 distinct values)
offline_record_flag
N       2848340
<NA>    1038755
Y         11868

Value counts: origin_loc_id (including missing; 261 distinct values)
origin_loc_id
132    186031
161    175989
237    148501
186    130750
230    125785
162    125145
236    122720
170    108751
68     102174
138    101122
234    100629
142    100170
163     97429
48      93432
79      91062
239     88130
164     86789
249     80818
141     75918
140     71220
246     71061
107     68696
263     62410
238     60153
229     59952
100     58025
90      57265
231     53025
114     51375
43      50947
113     50413
148     48620
262     45840
233     44566
144     44077
137     43579
158     39643
143     39197
211     33118
87      30682
151     28982
75      28352
13      27834
50      27646
261     22322
166     20460
125     19703
41      18293
74      16713
88      14937
42      12780
4       12412
70      11570
232     11487
209     10483
24      10476
145     10457
255      9874
45       9809
7        9501
244      9360
226      8773
224      8701
61       8413
116      8339
256      7236
130      7045
37       7006
112      6582
66       6474
80       6325
264      6114
65       5954
97       5746
129      5580
33       5568
76       5561
181      5266
152      5210
225      5118
25       5072
188      4929
17       4848
36       4695
89       4556
146      4466
216      4191
243      4121
197      4002
39       3857
49       3849
82       3827
260      3800
193      3628
179      3454
168      3318
95       3236
177      3159
35       2884
72       2876
223      2867
71       2768
91       2611
198      2525
10       2497
228      2356
62       2320
12       2320
265      2252
247      2087
93       2085
189      2031
85       1961
14       1893
195      1879
127      1873
215      1864
157      1838
92       1763
63       1683
205      1631
40       1618
258      1555
69       1546
28       1539
196      1526
159      1504
83       1446
134      1429
52       1422
77       1422
55       1416
56       1366
213      1366
254      1316
219      1238
106      1188
51       1167
191      1154
133      1132
78       1112
169      1094
235      1092
182      1086
218      1074
155      1072
167      1034
26       1031
160      1025
34        990
165       981
18        967
212       940
210       933
119       907
173       902
131       888
227       881
222       869
117       853
102       841
22        836
126       825
47        799
250       785
220       781
248       780
86        775
217       767
242       761
81        754
208       745
241       723
121       694
174       693
180       679
257       678
29        674
60        660
259       651
147       642
123       639
124       638
149       611
135       603
136       599
32        591
122       588
202       588
139       570
20        548
19        536
21        525
203       500
1         497
94        491
185       483
3         465
54        455
190       446
67        437
108       430
38        421
200       405
16        398
53        395
150       378
192       378
101       373
171       372
201       352
11        347
252       329
207       315
98        306
175       276
178       251
183       245
64        226
73        213
9         212
153       200
194       186
15        183
128       156
96        138
240       135
31        131
57        125
184       102
154       102
46        102
120        89
6          85
27         82
253        76
8          71
221        68
58         44
30         37
23         33
214        28
59         24
251        22
118        20
111        17
115        17
172        17
206        13
156        13
187        11
245         9
2           7
176         7
109         5
99          2
199         2
44          2
105         1
5           1
84          1

Value counts: dest_loc_id (including missing; 261 distinct values)
dest_loc_id
161    146074
237    134027
236    129024
230    126212
170    110974
162    109657
68     101740
48      93996
186     91537
163     90972
234     90359
142     90117
239     87960
141     85924
164     84576
79      81377
246     75760
140     71869
229     70835
263     68615
107     67820
238     67342
249     64885
231     61072
233     57200
90      52518
100     52260
137     49843
143     48110
262     47862
148     47506
113     43566
75      43129
50      41720
144     40892
158     39897
87      39553
138     37735
114     37699
132     36368
43      36266
211     34439
13      31447
151     30427
74      30084
166     25764
41      25045
261     22143
232     21819
265     21233
125     21029
42      20944
244     19498
88      19019
4       17743
224     15543
45      13420
116     13289
145     13258
7       12634
209     12530
255     12416
112     11982
181     11868
24      11820
61      11804
243     11600
256     10617
33      10343
37      10205
226      8498
80       8018
129      7743
25       7697
225      7662
65       7585
216      7423
66       7353
76       7154
1        7124
95       7091
264      7061
97       7057
17       7018
49       6765
188      6715
130      6663
152      6587
89       6572
36       6502
223      6437
82       5804
10       5644
127      5610
93       5261
198      5253
92       5024
39       4953
179      4924
146      4430
260      4398
14       4386
193      4117
189      4097
228      4084
168      4016
197      3953
35       3606
40       3452
12       3337
177      3198
62       3184
72       3127
56       3067
205      3005
91       3004
247      2987
70       2975
71       2953
157      2888
28       2809
219      2595
52       2571
258      2518
55       2502
69       2486
195      2483
196      2477
215      2391
134      2323
85       2310
63       2291
202      2287
155      2176
160      2142
218      2137
220      2052
26       2025
159      2005
257      1996
191      1985
106      1948
83       1907
77       1864
213      1833
254      1745
227      1740
235      1739
133      1731
121      1696
51       1692
124      1691
22       1688
102      1687
165      1686
169      1667
174      1644
173      1631
119      1623
242      1607
18       1596
135      1595
131      1578
210      1549
139      1516
200      1513
78       1475
203      1440
167      1436
86       1430
208      1413
241      1392
182      1355
217      1346
53       1331
16       1324
185      1320
29       1216
222      1215
252      1211
180      1211
123      1204
21       1203
171      1188
98       1175
38       1169
126      1151
259      1123
20       1102
149      1091
250      1088
47       1087
136      1075
67       1007
19        991
117       990
81        971
32        967
54        955
34        943
212       938
248       899
122       871
192       868
147       813
60        808
64        754
201       743
3         723
190       718
15        708
108       708
94        692
175       685
9         683
101       671
73        663
150       648
11        600
154       591
128       588
194       508
178       484
183       478
31        422
240       326
120       308
153       288
96        254
184       239
207       234
46        227
58        193
27        183
57        182
253       148
8         148
221       136
6         133
214       119
118       118
23        105
206       102
172        66
30         62
245        61
251        55
59         55
111        54
115        51
109        48
156        44
84         39
176        32
44         28
187        28
5          13
2          11
204        10
99          3
199         1

Value counts: fare_settlement_method (including missing; 5 distinct values)
fare_settlement_method
1    2343668
0    1038755
2     383976
4     105080
3      27484
Loading: Urban_Flow_Analytics_Taxi_Dataset_2025-08.csv

### `Urban_Flow_Analytics_Taxi_Dataset_2025-08.csv`

Exact source: data\raw\Urban_Flow_Analytics_Taxi_Dataset_2025-08.csv
Shape: (3574091, 20)
All columns: ['provider_code', 'pickup_timestamp', 'dropoff_timestamp', 'rider_count', 'distance_miles', 'rate_class_id', 'offline_record_flag', 'origin_loc_id', 'dest_loc_id', 'fare_settlement_method', 'base_fare', 'surcharge_misc', 'transit_tax', 'driver_tip_payment', 'toll_total', 'service_improvement_fee', 'charge_total', 'zone_congestion_fee', 'Airport_fee', 'congestion_relief_fee']
Data types:
provider_code               int64[pyarrow]
pickup_timestamp           string[pyarrow]
dropoff_timestamp          string[pyarrow]
rider_count                double[pyarrow]
distance_miles             double[pyarrow]
rate_class_id              double[pyarrow]
offline_record_flag        string[pyarrow]
origin_loc_id               int64[pyarrow]
dest_loc_id                 int64[pyarrow]
fare_settlement_method      int64[pyarrow]
base_fare                  double[pyarrow]
surcharge_misc             double[pyarrow]
transit_tax                double[pyarrow]
driver_tip_payment         double[pyarrow]
toll_total                 double[pyarrow]
service_improvement_fee    double[pyarrow]
charge_total               double[pyarrow]
zone_congestion_fee        double[pyarrow]
Airport_fee                double[pyarrow]
congestion_relief_fee      double[pyarrow]
First 5 rows:

,provider_code,pickup_timestamp,dropoff_timestamp,rider_count,distance_miles,rate_class_id,offline_record_flag,origin_loc_id,dest_loc_id,fare_settlement_method,base_fare,surcharge_misc,transit_tax,driver_tip_payment,toll_total,service_improvement_fee,charge_total,zone_congestion_fee,Airport_fee,congestion_relief_fee
0,2,2025-08-01 00:52:23,2025-08-01 01:12:20,1.0,8.44,1.0,N,138,141,1,33.8,6.0,0.5,5.0,6.94,1.0,57.49,2.5,1.75,0.0
1,2,2025-08-01 00:03:01,2025-08-01 00:15:33,2.0,4.98,1.0,N,138,193,1,21.2,6.0,0.5,0.0,0.0,1.0,30.45,0.0,1.75,0.0
2,7,2025-08-01 00:24:38,2025-08-01 00:24:38,2.0,1.89,1.0,N,249,45,1,14.2,0.0,0.5,3.99,0.0,1.0,23.94,2.5,0.0,0.75
3,7,2025-08-01 00:48:19,2025-08-01 00:48:19,1.0,2.35,1.0,N,79,229,1,11.4,0.0,0.5,3.43,0.0,1.0,20.58,2.5,0.0,0.75
4,2,2025-08-01 00:25:34,2025-08-01 00:33:18,1.0,2.14,1.0,N,43,48,1,11.4,1.0,0.5,2.57,0.0,1.0,19.72,2.5,0.0,0.75

Missing-value counts (every column):
provider_code                   0
pickup_timestamp                0
dropoff_timestamp               0
rider_count                886234
distance_miles                  0
rate_class_id              886234
offline_record_flag        886234
origin_loc_id                   0
dest_loc_id                     0
fare_settlement_method          0
base_fare                       0
surcharge_misc                  0
transit_tax                     0
driver_tip_payment              0
toll_total                      0
service_improvement_fee         0
charge_total                    0
zone_congestion_fee        886234
Airport_fee                886234
congestion_relief_fee           0
Exact duplicate rows within this dataset (after first occurrence): 0
Total deep memory usage (MB): 668.023365
Observed categorical/code columns: ['provider_code', 'rider_count', 'rate_class_id', 'offline_record_flag', 'origin_loc_id', 'dest_loc_id', 'fare_settlement_method']

Value counts: provider_code (including missing; 4 distinct values)
provider_code
2    2867667
1     656568
7      47276
6       2580

Value counts: rider_count (including missing; 11 distinct values)
rider_count
1.0     2084772
<NA>     886234
2.0      385427
3.0      104083
4.0       79650
0.0       17272
5.0       10545
6.0        6099
8.0           4
9.0           3
7.0           2

Value counts: rate_class_id (including missing; 8 distinct values)
rate_class_id
1.0     2446064
<NA>     886234
2.0      102947
99.0      70383
5.0       43088
3.0       13569
4.0       11802
6.0           4

Value counts: offline_record_flag (including missing; 3 distinct values)
offline_record_flag
N       2683298
<NA>     886234
Y          4559

Value counts: origin_loc_id (including missing; 260 distinct values)
origin_loc_id
132    189212
161    145835
237    127600
186    120561
230    109457
162    108965
236    103850
138    100928
170     98960
79      92165
68      90807
234     90092
48      85426
163     83888
142     82476
239     80643
249     77895
164     75763
141     70450
246     64847
140     64437
107     63400
263     58038
238     54606
229     53592
100     52336
90      51506
148     50914
114     50594
43      46132
231     46059
113     45956
144     43336
262     42161
137     39399
233     39137
158     37243
143     35041
211     31024
87      29381
151     27261
75      26773
50      26251
13      23909
261     20489
166     18513
125     17126
41      16838
74      15819
88      14287
4       12782
42      12250
93      11627
232     11417
70      11106
255     11088
209     10469
24       9749
145      9376
45       9118
61       8571
7        8391
244      8073
224      8062
116      7495
256      7379
226      7263
37       7128
112      6971
66       6406
80       6372
130      5777
65       5753
33       5703
97       5647
264      5382
225      5275
76       5225
188      4940
129      4933
17       4899
25       4868
152      4858
181      4853
36       4579
89       4447
146      4105
49       4013
243      3988
39       3617
216      3614
193      3419
177      3176
179      3110
260      3075
82       3023
197      3016
35       2956
168      2864
72       2837
223      2816
95       2732
71       2658
91       2463
62       2314
195      2281
228      2273
265      2225
10       2179
198      2116
189      2076
12       2042
85       1966
247      1951
14       1854
127      1679
215      1624
157      1609
92       1586
69       1549
63       1477
40       1462
55       1440
77       1426
56       1407
213      1394
205      1349
52       1343
159      1319
28       1286
196      1269
51       1238
258      1236
134      1232
254      1213
106      1208
83       1155
219      1108
235      1094
167      1073
133      1041
191      1038
218      1013
155      1010
182      1001
169       997
78        990
222       977
165       935
119       917
26        895
86        888
18        875
117       842
210       810
173       805
212       805
22        792
160       775
227       758
47        735
250       722
242       713
126       704
217       700
248       697
81        674
241       673
131       672
102       670
220       668
121       660
123       657
208       655
259       640
60        618
174       616
257       610
202       603
180       600
29        593
1         560
135       538
32        537
147       535
136       533
190       510
203       493
124       483
20        482
19        475
21        474
122       467
149       464
185       455
34        448
207       446
139       446
67        428
94        426
54        418
200       410
53        407
38        398
3         398
108       394
171       380
252       337
150       314
101       313
192       307
201       297
11        286
16        284
98        252
183       224
57        214
64        211
175       206
178       204
194       189
153       185
73        173
9         166
128       161
15        129
240       129
120       115
184       108
96        108
46        101
27         94
31         94
6          85
253        76
8          70
154        60
58         48
221        45
214        40
59         37
23         33
30         28
118        24
206        20
115        20
251        16
245        14
172        14
111        12
176        10
156         9
187         8
2           8
109         8
44          5
99          2
204         2
199         1
5           1

Value counts: dest_loc_id (including missing; 260 distinct values)
dest_loc_id
161    123652
237    115585
230    111227
236    109368
170    101556
162     95345
68      91297
48      85873
186     83405
234     82234
163     80076
79      79597
239     79157
141     77262
142     76456
164     76225
246     67319
140     64655
229     63173
107     62646
263     62416
238     60096
249     59726
231     53606
233     51358
90      48022
100     47828
137     45477
148     45467
262     43070
143     42734
75      40019
50      39914
113     39639
144     38382
87      36960
132     36670
138     36297
158     35554
114     35159
43      32739
211     32409
74      28634
151     27837
13      26926
166     23952
41      23356
265     22420
232     20478
42      20112
261     20031
125     18452
88      18211
244     17659
4       17259
224     14578
255     12930
45      12599
116     12325
7       12313
61      12276
145     12254
112     12135
209     11831
181     11359
256     11125
243     11116
24      10985
37      10655
33      10022
225      8184
93       8152
80       8095
226      7863
25       7843
17       7512
49       7477
65       7436
97       7304
76       7254
66       7207
188      7081
95       7052
129      7048
1        6934
216      6895
89       6865
223      6663
36       6554
152      6468
264      6224
130      6190
198      5278
82       5266
127      5254
10       4889
39       4848
179      4842
92       4727
189      4507
14       4424
146      4234
260      4098
168      3960
228      3959
193      3930
35       3655
197      3581
62       3492
177      3399
72       3272
40       3240
91       3132
71       3120
56       3098
157      3059
12       3041
205      2955
195      2932
28       2924
247      2889
196      2602
69       2568
70       2531
55       2479
52       2476
85       2456
219      2451
215      2379
258      2344
202      2285
155      2268
63       2260
159      2128
134      2122
220      2079
160      2079
191      2076
106      2075
218      2055
26       2034
77       1959
257      1949
213      1909
119      1842
83       1829
254      1816
51       1815
235      1727
124      1696
174      1691
169      1681
102      1661
227      1650
165      1650
135      1643
133      1611
121      1603
18       1596
22       1585
167      1572
242      1565
200      1553
173      1546
78       1525
139      1521
86       1505
203      1446
210      1435
53       1432
217      1423
131      1418
241      1405
208      1371
222      1365
252      1326
182      1309
185      1277
38       1266
180      1248
16       1224
29       1218
171      1179
259      1171
126      1171
123      1127
21       1127
20       1125
250      1111
47       1103
98       1102
149      1082
117      1078
67       1063
19       1002
212       982
136       968
81        949
54        947
32        911
248       901
147       880
60        851
3         824
190       788
64        757
192       738
94        738
108       729
122       718
154       712
15        712
175       704
201       695
9         680
101       671
11        641
150       637
128       587
73        573
34        572
194       540
178       514
183       506
31        471
240       339
120       339
153       293
207       277
96        266
46        232
57        217
184       208
58        200
27        186
253       146
6         129
214       124
206       120
23        118
118       110
221       110
8         103
245        99
59         98
251        92
172        74
115        72
30         59
109        52
156        47
187        44
176        40
111        34
44         33
84         28
5          27
204        23
2          16
99          3

Value counts: fare_settlement_method (including missing; 5 distinct values)
fare_settlement_method
1    2182738
0     886234
2     370677
4     106641
3      27801
Loading: Urban_Flow_Analytics_Taxi_Dataset_2025-09.csv

### `Urban_Flow_Analytics_Taxi_Dataset_2025-09.csv`

Exact source: data\raw\Urban_Flow_Analytics_Taxi_Dataset_2025-09.csv
Shape: (4251015, 20)
All columns: ['provider_code', 'pickup_timestamp', 'dropoff_timestamp', 'rider_count', 'distance_miles', 'rate_class_id', 'offline_record_flag', 'origin_loc_id', 'dest_loc_id', 'fare_settlement_method', 'base_fare', 'surcharge_misc', 'transit_tax', 'driver_tip_payment', 'toll_total', 'service_improvement_fee', 'charge_total', 'zone_congestion_fee', 'Airport_fee', 'congestion_relief_fee']
Data types:
provider_code               int64[pyarrow]
pickup_timestamp           string[pyarrow]
dropoff_timestamp          string[pyarrow]
rider_count                double[pyarrow]
distance_miles             double[pyarrow]
rate_class_id              double[pyarrow]
offline_record_flag        string[pyarrow]
origin_loc_id               int64[pyarrow]
dest_loc_id                 int64[pyarrow]
fare_settlement_method      int64[pyarrow]
base_fare                  double[pyarrow]
surcharge_misc             double[pyarrow]
transit_tax                double[pyarrow]
driver_tip_payment         double[pyarrow]
toll_total                 double[pyarrow]
service_improvement_fee    double[pyarrow]
charge_total               double[pyarrow]
zone_congestion_fee        double[pyarrow]
Airport_fee                double[pyarrow]
congestion_relief_fee      double[pyarrow]
First 5 rows:

,provider_code,pickup_timestamp,dropoff_timestamp,rider_count,distance_miles,rate_class_id,offline_record_flag,origin_loc_id,dest_loc_id,fare_settlement_method,base_fare,surcharge_misc,transit_tax,driver_tip_payment,toll_total,service_improvement_fee,charge_total,zone_congestion_fee,Airport_fee,congestion_relief_fee
0,2,2025-09-01 00:19:20,2025-09-01 00:45:17,1.0,9.92,1.0,N,138,114,1,42.9,6.0,0.5,10.73,0.0,1.0,66.13,2.5,1.75,0.75
1,2,2025-09-01 00:15:20,2025-09-01 00:26:08,2.0,6.82,1.0,N,93,157,1,26.8,1.0,0.5,5.86,0.0,1.0,35.16,0.0,0.0,0.0
2,2,2025-09-01 00:06:07,2025-09-01 00:22:23,1.0,3.95,1.0,N,68,13,1,19.8,1.0,0.5,5.11,0.0,1.0,30.66,2.5,0.0,0.75
3,2,2025-09-01 00:49:47,2025-09-01 01:04:49,1.0,3.14,1.0,N,234,87,1,17.7,1.0,0.5,3.52,0.0,1.0,26.97,2.5,0.0,0.75
4,2,2025-09-01 00:05:00,2025-09-01 00:15:32,6.0,2.81,1.0,N,230,151,1,14.9,1.0,0.5,4.13,0.0,1.0,24.78,2.5,0.0,0.75

Missing-value counts (every column):
provider_code                    0
pickup_timestamp                 0
dropoff_timestamp                0
rider_count                1067195
distance_miles                   0
rate_class_id              1067195
offline_record_flag        1067195
origin_loc_id                    0
dest_loc_id                      0
fare_settlement_method           0
base_fare                        0
surcharge_misc                   0
transit_tax                      0
driver_tip_payment               0
toll_total                       0
service_improvement_fee          0
charge_total                     0
zone_congestion_fee        1067195
Airport_fee                1067195
congestion_relief_fee            0
Exact duplicate rows within this dataset (after first occurrence): 0
Total deep memory usage (MB): 794.543067
Observed categorical/code columns: ['provider_code', 'rider_count', 'rate_class_id', 'offline_record_flag', 'origin_loc_id', 'dest_loc_id', 'fare_settlement_method']

Value counts: provider_code (including missing; 4 distinct values)
provider_code
2    3374033
1     817547
7      56583
6       2852

Value counts: rider_count (including missing; 10 distinct values)
rider_count
1.0     2563028
<NA>    1067195
2.0      434358
3.0       89427
4.0       55742
0.0       22186
5.0       12387
6.0        6689
8.0           2
7.0           1

Value counts: rate_class_id (including missing; 8 distinct values)
rate_class_id
1.0     2912913
<NA>    1067195
2.0      113658
99.0      85745
5.0       44993
3.0       15618
4.0       10890
6.0           3

Value counts: offline_record_flag (including missing; 3 distinct values)
offline_record_flag
N       3174177
<NA>    1067195
Y          9643

Value counts: origin_loc_id (including missing; 259 distinct values)
origin_loc_id
237    188291
132    188038
161    168870
236    162663
186    137085
162    128866
230    122563
170    113174
234    113163
68     113103
138    111701
142    111678
79     108260
239    100203
163     99947
48      97386
249     92782
164     90202
141     87794
246     84437
107     79815
140     77869
238     73787
263     72231
90      65696
231     65221
229     64511
114     61656
113     59183
100     58738
148     55953
262     55913
43      54045
144     48018
143     47740
137     46331
158     45783
233     44671
211     38561
87      35168
50      32582
75      31661
151     31430
13      28609
166     24327
261     23261
125     22617
41      18077
74      17475
88      16700
4       14470
232     13580
42      12949
70      12717
24      11547
209     11002
45       9861
255      9698
244      9562
224      9433
145      9254
7        8835
116      8199
61       8096
226      7368
256      7078
93       6768
37       6728
112      6719
33       6656
97       6321
65       6164
264      6080
80       6070
66       5860
152      5654
25       5517
181      5201
225      4945
129      4859
188      4760
146      4706
76       4584
243      4530
17       4424
89       4394
130      4122
49       3999
36       3908
193      3567
216      3461
179      3319
39       3263
223      3024
260      2925
95       2881
177      2816
197      2742
168      2647
35       2645
72       2627
71       2443
82       2401
62       2314
91       2222
195      2190
228      2157
265      2135
10       2095
189      2086
127      1979
14       1978
198      1895
157      1869
85       1827
247      1806
40       1778
52       1729
69       1582
92       1438
215      1435
106      1343
55       1321
12       1315
205      1311
213      1304
56       1283
159      1254
77       1248
51       1220
63       1178
254      1156
34       1116
26       1095
28       1093
165      1082
219      1040
133      1028
222      1015
235      1014
134      1012
196      1004
258      1004
167       991
182       990
119       989
83        974
169       949
218       938
191       928
155       896
78        883
210       871
18        869
86        811
227       793
217       791
117       765
212       734
160       728
123       715
22        710
131       700
241       694
220       694
121       682
173       671
202       669
47        666
248       661
250       646
242       636
81        628
257       612
102       601
126       599
174       593
208       591
29        587
135       566
136       562
149       557
1         551
259       550
60        547
54        510
32        503
21        501
124       501
139       486
200       476
20        470
108       459
122       450
147       448
180       439
203       433
19        433
185       432
67        415
38        414
150       379
94        372
207       365
190       362
3         361
171       349
53        326
16        319
101       313
194       311
11        306
252       276
178       273
192       268
183       258
201       249
98        233
64        212
175       193
153       171
128       166
9         157
15        141
73        141
57        118
31        113
240       110
6         104
120       101
96         82
46         81
221        63
8          59
154        58
184        50
253        48
58         47
23         44
214        34
115        31
118        27
172        27
59         24
27         22
251        22
111        20
156        19
206        18
30         13
245        12
109        10
176        10
84          6
2           6
44          5
187         5
199         1
204         1

Value counts: dest_loc_id (including missing; 261 distinct values)
dest_loc_id
237    168597
236    167334
161    140001
230    118951
170    116205
68     109166
162    107286
234    102300
239    102241
142    100884
141     97899
48      95172
79      94840
186     92628
163     91741
246     91675
164     86350
238     81798
140     79266
263     78449
229     77492
107     76883
249     76263
231     75542
90      60170
262     58551
143     57002
233     56830
148     54859
113     53793
137     53007
100     51267
75      47418
50      46883
158     46502
114     46452
87      45024
144     44934
138     41035
211     40874
132     39640
43      39485
13      33536
151     33396
166     31333
74      30221
41      25973
232     24915
125     24291
261     23678
88      21391
42      21157
265     21106
4       20255
244     20008
224     16688
45      14347
255     13760
116     13501
209     13461
7       13432
112     13417
145     13393
24      12886
181     12748
243     12383
33      12161
61      12095
256     11953
37       9991
25       8648
80       8346
226      8206
1        8052
152      7931
49       7807
65       7805
97       7778
225      7714
95       7502
66       7198
17       7170
264      7141
129      6877
223      6752
89       6682
188      6573
76       6455
216      6424
93       6406
36       5924
127      5635
130      5160
82       5106
179      4890
198      4851
189      4654
146      4605
92       4567
14       4458
193      4365
39       4256
10       4213
260      4039
168      3998
228      3984
40       3906
62       3546
35       3314
177      3286
197      3231
195      3219
157      3111
56       3031
52       2928
247      2811
72       2780
71       2728
91       2707
70       2620
69       2532
196      2478
205      2467
28       2435
106      2322
202      2320
26       2320
85       2242
220      2208
257      2184
12       2121
55       2080
258      2026
215      1998
159      1993
219      1992
63       1972
134      1966
155      1930
160      1911
218      1894
165      1863
217      1840
200      1814
83       1777
133      1775
227      1762
213      1758
51       1757
119      1752
191      1670
174      1664
77       1659
254      1652
235      1648
121      1598
242      1589
22       1587
135      1517
169      1516
18       1495
210      1459
78       1443
182      1436
124      1414
131      1403
208      1396
102      1384
222      1382
241      1376
167      1373
86       1363
173      1322
38       1321
123      1286
139      1217
203      1194
194      1191
29       1188
53       1184
185      1153
67       1124
20       1112
250      1085
180      1084
171      1075
252      1074
34       1067
16       1063
21       1052
126      1051
149      1028
54       1016
259      1012
136       992
47        981
117       940
19        932
81        916
212       893
248       858
32        850
98        836
147       766
3         742
60        731
94        719
64        704
192       701
101       700
108       694
175       688
190       682
128       682
150       648
11        627
9         622
15        584
178       582
122       576
154       573
201       554
73        501
183       483
120       382
31        378
240       333
153       284
207       277
96        231
58        169
57        167
46        163
253       136
214       134
23        133
221       130
6         121
206       116
184       114
118       112
8          91
115        86
172        78
27         75
251        72
59         60
245        49
30         49
187        48
111        46
84         43
156        43
109        41
176        40
44         29
5          20
204        20
2          18
99          2
105         1

Value counts: fare_settlement_method (including missing; 5 distinct values)
fare_settlement_method
1    2676305
0    1067195
2     372069
4     107514
3      27932
Loading: Urban_Flow_Analytics_Taxi_Dataset_2025-10.csv

### `Urban_Flow_Analytics_Taxi_Dataset_2025-10.csv`

Exact source: data\raw\Urban_Flow_Analytics_Taxi_Dataset_2025-10.csv
Shape: (4428699, 20)
All columns: ['provider_code', 'pickup_timestamp', 'dropoff_timestamp', 'rider_count', 'distance_miles', 'rate_class_id', 'offline_record_flag', 'origin_loc_id', 'dest_loc_id', 'fare_settlement_method', 'base_fare', 'surcharge_misc', 'transit_tax', 'driver_tip_payment', 'toll_total', 'service_improvement_fee', 'charge_total', 'zone_congestion_fee', 'Airport_fee', 'congestion_relief_fee']
Data types:
provider_code               int64[pyarrow]
pickup_timestamp           string[pyarrow]
dropoff_timestamp          string[pyarrow]
rider_count                double[pyarrow]
distance_miles             double[pyarrow]
rate_class_id              double[pyarrow]
offline_record_flag        string[pyarrow]
origin_loc_id               int64[pyarrow]
dest_loc_id                 int64[pyarrow]
fare_settlement_method      int64[pyarrow]
base_fare                  double[pyarrow]
surcharge_misc             double[pyarrow]
transit_tax                double[pyarrow]
driver_tip_payment         double[pyarrow]
toll_total                 double[pyarrow]
service_improvement_fee    double[pyarrow]
charge_total               double[pyarrow]
zone_congestion_fee        double[pyarrow]
Airport_fee                double[pyarrow]
congestion_relief_fee      double[pyarrow]
First 5 rows:

,provider_code,pickup_timestamp,dropoff_timestamp,rider_count,distance_miles,rate_class_id,offline_record_flag,origin_loc_id,dest_loc_id,fare_settlement_method,base_fare,surcharge_misc,transit_tax,driver_tip_payment,toll_total,service_improvement_fee,charge_total,zone_congestion_fee,Airport_fee,congestion_relief_fee
0,1,2025-10-01 00:15:32,2025-10-01 01:04:03,1.0,17.2,2.0,N,132,107,1,70.0,5.0,0.5,0.0,6.94,1.0,83.44,2.5,1.75,0.75
1,7,2025-10-01 00:00:08,2025-10-01 00:00:08,1.0,5.0,1.0,N,107,225,1,28.2,0.0,0.5,8.49,0.0,1.0,42.44,2.5,0.0,0.75
2,2,2025-10-01 00:08:54,2025-10-01 00:14:44,1.0,2.75,1.0,N,263,229,1,12.8,1.0,0.5,3.71,0.0,1.0,22.26,2.5,0.0,0.75
3,1,2025-10-01 00:58:48,2025-10-01 01:04:40,1.0,1.3,1.0,N,211,231,2,7.9,4.25,0.5,0.0,0.0,1.0,13.65,2.5,0.0,0.75
4,2,2025-10-01 00:39:51,2025-10-01 00:49:40,1.0,2.88,1.0,N,230,151,1,14.2,1.0,0.5,3.99,0.0,1.0,23.94,2.5,0.0,0.75

Missing-value counts (every column):
provider_code                   0
pickup_timestamp                0
dropoff_timestamp               0
rider_count                990887
distance_miles                  0
rate_class_id              990887
offline_record_flag        990887
origin_loc_id                   0
dest_loc_id                     0
fare_settlement_method          0
base_fare                       0
surcharge_misc                  0
transit_tax                     0
driver_tip_payment              0
toll_total                      0
service_improvement_fee         0
charge_total                    0
zone_congestion_fee        990887
Airport_fee                990887
congestion_relief_fee           0
Exact duplicate rows within this dataset (after first occurrence): 0
Total deep memory usage (MB): 827.813978
Observed categorical/code columns: ['provider_code', 'rider_count', 'rate_class_id', 'offline_record_flag', 'origin_loc_id', 'dest_loc_id', 'fare_settlement_method']

Value counts: provider_code (including missing; 4 distinct values)
provider_code
2    3480300
1     877225
7      67360
6       3814

Value counts: rider_count (including missing; 10 distinct values)
rider_count
1.0     2755776
<NA>     990887
2.0      467451
3.0      104189
4.0       68445
0.0       22310
5.0       12334
6.0        7294
8.0           9
9.0           4

Value counts: rate_class_id (including missing; 8 distinct values)
rate_class_id
1.0     3140941
<NA>     990887
2.0      122079
99.0     103459
5.0       45128
3.0       15336
4.0       10863
6.0           6

Value counts: offline_record_flag (including missing; 3 distinct values)
offline_record_flag
N       3430189
<NA>     990887
Y          7623

Value counts: origin_loc_id (including missing; 262 distinct values)
origin_loc_id
237    205942
132    192927
161    192289
236    180363
162    137873
186    136064
142    133270
230    132168
138    123378
170    116677
234    116615
163    115826
68     112354
79     111533
239    110329
48     100068
141     94387
249     94115
164     90269
140     84093
107     83339
238     81525
246     81069
263     77535
229     69780
90      66310
114     63531
113     63259
231     62864
262     60720
43      60588
100     57550
148     54070
143     50929
144     48310
137     47898
233     46530
158     43327
211     35958
87      33183
151     33170
75      32934
50      31698
13      28893
166     26899
261     22859
125     21654
41      18429
88      17123
74      16566
4       14979
42      13560
232     12276
24      12232
70      11804
209     10820
255      9629
45       9602
224      9546
244      9514
145      8686
116      8403
7        7939
226      7500
61       6985
112      6774
256      6677
264      6591
65       6250
37       6200
33       6054
97       5923
80       5829
66       5732
152      5465
25       4997
181      4695
225      4693
76       4435
129      4371
243      4345
17       4197
146      4086
188      3992
49       3967
89       3889
130      3634
36       3628
193      3461
216      3137
179      3038
39       2905
223      2837
177      2623
168      2583
228      2548
260      2547
35       2451
72       2310
197      2294
95       2187
71       2060
82       2047
62       2026
91       1985
127      1963
265      1951
10       1938
189      1917
195      1896
14       1843
157      1796
198      1657
247      1652
52       1642
69       1605
40       1600
85       1548
215      1440
159      1430
213      1426
12       1359
205      1348
51       1347
55       1316
254      1265
106      1258
235      1230
77       1202
182      1159
92       1101
219      1077
34       1054
78       1044
167      1042
222      1029
63       1012
28       1007
134      1002
169       995
119       959
196       945
56        927
218       924
86        907
18        903
258       903
191       897
83        881
210       878
220       869
133       861
165       858
155       832
47        828
26        826
117       818
241       774
212       730
202       728
174       712
248       709
242       709
259       707
227       704
217       703
121       681
131       673
250       664
126       660
160       651
81        627
22        620
123       611
1         596
136       594
208       592
257       581
60        579
32        574
93        572
147       566
29        566
139       521
200       519
135       516
102       512
173       507
124       504
54        498
20        488
108       485
185       476
149       459
21        457
203       454
180       442
94        418
67        403
19        402
122       399
38        398
3         359
190       349
207       344
150       334
53        288
171       287
16        271
101       270
183       268
192       243
252       242
11        237
98        225
201       224
178       211
175       210
194       206
128       203
153       181
15        172
9         169
64        160
73        143
240       142
31        100
6          96
46         84
120        78
221        76
8          66
57         62
154        58
96         51
58         47
214        46
115        37
184        34
111        27
118        26
206        22
245        19
23         17
172        17
27         15
253        15
59         15
251        12
109         8
176         8
156         7
2           6
187         6
5           5
30          5
105         2
44          2
84          2
204         2
99          1
199         1

Value counts: dest_loc_id (including missing; 262 distinct values)
dest_loc_id
237    187300
236    185810
161    159841
230    125637
170    120743
162    118299
142    117430
68     111646
239    110742
141    105441
163    105208
234    105056
48      97699
79      96261
186     92388
246     89254
238     89212
164     87174
229     84480
140     84480
263     84201
107     80427
249     76523
231     74170
262     63467
90      62353
233     60693
143     60501
113     56948
137     55946
148     52059
100     51274
75      50163
50      46136
114     45959
43      45148
158     44723
138     44556
144     44094
87      43444
132     41390
211     38539
151     35709
166     35336
13      34202
74      31112
41      26989
261     23704
125     23697
232     23693
88      22223
42      21505
265     20955
4       20942
244     19680
224     17082
24      14108
112     14007
45      13960
255     13857
209     13571
145     13286
116     13201
181     12776
33      12487
7       12479
256     11776
243     11752
61      11116
37       9733
1        8881
25       8600
226      8301
80       8297
264      8273
65       8194
49       7769
97       7736
152      7711
225      7542
66       7456
17       7036
95       6839
129      6513
89       6383
223      6137
76       6056
188      5940
36       5899
216      5896
127      5583
82       5088
179      4646
189      4599
198      4566
130      4548
10       4390
146      4377
14       4301
193      4240
228      4189
40       4096
168      4026
92       4022
39       3895
260      3826
93       3823
62       3300
52       3212
195      3165
35       3030
177      3006
157      2939
197      2872
69       2722
56       2642
72       2566
70       2526
91       2517
71       2458
202      2389
28       2381
220      2358
106      2334
205      2306
12       2247
247      2246
196      2172
257      2152
219      2135
85       2087
159      2014
215      1998
200      1973
213      1971
134      1915
254      1911
55       1906
26       1856
160      1842
155      1822
258      1813
218      1807
235      1801
63       1728
51       1703
174      1654
165      1644
191      1618
217      1613
133      1603
227      1603
78       1555
22       1546
169      1533
241      1514
83       1511
18       1498
77       1497
119      1471
167      1469
242      1460
135      1455
121      1454
210      1435
124      1409
86       1374
182      1364
208      1363
102      1316
20       1262
185      1226
131      1211
222      1207
173      1171
123      1143
139      1132
203      1124
38       1081
34       1080
54       1072
126      1062
29       1059
47       1033
259      1031
117      1027
16       1025
252      1019
250      1017
67       1011
21       1007
136       990
149       971
180       966
32        942
53        936
212       924
171       923
194       911
81        895
248       847
19        800
147       781
98        779
108       773
190       761
60        759
128       749
3         743
64        671
150       655
192       655
154       655
94        643
101       613
201       595
15        595
122       588
11        582
175       572
9         560
178       524
73        520
183       516
31        449
240       316
120       316
153       314
207       270
46        202
96        195
58        156
6         136
57        133
214       129
23        124
206       120
221       119
118        89
184        89
172        88
27         88
8          83
251        71
253        68
30         62
115        60
245        51
156        51
59         50
187        46
111        42
109        38
176        36
84         24
5          24
44         21
204        16
2          13
99          6
199         1
105         1

Value counts: fare_settlement_method (including missing; 5 distinct values)
fare_settlement_method
1    2918737
0     990887
2     399080
4      93891
3      26104
Loading: Urban_Flow_Analytics_Taxi_Dataset_2025-11.csv

### `Urban_Flow_Analytics_Taxi_Dataset_2025-11.csv`

Exact source: data\raw\Urban_Flow_Analytics_Taxi_Dataset_2025-11.csv
Shape: (4181444, 20)
All columns: ['provider_code', 'pickup_timestamp', 'dropoff_timestamp', 'rider_count', 'distance_miles', 'rate_class_id', 'offline_record_flag', 'origin_loc_id', 'dest_loc_id', 'fare_settlement_method', 'base_fare', 'surcharge_misc', 'transit_tax', 'driver_tip_payment', 'toll_total', 'service_improvement_fee', 'charge_total', 'zone_congestion_fee', 'Airport_fee', 'congestion_relief_fee']
Data types:
provider_code               int64[pyarrow]
pickup_timestamp           string[pyarrow]
dropoff_timestamp          string[pyarrow]
rider_count                double[pyarrow]
distance_miles             double[pyarrow]
rate_class_id              double[pyarrow]
offline_record_flag        string[pyarrow]
origin_loc_id               int64[pyarrow]
dest_loc_id                 int64[pyarrow]
fare_settlement_method      int64[pyarrow]
base_fare                  double[pyarrow]
surcharge_misc             double[pyarrow]
transit_tax                double[pyarrow]
driver_tip_payment         double[pyarrow]
toll_total                 double[pyarrow]
service_improvement_fee    double[pyarrow]
charge_total               double[pyarrow]
zone_congestion_fee        double[pyarrow]
Airport_fee                double[pyarrow]
congestion_relief_fee      double[pyarrow]
First 5 rows:

,provider_code,pickup_timestamp,dropoff_timestamp,rider_count,distance_miles,rate_class_id,offline_record_flag,origin_loc_id,dest_loc_id,fare_settlement_method,base_fare,surcharge_misc,transit_tax,driver_tip_payment,toll_total,service_improvement_fee,charge_total,zone_congestion_fee,Airport_fee,congestion_relief_fee
0,7,2025-11-01 00:13:25,2025-11-01 00:13:25,1.0,1.68,1.0,N,43,186,1,14.9,0.0,0.5,1.5,0.0,1.0,22.15,2.5,0.0,0.75
1,2,2025-11-01 00:49:07,2025-11-01 01:01:22,1.0,2.28,1.0,N,142,237,1,14.2,1.0,0.5,4.99,0.0,1.0,24.94,2.5,0.0,0.75
2,1,2025-11-01 00:07:19,2025-11-01 00:20:41,0.0,2.7,1.0,N,163,238,1,15.6,4.25,0.5,4.27,0.0,1.0,25.62,2.5,0.0,0.75
3,2,2025-11-01 00:00:00,2025-11-01 01:01:03,3.0,12.87,1.0,N,138,261,1,66.7,6.0,0.5,0.0,6.94,1.0,86.14,2.5,1.75,0.75
4,1,2025-11-01 00:18:50,2025-11-01 00:49:32,0.0,8.4,1.0,N,138,37,2,39.4,7.75,0.5,0.0,0.0,1.0,48.65,0.0,1.75,0.0

Missing-value counts (every column):
provider_code                    0
pickup_timestamp                 0
dropoff_timestamp                0
rider_count                1014740
distance_miles                   0
rate_class_id              1014740
offline_record_flag        1014740
origin_loc_id                    0
dest_loc_id                      0
fare_settlement_method           0
base_fare                        0
surcharge_misc                   0
transit_tax                      0
driver_tip_payment               0
toll_total                       0
service_improvement_fee          0
charge_total                     0
zone_congestion_fee        1014740
Airport_fee                1014740
congestion_relief_fee            0
Exact duplicate rows within this dataset (after first occurrence): 0
Total deep memory usage (MB): 781.562745
Observed categorical/code columns: ['provider_code', 'rider_count', 'rate_class_id', 'offline_record_flag', 'origin_loc_id', 'dest_loc_id', 'fare_settlement_method']

Value counts: provider_code (including missing; 4 distinct values)
provider_code
2    3295835
1     821333
7      60043
6       4233

Value counts: rider_count (including missing; 10 distinct values)
rider_count
1.0     2518496
<NA>    1014740
2.0      438172
3.0      102742
4.0       70436
0.0       19942
5.0       10455
6.0        6452
8.0           8
7.0           1

Value counts: rate_class_id (including missing; 8 distinct values)
rate_class_id
1.0     2891153
<NA>    1014740
99.0     108669
2.0      102901
5.0       40413
3.0       13922
4.0        9637
6.0           9

Value counts: offline_record_flag (including missing; 3 distinct values)
offline_record_flag
N       3161473
<NA>    1014740
Y          5231

Value counts: origin_loc_id (including missing; 260 distinct values)
origin_loc_id
237    194593
161    182907
236    169621
132    165987
186    130699
162    128230
230    125716
142    124627
239    109906
163    108286
234    108090
138    107700
79     107413
170    106723
68     104306
48      96871
141     90710
249     88121
164     87565
107     80670
140     78448
238     78391
263     76718
246     74555
229     65920
114     60994
90      60556
113     58932
262     57270
100     55664
231     55233
43      53728
148     51711
143     48204
137     46493
144     45691
233     43043
158     38955
211     34737
151     33057
75      32728
50      28603
87      27455
166     26198
13      24089
125     19561
261     19497
41      19274
74      17546
4       15278
88      14939
42      14159
232     12407
24      12152
244     10174
224      9640
70       9142
255      9141
45       9051
145      8881
7        8867
116      8751
209      8149
61       7491
37       7226
226      7124
256      6697
112      6293
264      6138
80       6070
97       5746
152      5509
65       5394
33       5276
66       5226
181      4949
25       4933
76       4920
243      4901
225      4874
129      4695
89       4436
17       4302
188      4233
36       4052
146      3966
49       3860
130      3629
216      3239
193      3199
179      3198
39       3000
223      2952
168      2744
177      2723
260      2656
35       2645
82       2525
228      2404
72       2381
197      2326
95       2227
71       2180
91       2179
127      2129
62       2040
189      2021
198      2015
10       1902
265      1897
14       1824
157      1803
69       1713
85       1711
195      1627
52       1559
213      1545
247      1543
40       1515
159      1449
55       1444
215      1443
235      1434
205      1414
92       1379
51       1378
254      1349
77       1266
63       1234
182      1202
167      1194
106      1179
169      1139
78       1129
28       1114
12       1059
222      1054
117      1025
134      1018
191      1017
196      1014
219      1009
119      1005
26       1005
86        999
165       997
218       995
210       989
133       985
258       982
18        981
56        980
34        947
83        934
155       913
220       891
241       837
47        827
259       808
212       807
217       789
248       789
126       778
250       774
227       767
22        750
121       745
123       745
174       737
202       719
242       716
81        711
160       705
60        687
136       686
208       674
257       642
131       617
32        616
1         593
102       585
173       579
139       566
147       566
29        565
185       560
200       556
124       547
21        547
135       543
20        539
93        531
203       524
108       515
122       482
149       478
67        455
180       454
94        444
3         433
38        416
54        411
19        397
190       370
150       361
16        330
11        317
53        307
171       305
201       301
207       282
101       271
192       270
183       267
252       262
178       243
98        242
153       229
175       200
128       174
194       163
15        162
73        142
9         139
64        134
240       118
6          96
31         89
120        78
46         68
96         67
221        62
57         61
58         59
8          53
115        42
214        38
154        36
184        32
23         27
118        22
156        21
30         18
206        17
27         16
253        15
176        14
172        14
59         14
245        14
251        12
2           5
204         4
199         4
111         4
109         4
187         3
105         1
84          1
5           1

Value counts: dest_loc_id (including missing; 259 distinct values)
dest_loc_id
237    177680
236    173458
161    148960
230    119813
170    110867
162    110084
142    108903
239    107475
68     106241
141    102150
163     98277
234     95094
48      94011
79      90176
186     90034
238     85888
164     84269
263     82763
229     80717
246     80041
140     78640
107     76330
249     71073
231     66477
262     60544
143     58853
90      57009
233     56965
137     52508
113     51762
100     50162
148     48509
75      48485
114     43052
144     41396
50      40896
158     40723
43      40510
138     39060
87      37286
132     36907
211     36858
151     35117
166     33258
74      31473
13      29558
41      27460
232     22400
42      22024
125     21231
261     21143
88      20256
4       20028
244     19821
265     19252
224     16817
24      13716
116     13588
45      12934
7       12620
255     12531
243     12448
145     12427
112     12395
181     11954
209     11610
61      11311
256     11130
33      10922
37       9980
1        8333
226      8070
264      7971
25       7956
80       7917
152      7534
225      7531
49       7360
65       7277
17       7240
97       7229
66       6842
89       6624
129      6533
76       6306
223      6304
95       6269
188      6116
36       5845
127      5737
216      5658
179      5045
82       4939
130      4683
198      4638
189      4348
14       4287
39       4128
168      4056
10       4047
146      3948
92       3929
228      3795
260      3783
193      3758
93       3711
40       3664
62       3210
35       3105
177      3000
52       2985
197      2827
157      2827
56       2718
69       2689
91       2646
72       2610
71       2534
28       2456
220      2355
205      2333
196      2309
195      2225
247      2223
70       2197
202      2193
85       2113
106      2092
215      2073
26       2070
159      2037
213      2023
257      2020
219      2011
258      1953
12       1942
254      1929
155      1927
55       1919
235      1899
134      1871
63       1864
165      1847
200      1827
160      1817
51       1806
217      1801
133      1770
218      1743
18       1723
191      1716
77       1689
78       1646
169      1632
83       1615
174      1582
241      1570
22       1556
227      1541
135      1528
210      1525
119      1510
167      1499
121      1437
86       1430
182      1424
242      1402
124      1360
123      1332
208      1328
185      1327
102      1327
173      1320
38       1262
20       1259
222      1235
131      1219
139      1161
47       1160
203      1152
259      1139
117      1138
21       1129
126      1113
250      1111
136      1083
67       1078
16       1030
149      1029
29       1011
32       1011
81        985
180       974
171       965
54        964
252       949
212       946
248       921
53        921
34        914
60        860
147       827
3         821
94        773
190       719
19        712
108       693
122       663
98        657
64        649
101       624
192       604
201       603
128       592
194       588
150       583
11        576
175       563
15        536
183       524
178       524
154       511
73        494
9         483
120       353
31        345
153       342
240       314
207       244
96        193
58        163
46        136
6         133
206       132
214       127
221       123
57        118
118        97
23         92
8          78
27         78
172        78
115        66
59         66
251        64
184        62
253        57
245        53
156        51
176        48
109        38
30         38
84         36
111        35
44         33
204        31
187        28
5          10
2           8

Value counts: fare_settlement_method (including missing; 5 distinct values)
fare_settlement_method
1    2704695
0    1014740
2     373932
4      67726
3      20351
Loading: Urban_Flow_Analytics_Taxi_Dataset_2025-12.csv

### `Urban_Flow_Analytics_Taxi_Dataset_2025-12.csv`

Exact source: data\raw\Urban_Flow_Analytics_Taxi_Dataset_2025-12.csv
Shape: (4305006, 20)
All columns: ['provider_code', 'pickup_timestamp', 'dropoff_timestamp', 'rider_count', 'distance_miles', 'rate_class_id', 'offline_record_flag', 'origin_loc_id', 'dest_loc_id', 'fare_settlement_method', 'base_fare', 'surcharge_misc', 'transit_tax', 'driver_tip_payment', 'toll_total', 'service_improvement_fee', 'charge_total', 'zone_congestion_fee', 'Airport_fee', 'congestion_relief_fee']
Data types:
provider_code               int64[pyarrow]
pickup_timestamp           string[pyarrow]
dropoff_timestamp          string[pyarrow]
rider_count                double[pyarrow]
distance_miles             double[pyarrow]
rate_class_id              double[pyarrow]
offline_record_flag        string[pyarrow]
origin_loc_id               int64[pyarrow]
dest_loc_id                 int64[pyarrow]
fare_settlement_method      int64[pyarrow]
base_fare                  double[pyarrow]
surcharge_misc             double[pyarrow]
transit_tax                double[pyarrow]
driver_tip_payment         double[pyarrow]
toll_total                 double[pyarrow]
service_improvement_fee    double[pyarrow]
charge_total               double[pyarrow]
zone_congestion_fee        double[pyarrow]
Airport_fee                double[pyarrow]
congestion_relief_fee      double[pyarrow]
First 5 rows:

,provider_code,pickup_timestamp,dropoff_timestamp,rider_count,distance_miles,rate_class_id,offline_record_flag,origin_loc_id,dest_loc_id,fare_settlement_method,base_fare,surcharge_misc,transit_tax,driver_tip_payment,toll_total,service_improvement_fee,charge_total,zone_congestion_fee,Airport_fee,congestion_relief_fee
0,1,2025-12-01 00:37:08,2025-12-01 00:51:10,1.0,2.4,1.0,N,140,48,1,14.2,4.25,0.5,4.0,0.0,1.0,23.95,2.5,0.0,0.75
1,2,2025-12-01 00:03:54,2025-12-01 00:19:18,1.0,8.37,1.0,N,138,262,1,33.1,6.0,0.5,7.77,6.94,1.0,59.56,2.5,1.75,0.0
2,2,2025-12-01 00:40:50,2025-12-01 01:06:54,1.0,15.26,1.0,N,132,255,1,57.6,1.0,0.5,12.02,0.0,1.0,73.87,0.0,1.75,0.0
3,1,2025-12-01 00:21:30,2025-12-01 00:49:35,2.0,18.4,2.0,N,132,79,1,70.0,5.0,0.5,10.0,0.0,1.0,86.5,2.5,1.75,0.75
4,2,2025-12-01 00:00:24,2025-12-01 00:03:34,1.0,0.52,1.0,N,239,238,1,5.8,1.0,0.5,1.62,0.0,1.0,12.42,2.5,0.0,0.0

Missing-value counts (every column):
provider_code                    0
pickup_timestamp                 0
dropoff_timestamp                0
rider_count                1195482
distance_miles                   0
rate_class_id              1195482
offline_record_flag        1195482
origin_loc_id                    0
dest_loc_id                      0
fare_settlement_method           0
base_fare                        0
surcharge_misc                   0
transit_tax                      0
driver_tip_payment               0
toll_total                       0
service_improvement_fee          0
charge_total                     0
zone_congestion_fee        1195482
Airport_fee                1195482
congestion_relief_fee            0
Exact duplicate rows within this dataset (after first occurrence): 0
Total deep memory usage (MB): 804.606282
Observed categorical/code columns: ['provider_code', 'rider_count', 'rate_class_id', 'offline_record_flag', 'origin_loc_id', 'dest_loc_id', 'fare_settlement_method']

Value counts: provider_code (including missing; 4 distinct values)
provider_code
2    3417640
1     825421
7      57416
6       4529

Value counts: rider_count (including missing; 11 distinct values)
rider_count
1.0     2443369
<NA>    1195482
2.0      428566
3.0      112613
4.0       89642
0.0       18827
5.0       10791
6.0        5709
8.0           4
7.0           2
9.0           1

Value counts: rate_class_id (including missing; 8 distinct values)
rate_class_id
1.0     2824227
<NA>    1195482
99.0     117021
2.0       99471
5.0       43038
3.0       15601
4.0       10164
6.0           2

Value counts: offline_record_flag (including missing; 3 distinct values)
offline_record_flag
N       3104510
<NA>    1195482
Y          5014

Value counts: origin_loc_id (including missing; 260 distinct values)
origin_loc_id
237    195814
236    177313
132    164489
161    162409
186    135182
142    133819
162    130877
230    122028
239    113853
234    112736
138    111755
163    107852
68     107679
170    107008
79     105006
48     100601
141     96068
164     90363
249     88828
107     85519
140     84059
238     82889
263     80447
246     75037
229     69234
90      63772
262     60007
114     59887
113     59506
231     59124
100     57779
43      54431
137     50463
143     50289
148     49448
144     48061
233     45604
158     38926
151     35761
211     35706
75      35097
87      31311
50      29804
166     26759
13      24923
261     21855
41      21486
125     19659
74      18371
88      16881
42      15974
4       15952
24      13304
232     12900
244     11784
224     10772
45      10580
116     10217
145     10125
7        9864
209      9670
70       9617
255      8592
226      8332
61       7187
256      6954
112      6663
37       6310
152      6114
33       6016
97       5982
66       5896
65       5714
264      5684
80       5443
243      5350
129      5316
181      5304
25       5174
76       5131
225      4945
188      4663
89       4517
146      4437
17       4335
130      4225
49       4207
179      3842
193      3678
36       3555
216      3384
39       3354
223      3338
82       3196
260      3165
168      2921
35       2835
95       2697
177      2690
72       2636
127      2439
197      2429
91       2387
71       2276
14       2217
189      2200
62       2144
228      2066
198      2011
10       1941
69       1933
265      1930
247      1749
52       1748
159      1726
40       1702
157      1677
85       1670
213      1655
51       1646
55       1574
182      1535
205      1495
92       1489
254      1475
235      1467
215      1456
195      1445
63       1412
167      1393
106      1349
77       1300
28       1270
191      1261
26       1252
78       1243
169      1190
56       1184
196      1181
133      1177
258      1169
83       1169
12       1168
165      1149
86       1142
155      1113
18       1109
134      1105
119      1092
117      1089
219      1086
222      1063
210      1044
218      1034
220       994
241       978
67        960
212       947
242       929
47        929
217       902
250       901
174       895
227       874
248       868
22        849
123       820
126       814
121       809
259       806
81        803
131       788
160       779
60        772
208       740
257       736
136       731
173       726
1         712
32        689
202       688
135       667
185       652
102       648
124       644
29        639
21        629
149       627
147       618
200       600
20        588
34        571
203       570
139       559
108       538
94        535
93        535
180       520
122       516
38        490
54        464
3         458
19        429
190       413
53        394
171       367
16        351
183       348
201       318
150       318
101       313
11        309
207       304
192       299
178       294
252       292
153       278
98        259
175       215
128       213
9         206
15        196
73        168
194       159
64        156
240       149
120       120
31        108
6          97
221        76
57         75
58         73
96         69
154        52
8          51
46         51
184        48
214        42
23         39
115        33
59         32
251        29
118        28
172        27
30         19
156        19
253        18
27         17
245        17
176        14
187        11
206         9
109         7
2           6
111         6
84          4
204         4
5           3
44          3
105         2

Value counts: dest_loc_id (including missing; 261 distinct values)
dest_loc_id
237    175854
236    175705
161    147919
230    118838
162    116064
170    114879
142    112638
239    110449
68     108073
141    104560
48      99725
234     97431
163     97022
186     94781
79      90926
238     89602
164     88026
140     84590
263     84562
229     81152
246     80981
107     79428
249     72037
231     68971
262     64174
143     59814
233     58830
90      58595
137     56234
100     54334
113     51723
75      51194
148     50169
144     44171
114     42618
43      41807
50      41699
158     41074
138     39836
87      39544
132     38376
211     37643
151     36772
166     32355
74      32208
13      31459
41      29244
261     23487
42      23487
232     23315
125     21613
244     21508
88      21385
4       21255
265     20635
224     18294
116     14887
45      14494
24      14486
7       13423
243     13052
209     12902
145     12835
112     12581
255     12214
181     12202
61      11139
256     10886
33      10859
37       9765
1        9757
226      8838
25       8211
152      8068
264      8044
80       7645
225      7637
65       7547
49       7429
66       7330
97       7321
17       7243
129      7206
223      6696
89       6630
95       6624
76       6573
188      6391
127      6162
36       5869
216      5787
179      5478
82       5212
130      5056
198      4825
14       4631
193      4398
189      4343
146      4292
39       4200
10       4184
260      4036
168      3959
92       3824
228      3726
40       3690
93       3340
62       3181
35       3113
177      3095
52       2958
197      2937
72       2897
69       2854
56       2844
157      2803
91       2750
71       2582
70       2575
196      2451
205      2437
220      2419
28       2411
247      2299
12       2215
26       2215
159      2190
195      2134
155      2132
213      2114
219      2105
202      2102
85       2090
106      2058
257      2045
160      2011
51       1993
165      1982
134      1972
215      1958
55       1951
258      1950
254      1931
235      1912
63       1899
191      1873
218      1824
200      1817
78       1789
133      1755
174      1747
67       1741
22       1716
18       1707
83       1697
227      1685
217      1664
77       1659
167      1645
242      1642
169      1639
210      1600
86       1596
241      1587
121      1548
135      1517
182      1466
119      1452
123      1412
185      1410
102      1401
173      1398
124      1395
208      1385
131      1326
222      1297
139      1260
117      1225
203      1200
29       1191
126      1188
47       1188
259      1166
250      1163
20       1147
21       1143
136      1140
149      1123
38       1070
53       1054
16       1037
81       1032
32       1023
54       1023
180      1022
171      1015
248       966
212       959
252       954
60        831
147       827
3         793
108       768
94        739
122       698
190       695
19        676
34        669
98        665
201       658
192       656
178       632
101       624
128       612
150       612
175       600
64        590
11        578
183       559
15        548
9         544
154       513
73        509
194       376
31        350
153       349
120       323
240       287
207       196
96        184
58        165
57        149
6         141
46        140
206       128
23        121
221       114
214       106
118        87
27         76
172        74
251        71
8          68
184        66
245        66
115        64
59         62
253        51
30         49
109        49
156        48
187        36
84         35
176        35
44         31
204        30
111        22
2          11
5          11
99          2
105         1

Value counts: fare_settlement_method (including missing; 5 distinct values)
fare_settlement_method
1    2618772
0    1195482
2     401019
4      69145
3      20588
Loading: Urban_Flow_Analytics_Taxi_Dataset_2026-01.csv

### `Urban_Flow_Analytics_Taxi_Dataset_2026-01.csv`

Exact source: data\raw\Urban_Flow_Analytics_Taxi_Dataset_2026-01.csv
Shape: (3724889, 20)
All columns: ['provider_code', 'pickup_timestamp', 'dropoff_timestamp', 'rider_count', 'distance_miles', 'rate_class_id', 'offline_record_flag', 'origin_loc_id', 'dest_loc_id', 'fare_settlement_method', 'base_fare', 'surcharge_misc', 'transit_tax', 'driver_tip_payment', 'toll_total', 'service_improvement_fee', 'charge_total', 'zone_congestion_fee', 'Airport_fee', 'congestion_relief_fee']
Data types:
provider_code               int64[pyarrow]
pickup_timestamp           string[pyarrow]
dropoff_timestamp          string[pyarrow]
rider_count                double[pyarrow]
distance_miles             double[pyarrow]
rate_class_id              double[pyarrow]
offline_record_flag        string[pyarrow]
origin_loc_id               int64[pyarrow]
dest_loc_id                 int64[pyarrow]
fare_settlement_method      int64[pyarrow]
base_fare                  double[pyarrow]
surcharge_misc             double[pyarrow]
transit_tax                double[pyarrow]
driver_tip_payment         double[pyarrow]
toll_total                 double[pyarrow]
service_improvement_fee    double[pyarrow]
charge_total               double[pyarrow]
zone_congestion_fee        double[pyarrow]
Airport_fee                double[pyarrow]
congestion_relief_fee      double[pyarrow]
First 5 rows:

,provider_code,pickup_timestamp,dropoff_timestamp,rider_count,distance_miles,rate_class_id,offline_record_flag,origin_loc_id,dest_loc_id,fare_settlement_method,base_fare,surcharge_misc,transit_tax,driver_tip_payment,toll_total,service_improvement_fee,charge_total,zone_congestion_fee,Airport_fee,congestion_relief_fee
0,2,2026-01-01 00:54:04,2026-01-01 00:59:37,1.0,0.97,1.0,N,239,238,1,7.2,1.0,0.5,3.66,0.0,1.0,15.86,2.5,0.0,0.0
1,1,2026-01-01 00:34:04,2026-01-01 00:39:47,0.0,0.9,1.0,N,163,162,2,7.9,4.25,0.5,0.0,0.0,1.0,13.65,2.5,0.0,0.75
2,1,2026-01-01 00:57:06,2026-01-01 01:05:59,0.0,1.4,1.0,N,43,237,1,10.7,4.25,0.5,2.5,0.0,1.0,18.95,2.5,0.0,0.75
3,2,2026-01-01 00:15:22,2026-01-01 00:58:10,4.0,5.58,1.0,N,142,209,1,38.7,1.0,0.5,11.11,0.0,1.0,55.56,2.5,0.0,0.75
4,2,2026-01-01 00:27:13,2026-01-01 00:40:43,0.0,2.16,1.0,N,88,144,1,13.5,1.0,0.5,3.85,0.0,1.0,23.1,2.5,0.0,0.75

Missing-value counts (every column):
provider_code                    0
pickup_timestamp                 0
dropoff_timestamp                0
rider_count                1088058
distance_miles                   0
rate_class_id              1088058
offline_record_flag        1088058
origin_loc_id                    0
dest_loc_id                      0
fare_settlement_method           0
base_fare                        0
surcharge_misc                   0
transit_tax                      0
driver_tip_payment               0
toll_total                       0
service_improvement_fee          0
charge_total                     0
zone_congestion_fee        1088058
Airport_fee                1088058
congestion_relief_fee            0
Exact duplicate rows within this dataset (after first occurrence): 0
Total deep memory usage (MB): 696.155977
Observed categorical/code columns: ['provider_code', 'rider_count', 'rate_class_id', 'offline_record_flag', 'origin_loc_id', 'dest_loc_id', 'fare_settlement_method']

Value counts: provider_code (including missing; 4 distinct values)
provider_code
2    2965742
1     710425
7      44705
6       4017

Value counts: rider_count (including missing; 11 distinct values)
rider_count
1.0     2150994
<NA>    1088058
2.0      334370
3.0       72864
4.0       49738
0.0       14787
5.0        9184
6.0        4887
8.0           4
7.0           2
9.0           1

Value counts: rate_class_id (including missing; 8 distinct values)
rate_class_id
1.0     2390495
<NA>    1088058
99.0     110864
2.0       83592
5.0       32030
3.0       11541
4.0        8304
6.0           5

Value counts: offline_record_flag (including missing; 3 distinct values)
offline_record_flag
N       2634494
<NA>    1088058
Y          2337

Value counts: origin_loc_id (including missing; 262 distinct values)
origin_loc_id
237    160343
236    153640
132    152589
161    146641
186    110700
142    110004
162    108703
230    106114
79     100998
239     97465
234     94995
170     93056
68      91085
141     87311
163     86108
138     85190
48      82910
249     79431
140     77329
263     74053
238     72340
107     71411
164     69939
246     64501
229     60609
262     54941
90      54761
114     52777
113     49911
231     49747
137     48731
148     47344
100     46335
143     44737
43      43205
144     39671
233     39194
158     33052
151     31154
75      31131
211     28319
50      25104
87      24766
13      21987
166     21096
41      18530
125     17425
4       16613
74      16448
261     15382
42      14060
88      12577
232     12218
24      11430
7       10044
244      9934
224      9760
255      9175
116      8706
45       8701
145      8499
226      7884
209      7518
70       7428
256      7121
61       7099
37       7066
112      6216
80       6004
76       5582
97       5560
152      5085
33       5067
129      4938
181      4789
225      4700
66       4600
243      4487
65       4485
25       4396
264      4391
36       4385
188      4284
130      4261
89       4225
146      4158
17       4122
49       3901
179      3883
216      3476
223      3416
39       3318
193      3087
260      3035
82       2884
35       2853
168      2837
177      2763
72       2709
197      2688
95       2545
91       2448
71       2271
62       2146
198      2136
10       2050
228      2044
127      2012
189      1980
14       1978
69       1837
85       1652
40       1642
159      1638
247      1598
55       1578
213      1566
215      1559
63       1540
265      1539
52       1501
51       1493
205      1456
77       1425
254      1413
195      1402
182      1383
28       1337
26       1309
235      1303
92       1292
167      1274
258      1223
106      1220
157      1171
191      1165
165      1164
56       1160
83       1151
117      1136
78       1132
155      1128
196      1115
218      1112
86       1101
133      1077
222      1074
210      1074
169      1061
18       1046
134      1043
219      1035
119      1003
241       986
220       964
174       906
22        885
250       883
47        878
227       870
212       869
248       863
242       863
123       841
217       829
121       828
126       795
259       785
131       761
60        733
81        731
257       713
160       708
12        707
185       699
102       696
173       691
202       689
208       689
32        688
136       685
124       666
21        662
34        660
135       659
29        659
149       623
180       605
147       601
139       580
108       536
200       518
203       517
67        504
20        500
122       494
3         491
1         486
94        467
19        453
93        445
54        444
38        402
171       376
53        366
16        348
252       343
11        338
178       329
192       326
150       316
101       306
190       303
201       295
183       278
207       254
98        246
153       229
175       227
128       209
9         198
15        176
73        174
64        169
240       159
194       154
6          95
96         90
31         87
120        82
221        73
154        72
214        66
58         65
57         64
8          56
46         54
115        45
23         36
59         36
172        27
184        26
118        25
30         25
253        21
251        21
206        18
176        18
109        15
245        13
156        12
27         11
111        11
187        11
5           4
84          3
2           3
199         3
105         2
204         2
99          1
44          1

Value counts: dest_loc_id (including missing; 260 distinct values)
dest_loc_id
236    156661
237    146726
161    121571
170     99583
230     99157
142     97680
239     97287
141     95943
68      90437
162     89412
79      89025
234     84880
48      81372
238     80162
263     78681
140     78558
163     77901
186     72294
229     71410
107     70324
246     69485
164     68770
249     64716
231     58699
262     58497
137     54826
143     54754
90      52523
233     51616
75      45722
113     45644
148     44539
100     42045
114     38485
50      37151
144     36355
158     35032
87      33308
151     32343
43      31834
211     30015
74      27790
138     27340
132     26967
166     26835
13      25523
41      25494
232     21306
42      20853
4       20776
125     18859
244     18666
224     16622
265     16286
261     16222
88      16217
116     12850
24      12692
7       12451
45      11932
112     11424
145     11363
255     11349
243     10930
181     10770
61      10619
209     10194
256     10158
37       9854
33       9759
226      8405
80       7553
25       7004
97       6988
152      6964
225      6931
17       6798
76       6697
49       6651
36       6583
129      6461
95       6409
223      6243
65       6143
188      6072
264      6016
89       6002
1        5986
66       5944
216      5583
82       5214
127      5191
179      4990
130      4988
198      4813
93       4479
39       4332
14       4095
10       3854
189      3814
168      3752
260      3721
146      3692
228      3477
193      3394
92       3287
40       3256
35       3210
197      3110
62       3093
177      3055
56       2925
72       2887
91       2840
69       2655
52       2651
28       2620
71       2613
157      2477
205      2368
196      2345
26       2274
220      2222
247      2162
215      2125
195      2085
219      2078
159      2066
155      2053
213      2035
258      2014
85       1970
165      1964
55       1955
202      1927
63       1922
134      1914
106      1860
51       1836
217      1829
257      1825
70       1821
254      1812
235      1802
160      1779
218      1762
191      1755
174      1703
77       1695
86       1686
169      1677
83       1658
18       1651
200      1640
78       1603
135      1603
241      1572
133      1538
22       1538
210      1525
121      1521
167      1491
123      1489
227      1459
182      1431
242      1420
119      1396
102      1392
124      1379
173      1374
185      1345
12       1317
222      1302
131      1294
117      1229
208      1205
139      1203
29       1152
259      1151
126      1148
20       1129
47       1123
21       1119
149      1118
203      1115
136      1089
38       1052
250      1018
180      1004
252       981
67        966
16        962
171       932
32        927
53        911
81        905
248       904
212       884
54        884
147       878
3         815
60        797
19        795
94        748
34        741
108       690
98        668
122       659
192       643
190       635
11        626
201       624
175       594
150       579
64        578
178       573
101       561
128       559
154       558
9         522
15        520
183       509
73        494
194       394
153       355
120       263
240       245
207       219
31        199
58        160
96        156
214       146
221       128
6         124
57        107
206        93
46         91
23         82
118        81
8          76
251        72
172        65
253        64
115        62
27         62
59         58
184        54
30         51
156        49
245        46
111        31
176        30
84         28
109        26
187        25
44         25
204        16
5          14
2          12
99          2

Value counts: fare_settlement_method (including missing; 5 distinct values)
fare_settlement_method
1    2249747
0    1088058
2     314043
4      56400
3      16641
Loading: Urban_Flow_Analytics_Taxi_Dataset_2026-02.csv

### `Urban_Flow_Analytics_Taxi_Dataset_2026-02.csv`

Exact source: data\raw\Urban_Flow_Analytics_Taxi_Dataset_2026-02.csv
Shape: (3399866, 20)
All columns: ['provider_code', 'pickup_timestamp', 'dropoff_timestamp', 'rider_count', 'distance_miles', 'rate_class_id', 'offline_record_flag', 'origin_loc_id', 'dest_loc_id', 'fare_settlement_method', 'base_fare', 'surcharge_misc', 'transit_tax', 'driver_tip_payment', 'toll_total', 'service_improvement_fee', 'charge_total', 'zone_congestion_fee', 'Airport_fee', 'congestion_relief_fee']
Data types:
provider_code               int64[pyarrow]
pickup_timestamp           string[pyarrow]
dropoff_timestamp          string[pyarrow]
rider_count                double[pyarrow]
distance_miles             double[pyarrow]
rate_class_id              double[pyarrow]
offline_record_flag        string[pyarrow]
origin_loc_id               int64[pyarrow]
dest_loc_id                 int64[pyarrow]
fare_settlement_method      int64[pyarrow]
base_fare                  double[pyarrow]
surcharge_misc             double[pyarrow]
transit_tax                double[pyarrow]
driver_tip_payment         double[pyarrow]
toll_total                 double[pyarrow]
service_improvement_fee    double[pyarrow]
charge_total               double[pyarrow]
zone_congestion_fee        double[pyarrow]
Airport_fee                double[pyarrow]
congestion_relief_fee      double[pyarrow]
First 5 rows:

,provider_code,pickup_timestamp,dropoff_timestamp,rider_count,distance_miles,rate_class_id,offline_record_flag,origin_loc_id,dest_loc_id,fare_settlement_method,base_fare,surcharge_misc,transit_tax,driver_tip_payment,toll_total,service_improvement_fee,charge_total,zone_congestion_fee,Airport_fee,congestion_relief_fee
0,7,2026-02-01 00:05:57,2026-02-01 00:05:57,1.0,0.94,1.0,N,107,170,1,7.2,0.0,0.5,0.0,0.0,1.0,12.95,2.5,0.0,0.75
1,7,2026-02-01 00:35:58,2026-02-01 00:35:58,1.0,1.93,1.0,N,234,141,1,11.4,0.0,0.5,3.43,0.0,1.0,20.58,2.5,0.0,0.75
2,2,2026-02-01 00:08:41,2026-02-01 00:39:32,1.0,9.99,1.0,N,138,68,1,44.3,6.0,0.5,11.01,0.0,1.0,67.81,2.5,1.75,0.75
3,1,2026-02-01 00:29:06,2026-02-01 00:41:04,0.0,1.7,1.0,N,209,13,1,12.8,4.25,0.5,3.7,0.0,1.0,22.25,2.5,0.0,0.75
4,1,2026-02-01 00:53:52,2026-02-01 01:11:21,0.0,3.7,1.0,N,249,229,1,19.8,4.25,0.5,6.35,0.0,1.0,31.9,2.5,0.0,0.75

Missing-value counts (every column):
provider_code                    0
pickup_timestamp                 0
dropoff_timestamp                0
rider_count                1023317
distance_miles                   0
rate_class_id              1023317
offline_record_flag        1023317
origin_loc_id                    0
dest_loc_id                      0
fare_settlement_method           0
base_fare                        0
surcharge_misc                   0
transit_tax                      0
driver_tip_payment               0
toll_total                       0
service_improvement_fee          0
charge_total                     0
zone_congestion_fee        1023317
Airport_fee                1023317
congestion_relief_fee            0
Exact duplicate rows within this dataset (after first occurrence): 0
Total deep memory usage (MB): 635.402117
Observed categorical/code columns: ['provider_code', 'rider_count', 'rate_class_id', 'offline_record_flag', 'origin_loc_id', 'dest_loc_id', 'fare_settlement_method']

Value counts: provider_code (including missing; 4 distinct values)
provider_code
2    2716417
1     637609
7      40241
6       5599

Value counts: rider_count (including missing; 10 distinct values)
rider_count
1.0     1974695
<NA>    1023317
2.0      283138
3.0       57521
4.0       36347
0.0       12884
5.0        7700
6.0        4260
9.0           2
8.0           2

Value counts: rate_class_id (including missing; 8 distinct values)
rate_class_id
1.0     2162640
<NA>    1023317
99.0     100895
2.0       70087
5.0       25861
3.0        9874
4.0        7190
6.0           2

Value counts: offline_record_flag (including missing; 3 distinct values)
offline_record_flag
N       2374445
<NA>    1023317
Y          2104

Value counts: origin_loc_id (including missing; 259 distinct values)
origin_loc_id
237    145080
236    138747
161    135273
132    124659
162     99368
186     98677
142     94523
79      94352
230     91000
234     89587
170     87149
239     86904
68      85247
163     79511
141     76648
138     76503
249     74575
48      73701
140     69109
263     66415
238     66240
164     65938
107     65525
246     64503
90      52855
229     52280
262     49504
114     49479
113     48165
231     45703
148     45153
137     44661
100     42166
143     41166
144     36935
43      36547
233     34487
158     30808
75      29110
151     28233
211     26715
166     24304
50      22977
87      22250
13      19886
41      17954
125     16438
4       15351
74      15246
42      13197
261     13022
232     11103
88      10834
24      10779
244      9281
224      9192
145      9134
7        8960
255      8113
116      8053
45       7932
226      7219
61       6913
37       6766
209      6690
70       6516
256      6445
112      5816
76       5404
80       5342
152      5221
97       5218
33       4667
181      4636
225      4623
129      4413
25       4385
188      4361
17       4271
65       4112
146      4060
89       4054
66       4048
243      3986
49       3943
36       3771
264      3703
130      3586
39       3513
179      3402
168      3074
35       2881
223      2845
177      2817
82       2797
216      2732
260      2670
193      2669
72       2565
91       2515
95       2505
71       2352
197      2278
228      2100
198      2075
62       2053
14       1963
189      1902
127      1859
10       1848
157      1797
85       1640
69       1603
159      1559
63       1558
55       1540
247      1524
213      1523
40       1496
77       1469
51       1435
215      1391
26       1375
92       1347
205      1343
254      1327
265      1319
52       1305
195      1254
165      1215
235      1180
106      1179
28       1175
167      1157
182      1152
56       1149
155      1117
258      1115
196      1103
222      1096
133      1092
191      1079
210      1070
78       1020
169      1011
218      1000
83        996
86        986
119       978
134       951
241       943
117       935
220       900
18        892
22        890
242       888
123       871
174       869
217       867
219       848
227       836
248       823
250       817
212       817
47        804
121       796
126       791
131       743
259       721
102       718
160       713
173       711
81        701
136       674
29        666
21        656
257       654
149       637
34        635
208       634
185       632
60        616
32        607
124       600
135       584
202       576
147       574
200       559
139       547
12        544
180       524
108       520
203       503
122       484
93        483
38        477
67        454
94        449
20        438
53        437
3         421
54        420
19        408
1         407
150       358
192       351
252       346
178       345
16        343
171       339
11        331
183       301
101       297
190       291
98        284
201       246
153       231
207       220
175       215
64        188
15        170
73        163
128       157
9         155
194       139
240       123
31         97
120        94
6          91
58         83
96         73
57         63
46         62
221        62
154        52
115        46
8          41
214        40
23         36
184        31
59         31
251        31
118        30
172        27
30         24
253        18
27         17
156        14
176        14
111        13
2          12
109        10
206         9
245         8
84          5
187         4
199         2
5           1
99          1

Value counts: dest_loc_id (including missing; 261 distinct values)
dest_loc_id
236    142107
237    132576
161    106213
170     91717
239     88131
141     86657
142     84734
79      84655
68      83869
230     83172
234     79437
162     79347
238     73215
48      72109
263     70505
163     70312
246     70117
140     69486
107     65129
164     64442
229     64201
186     62689
249     61675
231     54795
262     52764
137     50750
90      50433
143     49964
233     45225
113     44313
148     43278
75      41800
100     36813
114     36749
50      34528
144     34020
158     33128
87      30728
151     29685
211     28690
166     28645
43      27103
74      26470
138     25753
41      23773
132     23768
13      22738
232     20188
42      19790
4       19467
125     17983
244     17552
224     15612
261     15042
88      14367
265     14156
116     12127
24      12077
7       11194
45      11124
112     10615
145     10499
243     10302
255     10298
181     10088
61       9766
209      9520
256      9209
33       8875
37       8712
226      6977
152      6893
80       6664
25       6523
17       6505
49       6431
225      6426
97       6371
76       6274
188      5881
129      5607
89       5604
36       5556
65       5554
95       5529
223      5447
1        5369
264      5191
66       5142
127      4940
216      4543
198      4383
179      4321
82       4233
130      4212
39       4090
14       3802
189      3523
93       3495
168      3352
146      3306
260      3287
228      3216
10       3208
62       3200
40       3083
35       2993
92       2938
91       2800
177      2781
193      2741
72       2673
197      2586
26       2466
56       2462
71       2460
52       2421
69       2346
157      2300
28       2129
205      2074
196      2042
165      1989
220      1962
155      1953
85       1953
247      1927
159      1897
63       1846
215      1836
213      1802
258      1783
55       1773
202      1763
195      1753
106      1718
257      1715
219      1675
134      1665
217      1652
51       1640
70       1612
160      1610
191      1591
254      1587
77       1584
218      1570
235      1564
210      1487
174      1473
200      1437
133      1433
22       1426
241      1420
123      1418
169      1405
167      1387
227      1384
78       1379
121      1376
83       1371
135      1366
86       1341
242      1317
18       1308
124      1267
102      1253
119      1233
173      1225
222      1215
131      1127
208      1119
182      1115
139      1106
117      1094
185      1077
47       1048
149      1038
38       1037
29       1037
21       1016
12       1000
20        980
126       977
259       974
53        961
203       954
136       953
16        921
250       905
252       900
67        878
54        871
81        858
32        838
180       833
212       815
248       803
171       767
147       733
19        721
34        715
108       713
3         694
192       635
60        624
178       612
94        603
11        595
122       583
101       578
150       570
98        569
64        535
175       531
128       529
201       516
190       496
15        493
154       459
183       433
73        424
9         423
194       348
153       295
120       251
240       236
31        230
207       186
58        149
96        131
46        120
6         115
221       115
214       105
57         98
206        92
23         88
27         74
118        72
251        72
172        62
184        55
253        52
8          51
59         50
245        49
115        48
109        40
156        37
176        34
84         34
111        32
30         28
187        23
204        16
44         16
5           8
2           4
105         1
99          1

Value counts: fare_settlement_method (including missing; 5 distinct values)
fare_settlement_method
1    2051661
0    1023317
2     273616
4      38888
3      12384
Loading: Urban_Flow_Analytics_Taxi_Dataset_2026-03.csv

### `Urban_Flow_Analytics_Taxi_Dataset_2026-03.csv`

Exact source: data\raw\Urban_Flow_Analytics_Taxi_Dataset_2026-03.csv
Shape: (3952451, 20)
All columns: ['provider_code', 'pickup_timestamp', 'dropoff_timestamp', 'rider_count', 'distance_miles', 'rate_class_id', 'offline_record_flag', 'origin_loc_id', 'dest_loc_id', 'fare_settlement_method', 'base_fare', 'surcharge_misc', 'transit_tax', 'driver_tip_payment', 'toll_total', 'service_improvement_fee', 'charge_total', 'zone_congestion_fee', 'Airport_fee', 'congestion_relief_fee']
Data types:
provider_code               int64[pyarrow]
pickup_timestamp           string[pyarrow]
dropoff_timestamp          string[pyarrow]
rider_count                double[pyarrow]
distance_miles             double[pyarrow]
rate_class_id              double[pyarrow]
offline_record_flag        string[pyarrow]
origin_loc_id               int64[pyarrow]
dest_loc_id                 int64[pyarrow]
fare_settlement_method      int64[pyarrow]
base_fare                  double[pyarrow]
surcharge_misc             double[pyarrow]
transit_tax                double[pyarrow]
driver_tip_payment         double[pyarrow]
toll_total                 double[pyarrow]
service_improvement_fee    double[pyarrow]
charge_total               double[pyarrow]
zone_congestion_fee        double[pyarrow]
Airport_fee                double[pyarrow]
congestion_relief_fee      double[pyarrow]
First 5 rows:

,provider_code,pickup_timestamp,dropoff_timestamp,rider_count,distance_miles,rate_class_id,offline_record_flag,origin_loc_id,dest_loc_id,fare_settlement_method,base_fare,surcharge_misc,transit_tax,driver_tip_payment,toll_total,service_improvement_fee,charge_total,zone_congestion_fee,Airport_fee,congestion_relief_fee
0,2,2026-03-01 00:02:26,2026-03-01 00:13:45,1.0,2.58,1.0,N,48,151,1,14.2,1.0,0.5,4.99,0.0,1.0,24.94,2.5,0.0,0.75
1,2,2026-03-01 00:19:33,2026-03-01 00:28:21,1.0,1.5,1.0,N,238,166,1,10.0,1.0,0.5,0.0,0.0,1.0,15.0,2.5,0.0,0.0
2,2,2026-03-01 00:07:20,2026-03-01 00:15:12,2.0,0.88,1.0,N,90,249,1,8.6,1.0,0.5,2.87,0.0,1.0,17.22,2.5,0.0,0.75
3,2,2026-03-01 00:16:11,2026-03-01 00:28:20,1.0,1.76,1.0,N,249,137,1,12.1,1.0,0.5,3.57,0.0,1.0,21.42,2.5,0.0,0.75
4,2,2026-03-01 00:20:47,2026-03-01 00:30:44,2.0,1.57,1.0,N,100,142,1,11.4,1.0,0.5,3.43,0.0,1.0,20.58,2.5,0.0,0.75

Missing-value counts (every column):
provider_code                   0
pickup_timestamp                0
dropoff_timestamp               0
rider_count                945748
distance_miles                  0
rate_class_id              945748
offline_record_flag        945748
origin_loc_id                   0
dest_loc_id                     0
fare_settlement_method          0
base_fare                       0
surcharge_misc                  0
transit_tax                     0
driver_tip_payment              0
toll_total                      0
service_improvement_fee         0
charge_total                    0
zone_congestion_fee        945748
Airport_fee                945748
congestion_relief_fee           0
Exact duplicate rows within this dataset (after first occurrence): 0
Total deep memory usage (MB): 738.769326
Observed categorical/code columns: ['provider_code', 'rider_count', 'rate_class_id', 'offline_record_flag', 'origin_loc_id', 'dest_loc_id', 'fare_settlement_method']

Value counts: provider_code (including missing; 4 distinct values)
provider_code
2    3129775
1     764424
7      48796
6       9456

Value counts: rider_count (including missing; 9 distinct values)
rider_count
1.0     2504921
<NA>     945748
2.0      351156
3.0       75898
4.0       48149
0.0       12967
5.0        8482
6.0        5127
8.0           3

Value counts: rate_class_id (including missing; 8 distinct values)
rate_class_id
1.0     2719036
<NA>     945748
99.0     139393
2.0       94180
5.0       33118
3.0       12793
4.0        8182
6.0           1

Value counts: offline_record_flag (including missing; 3 distinct values)
offline_record_flag
N       3001767
<NA>     945748
Y          4936

Value counts: origin_loc_id (including missing; 261 distinct values)
origin_loc_id
237    174403
161    165350
236    157296
132    153791
162    121946
186    121232
230    114682
142    111866
79     104033
234    103024
170    102760
239    101290
163     98068
68      98059
138     96067
48      88440
141     88350
249     86325
140     81116
164     79005
263     74543
107     74236
238     73673
246     69226
229     61875
90      59745
114     57523
113     56151
262     56143
231     53613
100     50738
148     50691
137     47774
143     46240
43      45369
144     42342
233     41565
158     37347
75      32783
151     32064
211     31104
166     25938
50      25577
87      25437
13      24135
41      20184
125     18565
261     16800
74      16629
4       15596
42      15117
88      14097
24      11963
232     11475
244     10022
224      9516
255      9462
145      9181
116      8729
7        8597
45       8565
70       8265
209      7715
61       7653
226      7118
256      6633
37       6580
112      6244
76       6194
97       6028
152      5578
80       5568
65       5091
33       4962
225      4960
25       4843
181      4768
188      4728
264      4624
129      4484
17       4422
146      4402
89       4386
66       4220
243      4150
49       4065
39       3837
36       3749
130      3718
35       3512
216      3205
177      3087
168      3047
72       2951
179      2927
193      2923
223      2845
82       2832
91       2748
71       2681
95       2673
260      2626
197      2249
62       2189
10       2091
198      2072
189      1974
69       1936
127      1866
228      1853
157      1840
213      1835
159      1825
14       1812
247      1809
85       1725
55       1643
51       1642
215      1633
265      1625
77       1599
195      1559
63       1554
254      1531
182      1492
205      1487
52       1425
235      1423
40       1414
86       1379
92       1349
167      1340
222      1295
78       1274
155      1253
117      1234
165      1230
258      1184
26       1176
218      1168
169      1149
196      1120
56       1118
191      1109
28       1098
106      1095
210      1077
119      1059
18       1050
134      1026
219      1001
123       997
133       992
83        977
174       975
34        965
241       957
242       953
248       945
259       937
47        935
12        915
220       915
212       882
250       871
217       862
126       847
81        837
121       830
60        814
22        804
227       795
136       762
32        750
29        736
208       719
160       708
185       704
147       692
131       680
93        669
124       667
135       655
173       653
102       649
202       644
149       640
21        630
257       622
139       612
108       606
203       553
94        548
122       543
20        538
1         527
200       509
3         500
180       483
38        422
53        408
67        404
19        386
54        384
150       382
183       376
11        350
178       340
192       330
171       326
201       319
101       315
190       315
16        312
252       311
153       275
98        257
207       214
175       214
9         198
128       187
194       183
15        176
240       171
64        154
73        131
31        124
120       100
6          89
214        88
58         82
46         81
96         67
221        65
154        55
57         50
184        48
23         45
59         40
172        39
8          34
115        28
206        24
118        22
251        18
30         17
109        17
253        16
176        16
27         15
156        14
2          11
187         9
84          7
245         7
204         4
111         4
99          3
44          3
5           2
199         1

Value counts: dest_loc_id (including missing; 260 distinct values)
dest_loc_id
236    163191
237    157441
161    131327
170    109689
230    103997
239    102275
142    101352
162    100603
141     99612
68      97554
234     91886
79      89990
163     87772
48      87040
238     82893
140     81643
186     79889
263     78967
229     76668
246     76420
164     75340
107     74485
249     68783
231     64522
262     59069
143     57160
90      56890
233     56444
137     55301
113     49859
75      47600
148     46895
100     44394
114     40213
158     39535
50      39299
144     37919
87      36022
138     35115
151     33665
43      33567
211     32535
132     32143
166     31036
74      30252
13      28476
41      26771
42      23079
232     21850
125     20833
4       20716
244     19834
88      18424
261     18357
224     16984
265     15437
116     13367
24      13089
7       12683
45      12379
112     12220
145     12052
255     11922
181     11827
209     11453
243     11238
61      11236
256     10535
33      10488
37       9014
1        7924
152      7856
25       7829
97       7618
49       7599
226      7470
80       7373
76       7325
225      7253
65       7042
17       7039
188      6438
89       6390
223      6297
95       6253
129      5962
66       5930
264      5443
36       5398
127      5377
216      5119
93       5045
179      4819
130      4683
39       4606
82       4566
198      4366
189      4360
10       4062
146      3938
14       3927
168      3787
35       3587
40       3537
260      3514
193      3335
228      3217
177      3194
72       3162
62       3125
91       3100
92       3052
52       2902
56       2841
71       2781
197      2721
69       2695
157      2481
28       2467
205      2304
196      2285
247      2199
26       2187
159      2159
220      2129
213      2086
70       2072
202      2066
85       2065
195      2047
215      2002
55       1995
155      1994
63       1990
165      1962
219      1928
257      1926
51       1887
134      1870
77       1826
106      1823
218      1775
235      1752
254      1746
217      1741
86       1738
258      1709
191      1669
160      1663
200      1626
12       1590
169      1574
167      1559
210      1542
18       1528
174      1515
123      1511
133      1505
78       1485
121      1484
83       1439
241      1432
135      1423
22       1408
227      1406
117      1405
119      1404
222      1383
124      1383
242      1360
182      1298
102      1260
208      1199
259      1180
185      1172
131      1159
139      1156
20       1149
47       1138
29       1126
203      1123
126      1087
136      1082
173      1075
149      1066
38       1017
54       1011
81       1003
21        995
67        981
250       977
16        955
32        930
252       919
53        907
212       900
180       884
171       882
147       862
248       856
34        787
60        780
3         721
108       713
94        710
19        690
150       664
201       646
101       639
192       635
98        633
122       618
11        616
178       602
128       592
64        584
175       566
15        552
190       530
154       505
194       486
183       477
9         462
73        397
31        326
153       312
120       275
240       255
207       212
58        172
214       160
6         159
96        142
46        133
221       111
206       110
253        95
23         93
57         92
118        83
172        80
27         75
59         70
251        67
184        61
245        58
156        57
8          54
30         54
109        50
176        48
115        42
204        34
111        33
5          31
84         27
44         20
187        19
2           6
99          3

Value counts: fare_settlement_method (including missing; 5 distinct values)
fare_settlement_method
1    2608830
0     945748
2     353541
4      31490
3      12842

## 4. Zone/reference audit

Audit supplied zone/reference datasets with the same read-only checks. If no reference file is present, record the missing input explicitly; do not download or invent a replacement.

In [5]:
reference_audits = []
for path in reference_files:
    for label, frame in read_source(path):
        reference_audits.append(audit_frame(path, label, frame))
        del frame
    gc.collect()
if not reference_audits:
    print("MISSING: zone/reference dataset; shape, columns, missing values, and duplicates are unavailable.")

MISSING: zone/reference dataset; shape, columns, missing values, and duplicates are unavailable.

## 5. Step 1 summary and Step 2 investigation candidates

Aggregate audit statistics only. A combined taxi shape is reported only when all files have the same ordered columns. Missing percentages use all taxi rows. Duplicate totals are explicitly scoped to within-file duplicates. Observed schema differences, missing fields, and unusual code values are investigation candidates; no values are changed or declared invalid without competition documentation.

In [6]:
print("Number of taxi source files:", len(taxi_files))
print("Combined taxi disk size: {:.3f} MB ({:.3f} GB)".format(sum(p.stat().st_size for p in taxi_files) / 1e6, sum(p.stat().st_size for p in taxi_files) / 1e9))
if taxi_audits:
    overview = pd.DataFrame([{key: result[key] for key in ("dataset", "rows", "duplicates", "memory_mb")} for result in taxi_audits])
    display(overview)
    total_rows = sum(result["rows"] for result in taxi_audits)
    same_schema = all(result["columns"] == taxi_audits[0]["columns"] for result in taxi_audits)
    print("Combined taxi shape (logical; no concatenation):", (total_rows, len(taxi_audits[0]["columns"])) if same_schema else "Different schemas: see per-file shapes")
    print("Sum of per-file deep memory usage (MB):", sum(result["memory_mb"] for result in taxi_audits))
    print("Exact within-file duplicate total:", sum(result["duplicates"] for result in taxi_audits))
    print("Cross-file duplicates: not evaluated; the above is not a global duplicate count.")
    if same_schema:
        missing = pd.concat([result["missing"] for result in taxi_audits], axis=1).sum(axis=1)
        summary = pd.DataFrame({"missing_count": missing.astype("int64"), "missing_percent": missing / total_rows * 100})
        print("Combined missing values (every column):")
        display(summary)
        print("Columns with missing values to investigate:", summary.index[summary.missing_count > 0].tolist())
        dtype_changes = {column: sorted({result["dtypes"][column] for result in taxi_audits}) for column in taxi_audits[0]["columns"]}
        print("Dtype differences across files:", {column: types for column, types in dtype_changes.items() if len(types) > 1})
        print("Code/count values to investigate against the data dictionary:")
        for column in taxi_audits[0]["frequencies"]:
            counts = pd.concat([result["frequencies"][column] for result in taxi_audits if column in result["frequencies"]])
            combined = counts.groupby(level=0, dropna=False).sum().sort_values(ascending=False)
            print(f"\n{column}: {len(combined)} distinct values; 15 most frequent")
            print(combined.head(15).to_string())
            if len(combined) <= 30:
                print("All observed values:", combined.index.tolist())
for result in reference_audits:
    print("Zone/reference shape:", result["dataset"], (result["rows"], len(result["columns"])))
    print("Zone/reference duplicates:", result["duplicates"])
if not reference_audits:
    print("Zone dataset shape: unavailable ? reference file missing.")
assert source_snapshot == {str(p): (p.stat().st_size, p.stat().st_mtime_ns) for p in source_files}, "Source file size or modification time changed during audit"
print("Source sizes and modification times unchanged.")
print("STOP: Step 1 complete for available inputs. No Step 2 operations performed.")

Number of taxi source files: 12
Combined taxi disk size: 5215.965 MB (5.216 GB)

,dataset,rows,duplicates,memory_mb
0,Urban_Flow_Analytics_Taxi_Dataset_2025-04.csv,3970553,0,742.222373
1,Urban_Flow_Analytics_Taxi_Dataset_2025-05.csv,4591845,0,858.239436
2,Urban_Flow_Analytics_Taxi_Dataset_2025-06.csv,4322960,0,807.957436
3,Urban_Flow_Analytics_Taxi_Dataset_2025-07.csv,3898963,1,728.722553
4,Urban_Flow_Analytics_Taxi_Dataset_2025-08.csv,3574091,0,668.023365
5,Urban_Flow_Analytics_Taxi_Dataset_2025-09.csv,4251015,0,794.543067
6,Urban_Flow_Analytics_Taxi_Dataset_2025-10.csv,4428699,0,827.813978
7,Urban_Flow_Analytics_Taxi_Dataset_2025-11.csv,4181444,0,781.562745
8,Urban_Flow_Analytics_Taxi_Dataset_2025-12.csv,4305006,0,804.606282
9,Urban_Flow_Analytics_Taxi_Dataset_2026-01.csv,3724889,0,696.155977
10,Urban_Flow_Analytics_Taxi_Dataset_2026-02.csv,3399866,0,635.402117
11,Urban_Flow_Analytics_Taxi_Dataset_2026-03.csv,3952451,0,738.769326

Combined taxi shape (logical; no concatenation): (48601782, 20)
Sum of per-file deep memory usage (MB): 9084.018655
Exact within-file duplicate total: 1
Cross-file duplicates: not evaluated; the above is not a global duplicate count.
Combined missing values (every column):

                         missing_count  missing_percent
provider_code                        0         0.000000
pickup_timestamp                     0         0.000000
dropoff_timestamp                    0         0.000000
rider_count                   12405268        25.524307
distance_miles                       0         0.000000
rate_class_id                 12405268        25.524307
offline_record_flag           12405268        25.524307
origin_loc_id                        0         0.000000
dest_loc_id                          0         0.000000
fare_settlement_method               0         0.000000
base_fare                            0         0.000000
surcharge_misc                       0         0.000000
transit_tax                          0         0.000000
driver_tip_payment                   0         0.000000
toll_total                           0         0.000000
service_improvement_fee              0         0.000000
charge_total                         0         0.000000
zone_congestion_fee           12405268        25.524307
Airport_fee                   12405268        25.524307
congestion_relief_fee                0         0.000000

Columns with missing values to investigate: ['rider_count', 'rate_class_id', 'offline_record_flag', 'zone_congestion_fee', 'Airport_fee']
Dtype differences across files: {}
Code/count values to investigate against the data dictionary:

provider_code: 4 distinct values; 15 most frequent
provider_code
2    38561069
1     9356276
7      642536
6       41901
All observed values: [2, 1, 7, 6]

rider_count: 11 distinct values; 15 most frequent
rider_count
1.0     28925980
<NA>    12405268
2.0      4874019
3.0      1143516
4.0       793921
0.0       231578
5.0       145773
6.0        81614
8.0           69
9.0           29
7.0           15
All observed values: [1.0, <NA>, 2.0, 3.0, 4.0, 0.0, 5.0, 6.0, 8.0, 9.0, 7.0]

rate_class_id: 8 distinct values; 15 most frequent
rate_class_id
1.0     33174103
<NA>    12405268
2.0      1257191
99.0     1030466
5.0       458398
3.0       157722
4.0       118586
6.0           48
All observed values: [1.0, <NA>, 2.0, 99.0, 5.0, 3.0, 4.0, 6.0]

offline_record_flag: 3 distinct values; 15 most frequent
offline_record_flag
N       36118953
<NA>    12405268
Y          77561
All observed values: ['N', <NA>, 'Y']

origin_loc_id: 262 distinct values; 15 most frequent
origin_loc_id
237    2113429
132    2059989
161    2023458
236    1867732
186    1508078
162    1477633
230    1450984
142    1371620
170    1273860
234    1268407
138    1266238
79     1233380
68     1230581
239    1210668
163    1204941

dest_loc_id: 263 distinct values; 15 most frequent
dest_loc_id
236    1924538
237    1916867
161    1686185
230    1399868
170    1328707
162    1267101
68     1227513
142    1214145
239    1207346
141    1155987
234    1129017
48     1105789
163    1100867
79     1069879
186    1031465

fare_settlement_method: 6 distinct values; 15 most frequent
fare_settlement_method
1    30479504
0    12405268
2     4459788
4      979752
3      277468
5           2
All observed values: [1, 0, 2, 4, 3, 5]
Zone dataset shape: unavailable ? reference file missing.
Source sizes and modification times unchanged.
STOP: Step 1 complete for available inputs. No Step 2 operations performed.

## Recorded findings ? available inputs only

- **Taxi sources:** 12 monthly CSV files, April 2025 through March 2026. Exact filenames and per-file shapes appear above.
- **Combined source size:** 5,215.965 MB (5.216 GB, decimal). Summed deep dataframe memory is 9,084.019 MB; files were loaded separately.
- **Logical combined taxi shape:** **48,601,782 rows ? 20 columns**. All monthly files have matching ordered columns and inferred dtypes. No combined dataframe or dataset file was created.
- **Zone/reference shape:** unavailable because no zone/reference dataset was present in `data/raw/`. This part of Step 1 remains pending until the file is supplied.
- **Missing values:** `rider_count`, `rate_class_id`, `offline_record_flag`, `zone_congestion_fee`, and `Airport_fee` each have **12,405,268 missing values (25.5243%)**. All other columns have zero missing values under the pandas CSV reader's standard missing-value recognition. Equal totals do not establish that the missing values occur on the same rows.
- **Exact within-file duplicates:** **1** in `Urban_Flow_Analytics_Taxi_Dataset_2025-07.csv`; **0** in each of the other 11 taxi files. Cross-file duplicates were not evaluated; this is not a global duplicate count.

### Columns to investigate in Step 2 ? no rules applied

- The five columns with missing values above need a documented explanation before choosing any treatment.
- `rider_count` includes **231,578 zero values** and **113 values from 7 to 9**. Confirm the intended count semantics and applicable vehicle capacities.
- `rate_class_id` includes **1,030,466 values of 99**. Check the official code definitions.
- `fare_settlement_method` includes **12,405,268 values of 0** and only **2 values of 5**. The count for code 0 equals each of the five missing-value totals; whether these involve the same rows has **not** been tested.
- `provider_code` includes codes **6 and 7**, as well as 1 and 2. Confirm all codes using the competition data dictionary.
- `origin_loc_id` and `dest_loc_id` have **262 and 263 distinct values**, respectively. Reference coverage cannot be checked until the zone dataset is supplied; no zone join was performed.

These are investigation candidates, not confirmed invalid values. Source file sizes and modification times were unchanged at the end of execution. **Stop here: no timestamp parsing, cleaning, anomaly removal, feature engineering, data splitting, or modelling.**

## Step 2: Timestamp validation

This section is independent of Step 1's in-memory variables and can be run on its own. It validates timestamps only, reading the two timestamp columns in **200,000-row chunks**, one monthly file at a time. Source rows and files remain unchanged. Parsed series are temporary audit objects; invalid values are counted, not repaired or removed. No joins, trip durations, speed calculations, anomaly filtering, feature engineering, splitting, or modelling are performed.

In [7]:
from pathlib import Path
from collections import Counter
import re
import pandas as pd
from IPython.display import display

ts_root = next(p for p in [Path.cwd(), *Path.cwd().parents] if (p / "data" / "raw").is_dir())
ts_raw = ts_root / "data" / "raw"
ts_files = sorted(p for p in ts_raw.rglob("Urban_Flow_Analytics_Taxi_Dataset_*.csv")
                  if p.is_file() and "__MACOSX" not in p.relative_to(ts_raw).parts
                  and not any(part.startswith("._") for part in p.relative_to(ts_raw).parts))
assert len(ts_files) == 12, f"Expected 12 monthly taxi CSVs; found {len(ts_files)}"
ts_source_snapshot = {str(p): (p.stat().st_size, p.stat().st_mtime_ns) for p in ts_files}
# These names were observed in the source headers; verify every file before reading data.
ts_pickup = "pickup_timestamp"
ts_dropoff = "dropoff_timestamp"
for ts_path in ts_files:
    ts_columns = pd.read_csv(ts_path, nrows=0).columns.tolist()
    assert all(column in ts_columns for column in [ts_pickup, ts_dropoff]), ts_path.name
    assert re.fullmatch(r"Urban_Flow_Analytics_Taxi_Dataset_\d{4}-\d{2}\.csv", ts_path.name), ts_path.name
print("pandas version:", pd.__version__)
print("Actual timestamp columns:", ts_pickup, ts_dropoff)
print("Chunk size: 200,000 rows; only timestamp columns loaded")
print("Exact source filenames:")
for ts_path in ts_files:
    print(ts_path.relative_to(ts_root))

pandas version: 3.0.5
Actual timestamp columns: pickup_timestamp dropoff_timestamp
Chunk size: 200,000 rows; only timestamp columns loaded
Exact source filenames:
data\raw\Urban_Flow_Analytics_Taxi_Dataset_2025-04.csv
data\raw\Urban_Flow_Analytics_Taxi_Dataset_2025-05.csv
data\raw\Urban_Flow_Analytics_Taxi_Dataset_2025-06.csv
data\raw\Urban_Flow_Analytics_Taxi_Dataset_2025-07.csv
data\raw\Urban_Flow_Analytics_Taxi_Dataset_2025-08.csv
data\raw\Urban_Flow_Analytics_Taxi_Dataset_2025-09.csv
data\raw\Urban_Flow_Analytics_Taxi_Dataset_2025-10.csv
data\raw\Urban_Flow_Analytics_Taxi_Dataset_2025-11.csv
data\raw\Urban_Flow_Analytics_Taxi_Dataset_2025-12.csv
data\raw\Urban_Flow_Analytics_Taxi_Dataset_2026-01.csv
data\raw\Urban_Flow_Analytics_Taxi_Dataset_2026-02.csv
data\raw\Urban_Flow_Analytics_Taxi_Dataset_2026-03.csv

### Parsing, invalid counts, and file date ranges

Use `pd.to_datetime(..., errors="coerce", format="mixed", utc=False)` so parsing does not depend on the first row or chunk. Raw timestamp strings are read without CSV missing-marker conversion. Blank, missing-like, and unparseable strings become `NaT` in temporary parsed series and count as invalid; the source values are untouched. Minima and maxima refer only to successfully parsed timestamps.

Timezone status comes from parsed pandas dtypes, without assuming UTC or a local timezone. If offset-aware timestamps occur, monthly and daily counts use their displayed local calendar dates without converting timezone. Mixed incompatible timezone representations fail explicitly rather than being silently normalized.

The expected month is read from each source filename. Count valid pickups and dropoffs outside that calendar month separately from invalid timestamps. A dropoff just after month-end can be legitimate; these flags are observations, not cleaning rules.

In [8]:
ts_records = []
ts_daily_counts = Counter()
ts_timezone_kinds = {"pickup": set(), "dropoff": set()}
for ts_path in ts_files:
    ts_month = re.search(r"(\d{4}-\d{2})\.csv$", ts_path.name).group(1)
    ts_month_start = pd.Timestamp(ts_month + "-01")
    ts_next_month = ts_month_start + pd.offsets.MonthBegin(1)
    ts_record = {"source_file": ts_path.name, "expected_month": ts_month, "rows": 0}
    for ts_role in ["pickup", "dropoff"]:
        ts_record.update({f"invalid_{ts_role}": 0, f"earliest_{ts_role}": pd.NaT,
                          f"latest_{ts_role}": pd.NaT, f"{ts_role}_before_month": 0,
                          f"{ts_role}_after_month": 0})
    ts_file_zones = {"pickup": set(), "dropoff": set()}
    with pd.read_csv(ts_path, usecols=[ts_pickup, ts_dropoff], dtype="string",
                     keep_default_na=False, parse_dates=False, chunksize=200_000) as ts_reader:
        for ts_chunk in ts_reader:
            ts_record["rows"] += len(ts_chunk)
            for ts_role, ts_column in [("pickup", ts_pickup), ("dropoff", ts_dropoff)]:
                ts_parsed = pd.to_datetime(ts_chunk[ts_column], errors="coerce", format="mixed", utc=False)
                ts_record[f"invalid_{ts_role}"] += int(ts_parsed.isna().sum())
                if not ts_parsed.notna().any():
                    continue
                if not pd.api.types.is_datetime64_any_dtype(ts_parsed.dtype):
                    raise ValueError(f"Mixed timezone representations in {ts_path.name}: {ts_column}; no normalization applied")
                ts_tz = ts_parsed.dt.tz
                ts_zone = "timezone-naive" if ts_tz is None else f"timezone-aware ({ts_tz})"
                ts_file_zones[ts_role].add(ts_zone)
                ts_timezone_kinds[ts_role].add(ts_zone)
                if len(ts_timezone_kinds[ts_role]) > 1:
                    raise ValueError(f"Inconsistent timezone representations for {ts_role}; no normalization applied")
                ts_lo, ts_hi = ts_parsed.min(), ts_parsed.max()
                if pd.isna(ts_record[f"earliest_{ts_role}"]) or ts_lo < ts_record[f"earliest_{ts_role}"]:
                    ts_record[f"earliest_{ts_role}"] = ts_lo
                if pd.isna(ts_record[f"latest_{ts_role}"]) or ts_hi > ts_record[f"latest_{ts_role}"]:
                    ts_record[f"latest_{ts_role}"] = ts_hi
                ts_calendar = ts_parsed if ts_tz is None else ts_parsed.dt.tz_localize(None)
                ts_record[f"{ts_role}_before_month"] += int((ts_calendar < ts_month_start).sum())
                ts_record[f"{ts_role}_after_month"] += int((ts_calendar >= ts_next_month).sum())
                if ts_role == "pickup":
                    ts_counts = ts_calendar.dt.normalize().value_counts(dropna=True)
                    ts_daily_counts.update({day: int(count) for day, count in ts_counts.items()})
                del ts_parsed, ts_calendar
            del ts_chunk
    for ts_role in ["pickup", "dropoff"]:
        ts_record[f"{ts_role}_timezone"] = ", ".join(sorted(ts_file_zones[ts_role])) or "unknown (no valid timestamps)"
    ts_records.append(ts_record)
    print(f"Finished {ts_path.name}: {ts_record['rows']:,} rows; invalid pickup={ts_record['invalid_pickup']:,}, invalid dropoff={ts_record['invalid_dropoff']:,}", flush=True)

ts_file_summary = pd.DataFrame(ts_records)
print("Per-file timestamp validation (all rows and columns):")
print(ts_file_summary.to_string(index=False))

Finished Urban_Flow_Analytics_Taxi_Dataset_2025-04.csv: 3,970,553 rows; invalid pickup=0, invalid dropoff=0
Finished Urban_Flow_Analytics_Taxi_Dataset_2025-05.csv: 4,591,845 rows; invalid pickup=0, invalid dropoff=0
Finished Urban_Flow_Analytics_Taxi_Dataset_2025-06.csv: 4,322,960 rows; invalid pickup=0, invalid dropoff=0
Finished Urban_Flow_Analytics_Taxi_Dataset_2025-07.csv: 3,898,963 rows; invalid pickup=0, invalid dropoff=0
Finished Urban_Flow_Analytics_Taxi_Dataset_2025-08.csv: 3,574,091 rows; invalid pickup=0, invalid dropoff=0
Finished Urban_Flow_Analytics_Taxi_Dataset_2025-09.csv: 4,251,015 rows; invalid pickup=0, invalid dropoff=0
Finished Urban_Flow_Analytics_Taxi_Dataset_2025-10.csv: 4,428,699 rows; invalid pickup=0, invalid dropoff=0
Finished Urban_Flow_Analytics_Taxi_Dataset_2025-11.csv: 4,181,444 rows; invalid pickup=0, invalid dropoff=0
Finished Urban_Flow_Analytics_Taxi_Dataset_2025-12.csv: 4,305,006 rows; invalid pickup=0, invalid dropoff=0
Finished Urban_Flow_Analytics_Taxi_Dataset_2026-01.csv: 3,724,889 rows; invalid pickup=0, invalid dropoff=0
Finished Urban_Flow_Analytics_Taxi_Dataset_2026-02.csv: 3,399,866 rows; invalid pickup=0, invalid dropoff=0
Finished Urban_Flow_Analytics_Taxi_Dataset_2026-03.csv: 3,952,451 rows; invalid pickup=0, invalid dropoff=0
Per-file timestamp validation (all rows and columns):
                                  source_file expected_month    rows  invalid_pickup     earliest_pickup       latest_pickup  pickup_before_month  pickup_after_month  invalid_dropoff    earliest_dropoff      latest_dropoff  dropoff_before_month  dropoff_after_month pickup_timezone dropoff_timezone
Urban_Flow_Analytics_Taxi_Dataset_2025-04.csv        2025-04 3970553               0 2025-03-31 23:45:01 2025-05-01 00:48:13                    4                   3                0 2025-03-31 23:54:54 2025-05-01 21:42:14                     1                 1102  timezone-naive   timezone-naive
Urban_Flow_Analytics_Taxi_Dataset_2025-05.csv        2025-05 4591845               0 2009-01-01 00:20:39 2025-06-01 00:04:31                   21                   3                0 2009-01-01 00:20:49 2025-06-04 11:17:10                     9                 2930  timezone-naive   timezone-naive
Urban_Flow_Analytics_Taxi_Dataset_2025-06.csv        2025-06 4322960               0 2025-05-31 22:34:26 2025-06-30 23:59:59                   20                   0                0 2025-05-31 22:43:36 2025-07-01 22:36:42                     7                  745  timezone-naive   timezone-naive
Urban_Flow_Analytics_Taxi_Dataset_2025-07.csv        2025-07 3898963               0 2009-01-01 08:52:26 2025-07-31 23:59:59                    7                   0                0 2009-01-01 10:00:26 2025-08-03 17:03:02                     3                 1214  timezone-naive   timezone-naive
Urban_Flow_Analytics_Taxi_Dataset_2025-08.csv        2025-08 3574091               0 2009-01-01 12:52:15 2025-09-01 00:00:29                   16                   1                0 2009-01-01 13:12:15 2025-09-02 08:17:29                     2                 1491  timezone-naive   timezone-naive
Urban_Flow_Analytics_Taxi_Dataset_2025-09.csv        2025-09 4251015               0 2025-08-31 23:45:38 2025-10-01 00:00:11                    6                   1                0 2025-08-31 23:46:43 2025-10-03 14:49:31                     1                  985  timezone-naive   timezone-naive
Urban_Flow_Analytics_Taxi_Dataset_2025-10.csv        2025-10 4428699               0 2025-09-30 22:54:51 2025-11-01 00:32:12                   10                   3                0 2025-09-30 23:04:41 2025-11-03 09:38:20                     2                 3987  timezone-naive   timezone-naive
Urban_Flow_Analytics_Taxi_Dataset_2025-11.csv        2025-11 4181444               0 2008-12-31 23:04:21 2025-11-30 23:59:59                   24                   0                0 2008-12-31 23:32:25 2025-12-01 21:41:00                     6                  803  timezone-naive   timezone-naive
Urban_Flow_Analytics_Taxi_Dataset_2025-12.csv        2025-12 4305006               0 2025-11-30 20:48:56 2025-12-31 23:59:59                    9                   0                0 2025-11-30 20:57:48 2026-01-05 13:00:34                     4                  774  timezone-naive   timezone-naive
Urban_Flow_Analytics_Taxi_Dataset_2026-01.csv        2026-01 3724889               0 2025-12-31 23:57:29 2026-02-01 00:45:01                    6                   1                0 2025-12-31 23:57:32 2026-02-01 23:35:31                     2                 2282  timezone-naive   timezone-naive
Urban_Flow_Analytics_Taxi_Dataset_2026-02.csv        2026-02 3399866               0 2026-01-31 23:31:23 2026-03-01 00:51:48                   12                   4                0 2026-01-31 23:36:52 2026-03-01 23:11:29                     2                 2336  timezone-naive   timezone-naive
Urban_Flow_Analytics_Taxi_Dataset_2026-03.csv        2026-03 3952451               0 2008-12-31 23:03:20 2026-04-01 00:06:25                   17                   2                0 2009-01-01 00:07:36 2026-04-02 16:03:47                     5                  845  timezone-naive   timezone-naive

### Trips per pickup date across all 12 files

Sum daily pickup counts across chunks and source files. Each successfully parsed pickup contributes once, including dates outside the filename's month; no anomaly filtering is applied. Invalid pickups cannot be assigned a date and are reported separately. The table contains every observed pickup date (no artificial zero-count dates). Unique-date count is the number of rows in this aggregate table. This table is an audit summary only; no date feature is added to the taxi data.

In [9]:
ts_trips_per_day = pd.DataFrame(sorted(ts_daily_counts.items()), columns=["pickup_date", "trip_count"])
print("Number of unique valid pickup dates:", len(ts_trips_per_day))
print("Trips per day across all source files:")
print(ts_trips_per_day.to_string(index=False))
print("Rows with invalid pickup timestamp (unassigned to a day):", int(ts_file_summary["invalid_pickup"].sum()))
assert int(ts_trips_per_day["trip_count"].sum()) + int(ts_file_summary["invalid_pickup"].sum()) == int(ts_file_summary["rows"].sum())
print("PASS: daily counts plus invalid pickups equal total source rows.")

Number of unique valid pickup dates: 369
Trips per day across all source files:
pickup_date  trip_count
 2008-12-31           2
 2009-01-01           6
 2025-03-31           4
 2025-04-01      128955
 2025-04-02      137393
 2025-04-03      138411
 2025-04-04      135084
 2025-04-05      153237
 2025-04-06      122921
 2025-04-07      115829
 2025-04-08      131574
 2025-04-09      137646
 2025-04-10      147648
 2025-04-11      154758
 2025-04-12      149391
 2025-04-13      109780
 2025-04-14       99795
 2025-04-15      122082
 2025-04-16      133969
 2025-04-17      135522
 2025-04-18      125581
 2025-04-19      134049
 2025-04-20      115504
 2025-04-21      107881
 2025-04-22      124843
 2025-04-23      135843
 2025-04-24      148387
 2025-04-25      147589
 2025-04-26      158506
 2025-04-27      141509
 2025-04-28      110105
 2025-04-29      126466
 2025-04-30      140308
 2025-05-01      157143
 2025-05-02      147086
 2025-05-03      164004
 2025-05-04      142682
 2025-05-05      137188
 2025-05-06      144921
 2025-05-07      149451
 2025-05-08      165824
 2025-05-09      163691
 2025-05-10      159387
 2025-05-11      147535
 2025-05-12      128681
 2025-05-13      151498
 2025-05-14      162954
 2025-05-15      168804
 2025-05-16      163632
 2025-05-17      179126
 2025-05-18      143771
 2025-05-19      135579
 2025-05-20      151301
 2025-05-21      164793
 2025-05-22      162940
 2025-05-23      135539
 2025-05-24      120501
 2025-05-25      113909
 2025-05-26       98714
 2025-05-27      124926
 2025-05-28      156454
 2025-05-29      149182
 2025-05-30      147192
 2025-05-31      153436
 2025-06-01      131827
 2025-06-02      114839
 2025-06-03      140826
 2025-06-04      158588
 2025-06-05      177340
 2025-06-06      163616
 2025-06-07      163816
 2025-06-08      139865
 2025-06-09      128597
 2025-06-10      141039
 2025-06-11      151921
 2025-06-12      167192
 2025-06-13      146778
 2025-06-14      146409
 2025-06-15      125074
 2025-06-16      119913
 2025-06-17      136744
 2025-06-18      157383
 2025-06-19      143836
 2025-06-20      140275
 2025-06-21      157148
 2025-06-22      135715
 2025-06-23      141713
 2025-06-24      157733
 2025-06-25      158320
 2025-06-26      152851
 2025-06-27      138402
 2025-06-28      142771
 2025-06-29      129912
 2025-06-30      112506
 2025-07-01      131478
 2025-07-02      112327
 2025-07-03      105435
 2025-07-04       88185
 2025-07-05       94764
 2025-07-06       96065
 2025-07-07      102807
 2025-07-08      131924
 2025-07-09      136134
 2025-07-10      129180
 2025-07-11      124211
 2025-07-12      136207
 2025-07-13      118992
 2025-07-14      136073
 2025-07-15      133444
 2025-07-16      144325
 2025-07-17      147848
 2025-07-18      128409
 2025-07-19      136926
 2025-07-20      123945
 2025-07-21      111317
 2025-07-22      123086
 2025-07-23      130406
 2025-07-24      134564
 2025-07-25      137005
 2025-07-26      140599
 2025-07-27      118777
 2025-07-28      120972
 2025-07-29      139067
 2025-07-30      142973
 2025-07-31      141526
 2025-08-01      123253
 2025-08-02      128651
 2025-08-03      110831
 2025-08-04      105176
 2025-08-05      117583
 2025-08-06      126842
 2025-08-07      121674
 2025-08-08      115538
 2025-08-09      114880
 2025-08-10      102769
 2025-08-11       99484
 2025-08-12      114599
 2025-08-13      134000
 2025-08-14      123193
 2025-08-15      118200
 2025-08-16      121365
 2025-08-17      115203
 2025-08-18       94785
 2025-08-19      107047
 2025-08-20      132182
 2025-08-21      114532
 2025-08-22      113785
 2025-08-23      126686
 2025-08-24      112316
 2025-08-25       99132
 2025-08-26      107701
 2025-08-27      113712
 2025-08-28      116732
 2025-08-29      113683
 2025-08-30      117063
 2025-08-31      111483
 2025-09-01       98007
 2025-09-02      118917
 2025-09-03      131860
 2025-09-04      150893
 2025-09-05      147058
 2025-09-06      148005
 2025-09-07      128728
 2025-09-08      124409
 2025-09-09      140841
 2025-09-10      152786
 2025-09-11      155338
 2025-09-12      161096
 2025-09-13      166369
 2025-09-14      145484
 2025-09-15      129352
 2025-09-16      143858
 2025-09-17      149841
 2025-09-18      161661
 2025-09-19      155135
 2025-09-20      157514
 2025-09-21      137531
 2025-09-22      119526
 2025-09-23      116445
 2025-09-24      135382
 2025-09-25      152897
 2025-09-26      155360
 2025-09-27      163820
 2025-09-28      138200
 2025-09-29      124242
 2025-09-30      140464
 2025-10-01      135029
 2025-10-02      131906
 2025-10-03      142690
 2025-10-04      147729
 2025-10-05      126963
 2025-10-06      120579
 2025-10-07      134704
 2025-10-08      149074
 2025-10-09      162293
 2025-10-10      156862
 2025-10-11      154335
 2025-10-12      129982
 2025-10-13      112005
 2025-10-14      139132
 2025-10-15      146153
 2025-10-16      161458
 2025-10-17      153567
 2025-10-18      152292
 2025-10-19      138473
 2025-10-20      116870
 2025-10-21      136833
 2025-10-22      146946
 2025-10-23      159975
 2025-10-24      153910
 2025-10-25      156536
 2025-10-26      126484
 2025-10-27      122604
 2025-10-28      135969
 2025-10-29      144370
 2025-10-30      163577
 2025-10-31      169408
 2025-11-01      183035
 2025-11-02      152130
 2025-11-03      129816
 2025-11-04      131512
 2025-11-05      142587
 2025-11-06      158170
 2025-11-07      147795
 2025-11-08      153432
 2025-11-09      133197
 2025-11-10      131860
 2025-11-11      131252
 2025-11-12      142267
 2025-11-13      156277
 2025-11-14      154779
 2025-11-15      162604
 2025-11-16      136369
 2025-11-17      130552
 2025-11-18      143933
 2025-11-19      153531
 2025-11-20      160579
 2025-11-21      153946
 2025-11-22      154131
 2025-11-23      126561
 2025-11-24      120517
 2025-11-25      144794
 2025-11-26      122438
 2025-11-27       96815
 2025-11-28      100936
 2025-11-29      114334
 2025-11-30      111283
 2025-12-01      125341
 2025-12-02      146523
 2025-12-03      150529
 2025-12-04      171170
 2025-12-05      170278
 2025-12-06      168387
 2025-12-07      141064
 2025-12-08      142984
 2025-12-09      159436
 2025-12-10      165676
 2025-12-11      181547
 2025-12-12      182484
 2025-12-13      180534
 2025-12-14      159914
 2025-12-15      150723
 2025-12-16      158518
 2025-12-17      159874
 2025-12-18      166137
 2025-12-19      171960
 2025-12-20      156918
 2025-12-21      124368
 2025-12-22      114270
 2025-12-23      112450
 2025-12-24      100600
 2025-12-25       68111
 2025-12-26       83927
 2025-12-27       85759
 2025-12-28       91036
 2025-12-29       96991
 2025-12-30      105865
 2025-12-31      111629
 2026-01-01      114466
 2026-01-02      100054
 2026-01-03      108632
 2026-01-04       93622
 2026-01-05       96951
 2026-01-06      107485
 2026-01-07      113071
 2026-01-08      119516
 2026-01-09      124026
 2026-01-10      145411
 2026-01-11      116006
 2026-01-12      112970
 2026-01-13      123339
 2026-01-14      130024
 2026-01-15      141194
 2026-01-16      134510
 2026-01-17      128070
 2026-01-18      119164
 2026-01-19      100343
 2026-01-20      130352
 2026-01-21      130064
 2026-01-22      136180
 2026-01-23      143551
 2026-01-24      145194
 2026-01-25       44858
 2026-01-26       69172
 2026-01-27      122211
 2026-01-28      132513
 2026-01-29      143987
 2026-01-30      153101
 2026-01-31      144857
 2026-02-01      123132
 2026-02-02      113919
 2026-02-03      125167
 2026-02-04      131494
 2026-02-05      136461
 2026-02-06      135750
 2026-02-07      154672
 2026-02-08      130469
 2026-02-09      112524
 2026-02-10      118818
 2026-02-11      130001
 2026-02-12      143696
 2026-02-13      141907
 2026-02-14      133489
 2026-02-15      113601
 2026-02-16       86653
 2026-02-17      106028
 2026-02-18      121392
 2026-02-19      125845
 2026-02-20      129620
 2026-02-21      136152
 2026-02-22       85555
 2026-02-23       26039
 2026-02-24      104315
 2026-02-25      122987
 2026-02-26      133200
 2026-02-27      139118
 2026-02-28      137862
 2026-03-01      112185
 2026-03-02      113408
 2026-03-03      135124
 2026-03-04      126008
 2026-03-05      152515
 2026-03-06      134068
 2026-03-07      131974
 2026-03-08      114960
 2026-03-09      107953
 2026-03-10      129189
 2026-03-11      131998
 2026-03-12      161051
 2026-03-13      146830
 2026-03-14      143571
 2026-03-15      119504
 2026-03-16      115023
 2026-03-17      127830
 2026-03-18      144364
 2026-03-19      149180
 2026-03-20      141855
 2026-03-21      135560
 2026-03-22      116064
 2026-03-23      106383
 2026-03-24      119024
 2026-03-25      121768
 2026-03-26      128765
 2026-03-27      126695
 2026-03-28      134101
 2026-03-29      109562
 2026-03-30      101370
 2026-03-31      114554
 2026-04-01           2
Rows with invalid pickup timestamp (unassigned to a day): 0
PASS: daily counts plus invalid pickups equal total source rows.

### Overall timestamp summary and filename-month flags

Report the global extrema and invalid totals, then list each file with out-of-month timestamps. A timestamp can parse successfully and still have a suspicious date. All such rows remain included. These checks do not establish whether a trip duration, location, or other value is valid.

In [10]:
ts_overall = {
    "source_files": len(ts_files),
    "total_rows": int(ts_file_summary["rows"].sum()),
    "invalid_pickup": int(ts_file_summary["invalid_pickup"].sum()),
    "invalid_dropoff": int(ts_file_summary["invalid_dropoff"].sum()),
    "earliest_pickup": ts_file_summary["earliest_pickup"].min(),
    "latest_pickup": ts_file_summary["latest_pickup"].max(),
    "earliest_dropoff": ts_file_summary["earliest_dropoff"].min(),
    "latest_dropoff": ts_file_summary["latest_dropoff"].max(),
    "unique_pickup_dates": len(ts_trips_per_day),
}
for ts_key, ts_value in ts_overall.items():
    print(f"{ts_key}: {ts_value}")
print("Timezone status:", {role: sorted(kinds) for role, kinds in ts_timezone_kinds.items()})
ts_range_columns = ["pickup_before_month", "pickup_after_month", "dropoff_before_month", "dropoff_after_month"]
ts_range_flags = ts_file_summary.loc[ts_file_summary[ts_range_columns].sum(axis=1) > 0,
    ["source_file", "expected_month"] + ts_range_columns]
print("Files with valid timestamps outside the filename month:")
print(ts_range_flags.to_string(index=False) if len(ts_range_flags) else "None")
print("Totals outside filename month:")
print(ts_file_summary[ts_range_columns].sum().to_string())
assert ts_source_snapshot == {str(p): (p.stat().st_size, p.stat().st_mtime_ns) for p in ts_files}
print("PASS: source file sizes and modification times unchanged.")
print("STOP: Step 2 timestamp validation only; no rows changed or removed.")

source_files: 12
total_rows: 48601782
invalid_pickup: 0
invalid_dropoff: 0
earliest_pickup: 2008-12-31 23:03:20
latest_pickup: 2026-04-01 00:06:25
earliest_dropoff: 2008-12-31 23:32:25
latest_dropoff: 2026-04-02 16:03:47
unique_pickup_dates: 369
Timezone status: {'pickup': ['timezone-naive'], 'dropoff': ['timezone-naive']}
Files with valid timestamps outside the filename month:
                                  source_file expected_month  pickup_before_month  pickup_after_month  dropoff_before_month  dropoff_after_month
Urban_Flow_Analytics_Taxi_Dataset_2025-04.csv        2025-04                    4                   3                     1                 1102
Urban_Flow_Analytics_Taxi_Dataset_2025-05.csv        2025-05                   21                   3                     9                 2930
Urban_Flow_Analytics_Taxi_Dataset_2025-06.csv        2025-06                   20                   0                     7                  745
Urban_Flow_Analytics_Taxi_Dataset_2025-07.csv        2025-07                    7                   0                     3                 1214
Urban_Flow_Analytics_Taxi_Dataset_2025-08.csv        2025-08                   16                   1                     2                 1491
Urban_Flow_Analytics_Taxi_Dataset_2025-09.csv        2025-09                    6                   1                     1                  985
Urban_Flow_Analytics_Taxi_Dataset_2025-10.csv        2025-10                   10                   3                     2                 3987
Urban_Flow_Analytics_Taxi_Dataset_2025-11.csv        2025-11                   24                   0                     6                  803
Urban_Flow_Analytics_Taxi_Dataset_2025-12.csv        2025-12                    9                   0                     4                  774
Urban_Flow_Analytics_Taxi_Dataset_2026-01.csv        2026-01                    6                   1                     2                 2282
Urban_Flow_Analytics_Taxi_Dataset_2026-02.csv        2026-02                   12                   4                     2                 2336
Urban_Flow_Analytics_Taxi_Dataset_2026-03.csv        2026-03                   17                   2                     5                  845
Totals outside filename month:
pickup_before_month       152
pickup_after_month         18
dropoff_before_month       44
dropoff_after_month     19494
PASS: source file sizes and modification times unchanged.
STOP: Step 2 timestamp validation only; no rows changed or removed.

### Step 2 recorded findings

- **Coverage:** all 12 monthly taxi CSVs; **48,601,782 rows**, processed sequentially in chunks of at most 200,000 rows. Actual fields: `pickup_timestamp` and `dropoff_timestamp`.
- **Invalid pickup timestamps:** **0**. **Invalid dropoff timestamps:** **0**. Successful parsing does not establish that the recorded date is correct.
- **Pickup range:** **2008-12-31 23:03:20** through **2026-04-01 00:06:25**.
- **Dropoff range:** **2008-12-31 23:32:25** through **2026-04-02 16:03:47**.
- **Timezone status:** both columns are **timezone-naive** in every chunk/file. The source strings do not establish a timezone, and none was assigned.
- **Unique pickup dates:** **369**, including suspicious dates. The complete trips-per-day table above sums to **48,601,782**, matching the source row count.
- **Filename-month mismatches:** **170 pickups** (152 before, 18 after) and **19,538 dropoffs** (44 before, 19,494 after). These are separate field counts, not a count of distinct affected trips. All source rows remain included.

All filenames below have the prefix `Urban_Flow_Analytics_Taxi_Dataset_` and suffix `.csv`. Full filenames and exact per-file minima/maxima are printed above.

| File month | Pickups outside filename month | Dropoffs outside filename month | Date-range observation |
|---|---:|---:|---|
| 2025-04 | 7 | 1,103 | March 31 through May 1 |
| 2025-05 | 24 | 2,939 | Earliest pickup/dropoff in January 2009; dropoffs through June 4 |
| 2025-06 | 20 | 752 | Pickups begin May 31; dropoffs through July 1 |
| 2025-07 | 7 | 1,217 | Earliest pickup/dropoff in January 2009; dropoffs through August 3 |
| 2025-08 | 17 | 1,493 | Earliest pickup/dropoff in January 2009; dropoffs through September 2 |
| 2025-09 | 7 | 986 | Pickups begin August 31; dropoffs through October 3 |
| 2025-10 | 13 | 3,989 | Pickups begin September 30; dropoffs through November 3 |
| 2025-11 | 24 | 809 | Earliest pickup/dropoff in December 2008; dropoffs through December 1 |
| 2025-12 | 9 | 778 | Pickups begin November 30; dropoffs through January 5, 2026 |
| 2026-01 | 7 | 2,284 | Pickups begin December 31; dropoffs through February 1 |
| 2026-02 | 16 | 2,338 | Pickups begin January 31; dropoffs through March 1 |
| 2026-03 | 19 | 850 | Earliest pickup in December 2008 and dropoff in January 2009; dropoffs through April 2 |

Crossing a month boundary can be legitimate, especially for dropoffs. Historical dates and multi-day month spillovers deserve investigation, but this audit does not calculate durations or impose anomaly rules. No rows were removed, corrected, or saved as cleaned data. Source sizes and modification times remained unchanged. **Stop after Step 2.**

## Step 3: Zone/reference audit and join preparation

This section audits the newly supplied reference and checks key coverage without performing a taxi-zone join. It runs independently of earlier in-memory variables and preserves the earlier audit outputs as historical observations. Source files and taxi rows are not modified. Only `origin_loc_id` and `dest_loc_id` are read from taxi CSVs, sequentially in chunks of 200,000 rows.

No rows are removed, imputed, or saved as cleaned/joined data. No timestamp processing, duration/speed calculations, anomaly filtering, feature engineering, splitting, or modelling is performed here.

In [11]:
from pathlib import Path
from collections import Counter
import pandas as pd

z_root = next(p for p in [Path.cwd(), *Path.cwd().parents] if (p / "data" / "raw").is_dir())
z_raw_dir = z_root / "data" / "raw"
z_sources = sorted(p for p in z_raw_dir.rglob("*") if p.is_file()
                   and "__MACOSX" not in p.relative_to(z_raw_dir).parts
                   and not any(part.startswith("._") for part in p.relative_to(z_raw_dir).parts)
                   and p.name != ".gitkeep")
z_candidates = [p for p in z_sources if p.suffix.lower() == ".csv" and "zone" in p.stem.lower()]
assert len(z_candidates) == 1, f"Expected one zone CSV; review candidates: {z_candidates}"
z_path = z_candidates[0]
z_taxi_files = [p for p in z_sources if p.suffix.lower() == ".csv" and p.name.startswith("Urban_Flow_Analytics_Taxi_Dataset_")]
assert len(z_taxi_files) == 12, f"Expected 12 taxi CSVs; found {len(z_taxi_files)}"
z_snapshot = {str(p): (p.stat().st_size, p.stat().st_mtime_ns) for p in [z_path, *z_taxi_files]}
z_reference = pd.read_csv(z_path, parse_dates=False)
print("Exact reference filename:", z_path.name)
print("Source path:", z_path.relative_to(z_root))
print("Shape:", z_reference.shape)
print("All columns:", z_reference.columns.tolist())
print("Data types:")
print(z_reference.dtypes.to_string())
print("First 10 rows:")
print(z_reference.head(10).to_string(index=False))
print("Missing-value counts (standard pandas CSV missing markers):")
print(z_reference.isna().sum().to_string())
print("Duplicate rows after the first occurrence:", int(z_reference.duplicated().sum()))

Exact reference filename: Urban_Flow_Analytics_Zone_Dataset (1).csv
Source path: data\raw\Urban_Flow_Analytics_Zone_Dataset (1).csv
Shape: (265, 4)
All columns: ['loc_id', 'borough_name', 'zone_name', 'service_zone']
Data types:
loc_id          int64
borough_name      str
zone_name         str
service_zone      str
First 10 rows:
 loc_id  borough_name               zone_name service_zone
      1           EWR          Newark Airport          EWR
      2        Queens             Jamaica Bay    Boro Zone
      3         Bronx Allerton/Pelham Gardens    Boro Zone
      4     Manhattan           Alphabet City  Yellow Zone
      5 Staten Island           Arden Heights    Boro Zone
      6 Staten Island Arrochar/Fort Wadsworth    Boro Zone
      7        Queens                 Astoria    Boro Zone
      8        Queens            Astoria Park    Boro Zone
      9        Queens              Auburndale    Boro Zone
     10        Queens            Baisley Park    Boro Zone
Missing-value counts (standard pandas CSV missing markers):
loc_id          0
borough_name    1
zone_name       1
service_zone    2
Duplicate rows after the first occurrence: 0

### Reference key and readable fields

The actual reference column `loc_id` is the candidate key for the actual taxi columns `origin_loc_id` and `dest_loc_id`. The readable fields present are `borough_name`, `zone_name`, and `service_zone`; no additional field meanings or code definitions are inferred. Compare observed dtypes and exact ID membership without casting, normalizing, or rewriting source values.

Check key nulls, uniqueness, duplicate IDs, and range before any future join. Duplicate reference keys would cause row multiplication in a join and require review. For labels that pandas reads as missing, show the corresponding literal CSV strings separately, with missing-marker conversion disabled; this is an inspection view, not an imputation or edit.

In [12]:
z_key = "loc_id"
z_readable = ["borough_name", "zone_name", "service_zone"]
assert all(column in z_reference.columns for column in [z_key, *z_readable])
for z_taxi_path in z_taxi_files:
    z_header = pd.read_csv(z_taxi_path, nrows=0).columns
    assert all(column in z_header for column in ["origin_loc_id", "dest_loc_id"]), z_taxi_path.name
z_ids = set(z_reference[z_key].dropna())
z_duplicate_key_mask = z_reference[z_key].notna() & z_reference[z_key].duplicated(keep=False)
z_duplicate_ids = z_reference.loc[z_duplicate_key_mask, z_key].unique().tolist()
print("Candidate mappings: origin_loc_id -> loc_id; dest_loc_id -> loc_id")
print("Readable location columns:", z_readable)
print("Reference key dtype:", z_reference[z_key].dtype)
print("Unique non-missing zone IDs:", z_reference[z_key].nunique(dropna=True))
print("Missing zone IDs:", int(z_reference[z_key].isna().sum()))
print("All zone IDs unique:", z_reference[z_key].is_unique)
print("Minimum zone ID:", z_reference[z_key].min())
print("Maximum zone ID:", z_reference[z_key].max())
print("Duplicate zone IDs:", z_duplicate_ids)
print("Rows involved in duplicate IDs:", int(z_duplicate_key_mask.sum()))
if z_duplicate_ids:
    print(z_reference.loc[z_duplicate_key_mask].to_string(index=False))
z_incomplete_labels = z_reference[z_readable].isna().any(axis=1)
print("Reference rows with missing readable fields:")
print(z_reference.loc[z_incomplete_labels].to_string(index=False))
z_literal_reference = pd.read_csv(z_path, dtype="string", keep_default_na=False, parse_dates=False)
print("Literal CSV text for the same rows (N/A preserved as text):")
print(z_literal_reference.loc[z_incomplete_labels].to_string(index=False))

Candidate mappings: origin_loc_id -> loc_id; dest_loc_id -> loc_id
Readable location columns: ['borough_name', 'zone_name', 'service_zone']
Reference key dtype: int64
Unique non-missing zone IDs: 265
Missing zone IDs: 0
All zone IDs unique: True
Minimum zone ID: 1
Maximum zone ID: 265
Duplicate zone IDs: []
Rows involved in duplicate IDs: 0
Reference rows with missing readable fields:
 loc_id borough_name      zone_name service_zone
    264      Unknown            NaN          NaN
    265          NaN Outside of NYC          NaN
Literal CSV text for the same rows (N/A preserved as text):
loc_id borough_name      zone_name service_zone
   264      Unknown            N/A          N/A
   265          N/A Outside of NYC          N/A

### Taxi-to-reference coverage across all monthly files

Count distinct non-missing origin and destination IDs across all chunks, and count rows whose ID is absent from the reference. Missing taxi IDs, if present, count as unmatched and are also reported separately. All row percentages use the full source row count as denominator, not the number of distinct IDs. Invalid or unmatched values are only counted; no taxi rows are changed or excluded.

A matched ID does not guarantee a complete readable label. Report usage of reference rows with missing readable fields separately. This distinguishes absent keys from existing keys with incomplete labels, without joining any taxi rows.

In [13]:
z_origin_counts = Counter()
z_destination_counts = Counter()
z_origin_unmatched_counts = Counter()
z_destination_unmatched_counts = Counter()
z_file_records = []
z_taxi_dtypes = {"origin_loc_id": set(), "dest_loc_id": set()}
for z_taxi_path in z_taxi_files:
    z_record = {"source_file": z_taxi_path.name, "rows": 0,
                "unmatched_origin_rows": 0, "unmatched_destination_rows": 0,
                "missing_origin_rows": 0, "missing_destination_rows": 0}
    with pd.read_csv(z_taxi_path, usecols=["origin_loc_id", "dest_loc_id"],
                     parse_dates=False, chunksize=200_000) as z_reader:
        for z_chunk in z_reader:
            z_record["rows"] += len(z_chunk)
            for z_column, z_role, z_counts, z_unmatched_counts in [
                ("origin_loc_id", "origin", z_origin_counts, z_origin_unmatched_counts),
                ("dest_loc_id", "destination", z_destination_counts, z_destination_unmatched_counts),
            ]:
                z_values = z_chunk[z_column]
                z_taxi_dtypes[z_column].add(str(z_values.dtype))
                z_counts.update({key: int(value) for key, value in z_values.value_counts(dropna=True).items()})
                z_unmatched = ~z_values.isin(z_ids)
                z_record[f"unmatched_{z_role}_rows"] += int(z_unmatched.sum())
                z_record[f"missing_{z_role}_rows"] += int(z_values.isna().sum())
                z_unmatched_counts.update({key: int(value) for key, value in z_values[z_unmatched].value_counts(dropna=True).items()})
            del z_chunk, z_values, z_unmatched
    z_record["unmatched_origin_percent"] = 100 * z_record["unmatched_origin_rows"] / z_record["rows"] if z_record["rows"] else float("nan")
    z_record["unmatched_destination_percent"] = 100 * z_record["unmatched_destination_rows"] / z_record["rows"] if z_record["rows"] else float("nan")
    z_file_records.append(z_record)
    print(f"Finished {z_taxi_path.name}: {z_record['rows']:,} rows; unmatched origin={z_record['unmatched_origin_rows']:,}, unmatched destination={z_record['unmatched_destination_rows']:,}", flush=True)
z_file_coverage = pd.DataFrame(z_file_records)
print("Observed taxi ID dtypes:", {column: sorted(types) for column, types in z_taxi_dtypes.items()})
print("Per-file key coverage:")
print(z_file_coverage.to_string(index=False))

Finished Urban_Flow_Analytics_Taxi_Dataset_2025-04.csv: 3,970,553 rows; unmatched origin=0, unmatched destination=0
Finished Urban_Flow_Analytics_Taxi_Dataset_2025-05.csv: 4,591,845 rows; unmatched origin=0, unmatched destination=0
Finished Urban_Flow_Analytics_Taxi_Dataset_2025-06.csv: 4,322,960 rows; unmatched origin=0, unmatched destination=0
Finished Urban_Flow_Analytics_Taxi_Dataset_2025-07.csv: 3,898,963 rows; unmatched origin=0, unmatched destination=0
Finished Urban_Flow_Analytics_Taxi_Dataset_2025-08.csv: 3,574,091 rows; unmatched origin=0, unmatched destination=0
Finished Urban_Flow_Analytics_Taxi_Dataset_2025-09.csv: 4,251,015 rows; unmatched origin=0, unmatched destination=0
Finished Urban_Flow_Analytics_Taxi_Dataset_2025-10.csv: 4,428,699 rows; unmatched origin=0, unmatched destination=0
Finished Urban_Flow_Analytics_Taxi_Dataset_2025-11.csv: 4,181,444 rows; unmatched origin=0, unmatched destination=0
Finished Urban_Flow_Analytics_Taxi_Dataset_2025-12.csv: 4,305,006 rows; unmatched origin=0, unmatched destination=0
Finished Urban_Flow_Analytics_Taxi_Dataset_2026-01.csv: 3,724,889 rows; unmatched origin=0, unmatched destination=0
Finished Urban_Flow_Analytics_Taxi_Dataset_2026-02.csv: 3,399,866 rows; unmatched origin=0, unmatched destination=0
Finished Urban_Flow_Analytics_Taxi_Dataset_2026-03.csv: 3,952,451 rows; unmatched origin=0, unmatched destination=0
Observed taxi ID dtypes: {'origin_loc_id': ['int64'], 'dest_loc_id': ['int64']}
Per-file key coverage:
                                  source_file    rows  unmatched_origin_rows  unmatched_destination_rows  missing_origin_rows  missing_destination_rows  unmatched_origin_percent  unmatched_destination_percent
Urban_Flow_Analytics_Taxi_Dataset_2025-04.csv 3970553                      0                           0                    0                         0                       0.0                            0.0
Urban_Flow_Analytics_Taxi_Dataset_2025-05.csv 4591845                      0                           0                    0                         0                       0.0                            0.0
Urban_Flow_Analytics_Taxi_Dataset_2025-06.csv 4322960                      0                           0                    0                         0                       0.0                            0.0
Urban_Flow_Analytics_Taxi_Dataset_2025-07.csv 3898963                      0                           0                    0                         0                       0.0                            0.0
Urban_Flow_Analytics_Taxi_Dataset_2025-08.csv 3574091                      0                           0                    0                         0                       0.0                            0.0
Urban_Flow_Analytics_Taxi_Dataset_2025-09.csv 4251015                      0                           0                    0                         0                       0.0                            0.0
Urban_Flow_Analytics_Taxi_Dataset_2025-10.csv 4428699                      0                           0                    0                         0                       0.0                            0.0
Urban_Flow_Analytics_Taxi_Dataset_2025-11.csv 4181444                      0                           0                    0                         0                       0.0                            0.0
Urban_Flow_Analytics_Taxi_Dataset_2025-12.csv 4305006                      0                           0                    0                         0                       0.0                            0.0
Urban_Flow_Analytics_Taxi_Dataset_2026-01.csv 3724889                      0                           0                    0                         0                       0.0                            0.0
Urban_Flow_Analytics_Taxi_Dataset_2026-02.csv 3399866                      0                           0                    0                         0                       0.0                            0.0
Urban_Flow_Analytics_Taxi_Dataset_2026-03.csv 3952451                      0                           0                    0                         0                       0.0                            0.0

### Overall coverage and join readiness

Aggregate the counters, show every unmatched non-missing ID and its frequency, and distinguish key coverage from label completeness. Reference-only IDs are reported as observations, not defects. A future join should be a left join using the verified key with `validate="many_to_one"` to prevent unexpected row multiplication; no such join is executed in this step.

In [14]:
z_total_rows = int(z_file_coverage["rows"].sum())
print("Zone dataset shape:", z_reference.shape)
print("Zone ID column:", z_key)
print("Readable location columns:", z_readable)
print("Unique zone IDs:", len(z_ids))
print("Duplicate zone IDs:", z_duplicate_ids)
print("Total taxi rows checked:", z_total_rows)
print("Unique non-missing origin IDs:", len(z_origin_counts))
print("Unique non-missing destination IDs:", len(z_destination_counts))
for z_role, z_counts, z_unmatched_counts in [
    ("origin", z_origin_counts, z_origin_unmatched_counts),
    ("destination", z_destination_counts, z_destination_unmatched_counts),
]:
    z_missing_total = int(z_file_coverage[f"missing_{z_role}_rows"].sum())
    z_unmatched_total = int(z_file_coverage[f"unmatched_{z_role}_rows"].sum())
    print(f"Unmatched {z_role} IDs and row counts:", dict(z_unmatched_counts))
    print(f"Missing {z_role} IDs (rows):", z_missing_total)
    print(f"Unmatched {z_role} rows:", z_unmatched_total)
    print(f"Percentage of all taxi rows with unmatched {z_role} IDs: {100 * z_unmatched_total / z_total_rows:.6f}%")
    print(f"Reference IDs not observed as {z_role}:", sorted(z_ids - set(z_counts)))
    assert sum(z_counts.values()) + z_missing_total == z_total_rows
    assert sum(z_unmatched_counts.values()) + z_missing_total == z_unmatched_total
z_label_usage = z_reference.loc[z_incomplete_labels, [z_key, *z_readable]].copy()
z_label_usage["origin_rows"] = z_label_usage[z_key].map(z_origin_counts).fillna(0).astype("int64")
z_label_usage["destination_rows"] = z_label_usage[z_key].map(z_destination_counts).fillna(0).astype("int64")
z_label_usage["origin_percent"] = z_label_usage["origin_rows"] / z_total_rows * 100
z_label_usage["destination_percent"] = z_label_usage["destination_rows"] / z_total_rows * 100
print("Matched reference IDs with incomplete readable labels (aggregate report only):")
print(z_label_usage.to_string(index=False))
print("Key unique and non-missing:", z_reference[z_key].is_unique and z_reference[z_key].notna().all())
assert z_snapshot == {str(p): (p.stat().st_size, p.stat().st_mtime_ns) for p in [z_path, *z_taxi_files]}
print("PASS: ID counts reconcile to all taxi rows; source sizes and modification times unchanged.")
print("STOP: Step 3 audit and join coverage only. No taxi-zone join or source-data writes performed.")

Zone dataset shape: (265, 4)
Zone ID column: loc_id
Readable location columns: ['borough_name', 'zone_name', 'service_zone']
Unique zone IDs: 265
Duplicate zone IDs: []
Total taxi rows checked: 48601782
Unique non-missing origin IDs: 262
Unique non-missing destination IDs: 263
Unmatched origin IDs and row counts: {}
Missing origin IDs (rows): 0
Unmatched origin rows: 0
Percentage of all taxi rows with unmatched origin IDs: 0.000000%
Reference IDs not observed as origin: [103, 104, 110]
Unmatched destination IDs and row counts: {}
Missing destination IDs (rows): 0
Unmatched destination rows: 0
Percentage of all taxi rows with unmatched destination IDs: 0.000000%
Reference IDs not observed as destination: [103, 104]
Matched reference IDs with incomplete readable labels (aggregate report only):
 loc_id borough_name      zone_name service_zone  origin_rows  destination_rows  origin_percent  destination_percent
    264      Unknown            NaN          NaN        70293             89644        0.144630             0.184446
    265          NaN Outside of NYC          NaN        22560            227614        0.046418             0.468324
Key unique and non-missing: True
PASS: ID counts reconcile to all taxi rows; source sizes and modification times unchanged.
STOP: Step 3 audit and join coverage only. No taxi-zone join or source-data writes performed.

### Step 3 recorded findings

- **Exact reference file:** `Urban_Flow_Analytics_Zone_Dataset (1).csv`.
- **Shape:** **265 rows x 4 columns**. Columns are `loc_id`, `borough_name`, `zone_name`, and `service_zone`.
- **Join key:** `loc_id` for both taxi `origin_loc_id` and `dest_loc_id`. All three fields have observed `int64` dtype, and every taxi ID is present in the reference. No key coercion or join was performed.
- **Readable fields:** `borough_name`, `zone_name`, and `service_zone`, as named in the actual source file.
- **Reference integrity:** **265 unique IDs**, minimum **1**, maximum **265**; **0 missing IDs**, **0 duplicate IDs**, and **0 duplicate rows**. The key supports a future many-to-one join without reference-key row multiplication.
- **Taxi coverage:** all **12 files / 48,601,782 rows** checked in chunks. There are **262 unique origin IDs** and **263 unique destination IDs**, with no missing taxi IDs.
- **Unmatched origin IDs:** none; **0 rows (0%)**. **Unmatched destination IDs:** none; **0 rows (0%)**. Every monthly file has zero unmatched rows for both fields.
- **Reference IDs not observed:** origins: **103, 104, 110**; destinations: **103, 104**. Non-use alone is not a reference defect.

#### Reference issues requiring interpretation before later use

Standard pandas CSV loading reports **1 missing `borough_name`**, **1 missing `zone_name`**, and **2 missing `service_zone` values**. The literal file contains `N/A` at those positions; no missing values were filled or modified.

| loc_id | Actual reference labels | Origin rows (% of all taxi rows) | Destination rows (% of all taxi rows) |
|---|---|---:|---:|
| 264 | `borough_name=Unknown`; `zone_name=N/A`; `service_zone=N/A` | 70,293 (0.144630%) | 89,644 (0.184446%) |
| 265 | `borough_name=N/A`; `zone_name=Outside of NYC`; `service_zone=N/A` | 22,560 (0.046418%) | 227,614 (0.468324%) |

These IDs match the reference but do not supply complete readable location labels. Their exact meanings or treatment should not be inferred beyond the source labels. Origin and destination counts are separate and must not be added as a count of distinct affected trips.

Earlier Step 1 statements that the reference was missing describe the inputs available at that earlier audit; the reference is now supplied and audited here. Counts reconcile to all source rows, and source sizes and modification times remain unchanged. **Stop after Step 3: no taxi-zone join, cleaning, row removal, imputation, or later processing was performed.**

## Step 4: Audit-calculation fields

Create temporary audit fields in 200,000-row chunks, without concatenating the monthly data. Steps 1-3 remain unchanged. Only the five required source columns are loaded; every source row contributes to this step. No fare, distance, rider-count, duration, speed, or timestamp filtering is applied, and no values are imputed.

| Field | Calculation | Use in a later audit |
|---|---|---|
| `trip_duration_minutes` | Dropoff minus pickup, in minutes | Inspect recorded elapsed time |
| `speed_mph` | `distance_miles / (trip_duration_minutes / 60)`, only for positive duration | Inspect implied speed; undefined for non-positive duration |
| `pickup_date` | Pickup calendar date | Inspect date coverage |
| `pickup_hour` | Pickup hour, 0-23 | Inspect time-of-day patterns |
| `day_of_week` | Readable pickup weekday name | Inspect weekday patterns |
| `month` | Pickup calendar month number, 1-12 | Inspect month patterns; this is not a year-month key |
| `weekend` | Saturday or Sunday | Compare weekday/weekend coverage |
| `route_id` | Original origin ID + `-` + original destination ID | Reproducible directional route label |

Timestamp parsing uses `errors="coerce"` and `format="mixed"`, as in Step 2, without assigning a timezone. Invalid timestamps produce missing derived calendar/duration values. Missing inputs remain missing. These calculations prepare an audit view only; no anomaly counts, thresholds, cleaning rules, or downstream processing are introduced.

In [ ]:
from pathlib import Path
from collections import Counter
import tempfile
import math
import numpy as np
import pandas as pd

a_root = next(p for p in [Path.cwd(), *Path.cwd().parents] if (p / "data" / "raw").is_dir())
a_files = sorted(p for p in (a_root / "data" / "raw").rglob("Urban_Flow_Analytics_Taxi_Dataset_*.csv")
                 if p.is_file() and "__MACOSX" not in p.relative_to(a_root).parts
                 and not any(part.startswith("._") for part in p.relative_to(a_root).parts))
assert len(a_files) == 12, f"Expected 12 taxi files; found {len(a_files)}"
# Names verified from the actual CSV headers, not inferred alternatives.
a_columns = {"pickup": "pickup_timestamp", "dropoff": "dropoff_timestamp", "distance": "distance_miles",
             "origin": "origin_loc_id", "destination": "dest_loc_id"}
for a_path in a_files:
    a_header = pd.read_csv(a_path, nrows=0).columns.tolist()
    a_missing = set(a_columns.values()) - set(a_header)
    if a_missing:
        raise ValueError(f"Essential columns missing in {a_path.name}: {sorted(a_missing)}")
a_snapshot = {str(p): (p.stat().st_size, p.stat().st_mtime_ns) for p in a_files}
print("Verified source columns:", a_columns)
print("Files:")
for a_path in a_files:
    print(a_path.name)

def a_derive(chunk):
    if not pd.api.types.is_numeric_dtype(chunk[a_columns["distance"]]):
        raise TypeError("distance_miles is not numeric; stop without coercing source values")
    pickup = pd.to_datetime(chunk[a_columns["pickup"]], errors="coerce", format="mixed", utc=False)
    dropoff = pd.to_datetime(chunk[a_columns["dropoff"]], errors="coerce", format="mixed", utc=False)
    if not pd.api.types.is_datetime64_any_dtype(pickup.dtype) or not pd.api.types.is_datetime64_any_dtype(dropoff.dtype):
        raise TypeError("Unexpected timestamp dtype; stop without timezone normalization")
    if pickup.dt.tz is not None or dropoff.dt.tz is not None:
        raise TypeError("Timezone-aware timestamps differ from Step 2; review before calculating")
    enriched = chunk.copy()
    enriched["trip_duration_minutes"] = (dropoff - pickup).dt.total_seconds() / 60
    enriched["speed_mph"] = np.nan
    positive = enriched["trip_duration_minutes"] > 0
    # Division is executed only on positive-duration records.
    enriched.loc[positive, "speed_mph"] = enriched.loc[positive, a_columns["distance"]] / (enriched.loc[positive, "trip_duration_minutes"] / 60)
    enriched["pickup_date"] = pickup.dt.date
    enriched["pickup_hour"] = pickup.dt.hour.astype("Int64")
    enriched["day_of_week"] = pickup.dt.day_name()
    enriched["month"] = pickup.dt.month.astype("Int64")
    enriched["weekend"] = pickup.dt.dayofweek.astype("Int64") >= 5
    enriched["route_id"] = chunk[a_columns["origin"]].astype("string") + "-" + chunk[a_columns["destination"]].astype("string")
    assert enriched.loc[~positive, "speed_mph"].isna().all()
    assert len(enriched) == len(chunk)
    return enriched

Verified source columns: {'pickup': 'pickup_timestamp', 'dropoff': 'dropoff_timestamp', 'distance': 'distance_miles', 'origin': 'origin_loc_id', 'destination': 'dest_loc_id'}
Files:
Urban_Flow_Analytics_Taxi_Dataset_2025-04.csv
Urban_Flow_Analytics_Taxi_Dataset_2025-05.csv
Urban_Flow_Analytics_Taxi_Dataset_2025-06.csv
Urban_Flow_Analytics_Taxi_Dataset_2025-07.csv
Urban_Flow_Analytics_Taxi_Dataset_2025-08.csv
Urban_Flow_Analytics_Taxi_Dataset_2025-09.csv
Urban_Flow_Analytics_Taxi_Dataset_2025-10.csv
Urban_Flow_Analytics_Taxi_Dataset_2025-11.csv
Urban_Flow_Analytics_Taxi_Dataset_2025-12.csv
Urban_Flow_Analytics_Taxi_Dataset_2026-01.csv
Urban_Flow_Analytics_Taxi_Dataset_2026-02.csv
Urban_Flow_Analytics_Taxi_Dataset_2026-03.csv

### Incremental descriptive statistics and exact medians

Accumulate counts, sums, minima, maxima, weekday counts, and weekend counts across chunks. Duration statistics include all defined durations, including zero and negative values. Speed statistics include all defined speeds on positive-duration rows, including zero/negative distances and extreme results; no plausibility threshold is used.

For **exact** medians, append only the two numeric calculation vectors to temporary binary files, excluding undefined values only from their respective statistics. Partition each disk-backed vector in place, then remove the temporary files automatically. This requires approximately 0.8 GB of temporary disk space, stores no enriched taxi rows, and creates no persistent dataset or Parquet output. Only the current chunk, small counters, and ten sample rows are retained in the notebook process.

The ten validation examples are purposive, not a statistically representative sample: six file-start examples spread across the year, a zero-duration example if present, and rows attaining minimum duration, maximum duration, and maximum speed. These demonstrate calculation behavior without counting anomalies or removing records.

In [16]:
a_stats = {field: {"n": 0, "min": math.inf, "max": -math.inf, "chunk_sums": []}
           for field in ["trip_duration_minutes", "speed_mph"]}
a_weekdays = Counter()
a_weekends = Counter()
a_dtypes = {column: set() for column in a_columns.values()}
a_field_dtypes = {}
a_hour_min, a_hour_max = None, None
a_rows = 0
a_file_rows = []
a_samples = {}
a_sample_file_indices = {0, 2, 4, 6, 8, 11}
a_extrema = {"minimum duration": math.inf, "maximum duration": -math.inf, "maximum speed": -math.inf}

def a_sample_record(frame, index, filename, reason):
    row = frame.loc[index].copy()
    row["source_file"] = filename
    row["source_row_1based"] = int(index) + 1
    row["sample_reason"] = reason
    return row

def a_exact_median(path, n):
    if n == 0:
        return float("nan")
    vector = np.memmap(path, dtype="float64", mode="r+", shape=(n,))
    try:
        middle = n // 2
        if n % 2:
            vector.partition(middle)
            result = float(vector[middle])
        else:
            vector.partition((middle - 1, middle))
            result = float(vector[middle - 1]) / 2 + float(vector[middle]) / 2
        vector.flush()
        return result
    finally:
        vector._mmap.close()

with tempfile.TemporaryDirectory(prefix="urban_flow_step4_medians_") as a_tmp:
    a_temp_paths = {field: Path(a_tmp) / f"{field}.bin" for field in a_stats}
    a_handles = {field: path.open("wb") for field, path in a_temp_paths.items()}
    try:
        for a_file_index, a_path in enumerate(a_files):
            a_this_file_rows = 0
            with pd.read_csv(a_path, usecols=list(a_columns.values()), parse_dates=False, chunksize=200_000) as a_reader:
                for a_chunk in a_reader:
                    for column in a_columns.values():
                        a_dtypes[column].add(str(a_chunk[column].dtype))
                    a_enriched = a_derive(a_chunk)
                    for field in a_enriched.columns:
                        if field not in a_columns.values():
                            a_field_dtypes.setdefault(field, set()).add(str(a_enriched[field].dtype))
                    a_rows += len(a_enriched)
                    a_this_file_rows += len(a_enriched)
                    for field, stats in a_stats.items():
                        values = a_enriched[field].dropna().to_numpy(dtype="float64")
                        if len(values):
                            stats["n"] += len(values)
                            stats["min"] = min(stats["min"], float(values.min()))
                            stats["max"] = max(stats["max"], float(values.max()))
                            stats["chunk_sums"].append(float(values.sum()))
                            values.tofile(a_handles[field])
                        del values
                    valid_hours = a_enriched["pickup_hour"].dropna()
                    if len(valid_hours):
                        lo, hi = int(valid_hours.min()), int(valid_hours.max())
                        a_hour_min = lo if a_hour_min is None else min(a_hour_min, lo)
                        a_hour_max = hi if a_hour_max is None else max(a_hour_max, hi)
                    a_weekdays.update({str(key): int(value) for key, value in a_enriched["day_of_week"].value_counts(dropna=False).items()})
                    a_weekends.update({"missing" if pd.isna(key) else "weekend" if bool(key) else "weekday": int(value)
                                       for key, value in a_enriched["weekend"].value_counts(dropna=False).items()})
                    sample_key = f"file {a_file_index}"
                    if a_file_index in a_sample_file_indices and sample_key not in a_samples:
                        a_samples[sample_key] = a_sample_record(a_enriched, a_enriched.index[0], a_path.name, "file-start example")
                    if "zero duration" not in a_samples:
                        zero = a_enriched["trip_duration_minutes"].eq(0)
                        if zero.any():
                            a_samples["zero duration"] = a_sample_record(a_enriched, zero[zero].index[0], a_path.name, "zero duration")
                    for reason, field, is_minimum in [("minimum duration", "trip_duration_minutes", True),
                                                       ("maximum duration", "trip_duration_minutes", False),
                                                       ("maximum speed", "speed_mph", False)]:
                        if a_enriched[field].notna().any():
                            index = a_enriched[field].idxmin() if is_minimum else a_enriched[field].idxmax()
                            value = a_enriched.at[index, field]
                            if (value < a_extrema[reason]) if is_minimum else (value > a_extrema[reason]):
                                a_extrema[reason] = value
                                a_samples[reason] = a_sample_record(a_enriched, index, a_path.name, reason)
                    if "fallback" not in a_samples and len(a_enriched) > 1:
                        a_samples["fallback"] = a_sample_record(a_enriched, a_enriched.index[1], a_path.name, "additional source example")
                    del a_enriched, a_chunk, valid_hours
            a_file_rows.append({"source_file": a_path.name, "rows": a_this_file_rows})
            print(f"Finished {a_path.name}: {a_this_file_rows:,} rows; audit fields calculated without row filtering", flush=True)
    finally:
        for handle in a_handles.values():
            handle.close()
    a_summary_records = []
    for field, stats in a_stats.items():
        print(f"Calculating exact disk-backed median: {field}", flush=True)
        a_summary_records.append({"field": field,
            "min": stats["min"] if stats["n"] else np.nan,
            "median": a_exact_median(a_temp_paths[field], stats["n"]),
            "mean": math.fsum(stats["chunk_sums"]) / stats["n"] if stats["n"] else np.nan,
            "max": stats["max"] if stats["n"] else np.nan})
a_summary = pd.DataFrame(a_summary_records).set_index("field")
assert not Path(a_tmp).exists()
print("PASS: temporary median files removed.")
print("Rows processed:", a_rows)
print(pd.DataFrame(a_file_rows).to_string(index=False))

Finished Urban_Flow_Analytics_Taxi_Dataset_2025-04.csv: 3,970,553 rows; audit fields calculated without row filtering
Finished Urban_Flow_Analytics_Taxi_Dataset_2025-05.csv: 4,591,845 rows; audit fields calculated without row filtering
Finished Urban_Flow_Analytics_Taxi_Dataset_2025-06.csv: 4,322,960 rows; audit fields calculated without row filtering
Finished Urban_Flow_Analytics_Taxi_Dataset_2025-07.csv: 3,898,963 rows; audit fields calculated without row filtering
Finished Urban_Flow_Analytics_Taxi_Dataset_2025-08.csv: 3,574,091 rows; audit fields calculated without row filtering
Finished Urban_Flow_Analytics_Taxi_Dataset_2025-09.csv: 4,251,015 rows; audit fields calculated without row filtering
Finished Urban_Flow_Analytics_Taxi_Dataset_2025-10.csv: 4,428,699 rows; audit fields calculated without row filtering
Finished Urban_Flow_Analytics_Taxi_Dataset_2025-11.csv: 4,181,444 rows; audit fields calculated without row filtering
Finished Urban_Flow_Analytics_Taxi_Dataset_2025-12.csv: 4,305,006 rows; audit fields calculated without row filtering
Finished Urban_Flow_Analytics_Taxi_Dataset_2026-01.csv: 3,724,889 rows; audit fields calculated without row filtering
Finished Urban_Flow_Analytics_Taxi_Dataset_2026-02.csv: 3,399,866 rows; audit fields calculated without row filtering
Finished Urban_Flow_Analytics_Taxi_Dataset_2026-03.csv: 3,952,451 rows; audit fields calculated without row filtering
Calculating exact disk-backed median: trip_duration_minutes
Calculating exact disk-backed median: speed_mph
PASS: temporary median files removed.
Rows processed: 48601782
                                  source_file    rows
Urban_Flow_Analytics_Taxi_Dataset_2025-04.csv 3970553
Urban_Flow_Analytics_Taxi_Dataset_2025-05.csv 4591845
Urban_Flow_Analytics_Taxi_Dataset_2025-06.csv 4322960
Urban_Flow_Analytics_Taxi_Dataset_2025-07.csv 3898963
Urban_Flow_Analytics_Taxi_Dataset_2025-08.csv 3574091
Urban_Flow_Analytics_Taxi_Dataset_2025-09.csv 4251015
Urban_Flow_Analytics_Taxi_Dataset_2025-10.csv 4428699
Urban_Flow_Analytics_Taxi_Dataset_2025-11.csv 4181444
Urban_Flow_Analytics_Taxi_Dataset_2025-12.csv 4305006
Urban_Flow_Analytics_Taxi_Dataset_2026-01.csv 3724889
Urban_Flow_Analytics_Taxi_Dataset_2026-02.csv 3399866
Urban_Flow_Analytics_Taxi_Dataset_2026-03.csv 3952451

### Ten-row calculation validation

Display original timestamps, distance, location IDs, all eight calculated fields, source filename, and source row number (one-based data row, excluding the header). Independently recompute each displayed result from the scalar source values and check it against the chunk calculations. Speed must remain missing when duration is zero, negative, or undefined. No sample row is used to prescribe a cleaning decision.

In [17]:
a_sample_keys = [f"file {index}" for index in sorted(a_sample_file_indices)]
a_sample_keys += ["zero duration" if "zero duration" in a_samples else "fallback", "minimum duration", "maximum duration", "maximum speed"]
a_sample = pd.DataFrame([a_samples[key] for key in a_sample_keys]).reset_index(drop=True)
assert len(a_sample) == 10
for _, row in a_sample.iterrows():
    pickup = pd.to_datetime(row[a_columns["pickup"]], errors="coerce", format="mixed")
    dropoff = pd.to_datetime(row[a_columns["dropoff"]], errors="coerce", format="mixed")
    expected_duration = (dropoff - pickup).total_seconds() / 60 if pd.notna(pickup) and pd.notna(dropoff) else np.nan
    assert np.isclose(row["trip_duration_minutes"], expected_duration, equal_nan=True)
    if expected_duration > 0 and pd.notna(row[a_columns["distance"]]):
        expected_speed = row[a_columns["distance"]] / (expected_duration / 60)
        assert np.isclose(row["speed_mph"], expected_speed, equal_nan=True)
    else:
        assert pd.isna(row["speed_mph"])
    if pd.notna(pickup):
        assert row["pickup_date"] == pickup.date()
        assert row["pickup_hour"] == pickup.hour
        assert row["day_of_week"] == pickup.day_name()
        assert row["month"] == pickup.month
        assert row["weekend"] == (pickup.weekday() >= 5)
    else:
        assert all(pd.isna(row[field]) for field in ["pickup_date", "pickup_hour", "day_of_week", "month", "weekend"])
    if pd.notna(row[a_columns["origin"]]) and pd.notna(row[a_columns["destination"]]):
        assert row["route_id"] == f"{row[a_columns['origin']]}-{row[a_columns['destination']]}"
    else:
        assert pd.isna(row["route_id"])
print(a_sample.to_string(index=False))
print("PASS: all ten sample rows match independent scalar calculations.")

   pickup_timestamp   dropoff_timestamp  distance_miles  origin_loc_id  dest_loc_id  trip_duration_minutes    speed_mph pickup_date  pickup_hour day_of_week  month  weekend route_id                                   source_file  source_row_1based      sample_reason
2025-04-01 00:47:06 2025-04-01 01:13:25            9.50            138          230              26.316667 2.165928e+01  2025-04-01            0     Tuesday      4    False  138-230 Urban_Flow_Analytics_Taxi_Dataset_2025-04.csv                  1 file-start example
2025-06-01 00:02:50 2025-06-01 00:39:51           10.00            138           50              37.016667 1.620891e+01  2025-06-01            0      Sunday      6     True   138-50 Urban_Flow_Analytics_Taxi_Dataset_2025-06.csv                  1 file-start example
2025-08-01 00:52:23 2025-08-01 01:12:20            8.44            138          141              19.950000 2.538346e+01  2025-08-01            0      Friday      8    False  138-141 Urban_Flow_Analytics_Taxi_Dataset_2025-08.csv                  1 file-start example
2025-10-01 00:15:32 2025-10-01 01:04:03           17.20            132          107              48.516667 2.127104e+01  2025-10-01            0   Wednesday     10    False  132-107 Urban_Flow_Analytics_Taxi_Dataset_2025-10.csv                  1 file-start example
2025-12-01 00:37:08 2025-12-01 00:51:10            2.40            140           48              14.033333 1.026128e+01  2025-12-01            0      Monday     12    False   140-48 Urban_Flow_Analytics_Taxi_Dataset_2025-12.csv                  1 file-start example
2026-03-01 00:02:26 2026-03-01 00:13:45            2.58             48          151              11.316667 1.367894e+01  2026-03-01            0      Sunday      3     True   48-151 Urban_Flow_Analytics_Taxi_Dataset_2026-03.csv                  1 file-start example
2025-04-01 00:39:00 2025-04-01 00:39:00            0.95            233          164               0.000000          NaN  2025-04-01            0     Tuesday      4    False  233-164 Urban_Flow_Analytics_Taxi_Dataset_2025-04.csv                  6      zero duration
2025-11-16 23:12:04 2025-11-16 11:24:45            2.00             74          264            -707.316667          NaN  2025-11-16           23      Sunday     11     True   74-264 Urban_Flow_Analytics_Taxi_Dataset_2025-11.csv            1779718   minimum duration
2025-04-01 09:00:28 2025-04-11 17:01:14            2.50            107           13           14880.766667 1.008013e-02  2025-04-01            9     Tuesday      4    False   107-13 Urban_Flow_Analytics_Taxi_Dataset_2025-04.csv            3231352   maximum duration
2026-02-20 08:00:00 2026-02-20 08:03:00       240830.74            151          166               3.000000 4.816615e+06  2026-02-20            8      Friday      2    False  151-166 Urban_Flow_Analytics_Taxi_Dataset_2026-02.csv            3098087      maximum speed
PASS: all ten sample rows match independent scalar calculations.

### Descriptive summaries and calculation checks

Report min, exact median, mean, and max of defined duration/speed values. Non-positive durations are included in duration summaries and have undefined speed. Undefined values are excluded only from the relevant numeric summary, not from the data. Weekday and weekend totals include a missing category if needed, so every source row is accounted for. No anomaly counts or cleaning recommendations are calculated.

In [18]:
print("New audit fields and observed dtypes:", {field: sorted(types) for field, types in a_field_dtypes.items()})
print("Source-column dtypes:", {column: sorted(types) for column, types in a_dtypes.items()})
print("Duration (minutes) and speed (mph) summaries:")
print(a_summary.to_string(float_format=lambda value: f"{value:.9f}"))
print("Pickup-hour range:", (a_hour_min, a_hour_max))
print("Weekday counts:")
for day in ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]:
    print(f"{day}: {a_weekdays.get(day, 0):,}")
for day, count in a_weekdays.items():
    if day not in ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]:
        print(f"Missing/other weekday ({day}): {count:,}")
print("Weekend versus weekday counts:", dict(a_weekends))
assert sum(a_weekdays.values()) == a_rows
assert sum(a_weekends.values()) == a_rows
assert a_hour_min is None or 0 <= a_hour_min <= a_hour_max <= 23
assert a_snapshot == {str(p): (p.stat().st_size, p.stat().st_mtime_ns) for p in a_files}
print("PASS: calendar counts reconcile to all source rows; source sizes and modification times unchanged.")
print("STOP: Step 4 calculations only. No cleaning, anomaly counts, joined/enriched dataset output, or later processing.")

New audit fields and observed dtypes: {'trip_duration_minutes': ['float64'], 'speed_mph': ['float64'], 'pickup_date': ['object'], 'pickup_hour': ['Int64'], 'day_of_week': ['str'], 'month': ['Int64'], 'weekend': ['boolean'], 'route_id': ['string']}
Source-column dtypes: {'pickup_timestamp': ['str'], 'dropoff_timestamp': ['str'], 'distance_miles': ['float64'], 'origin_loc_id': ['int64'], 'dest_loc_id': ['int64']}
Duration (minutes) and speed (mph) summaries:
                                 min       median         mean               max
field
trip_duration_minutes -707.316666667 13.850000000 17.799116685   14880.766666667
speed_mph                0.000000000  9.230769231 24.309371532 4816614.800000000
Pickup-hour range: (0, 23)
Weekday counts:
Monday: 5,894,446
Tuesday: 6,893,719
Wednesday: 7,194,184
Thursday: 7,494,630
Friday: 7,283,768
Saturday: 7,484,201
Sunday: 6,356,834
Weekend versus weekday counts: {'weekday': 34760747, 'weekend': 13841035}
PASS: calendar counts reconcile to all source rows; source sizes and modification times unchanged.
STOP: Step 4 calculations only. No cleaning, anomaly counts, joined/enriched dataset output, or later processing.

### Step 4 recorded findings

All eight requested fields were created in temporary chunk audit views: `trip_duration_minutes`, `speed_mph`, `pickup_date`, `pickup_hour`, `day_of_week`, `month`, `weekend`, and `route_id`. All **48,601,782 rows across 12 files** were processed without concatenating the full data or removing rows. The source fields had consistent types in every chunk: timestamps were strings, distance was `float64`, and origin/destination IDs were `int64`. No essential columns were missing and no column/type issues were encountered.

| Descriptive statistic | Trip duration (minutes) | Speed (mph; defined on positive-duration rows) |
|---|---:|---:|
| Minimum | -707.316666667 | 0.000000000 |
| Exact median | 13.850000000 | 9.230769231 |
| Mean | 17.799116685 | 24.309371532 |
| Maximum | 14,880.766666667 | 4,816,614.800000000 |

The medians are exact over the defined numeric calculation values, using temporary disk-backed arrays. All temporary files were removed; no enriched/cleaned dataset or `clean_trips.parquet` was saved.

- **Pickup-hour range:** 0-23.
- **Weekdays:** 34,760,747 rows. **Weekends:** 13,841,035 rows. These sum to all 48,601,782 source rows; the full weekday breakdown appears above.
- **Validation:** all ten displayed sample rows passed independent scalar checks for duration, speed, calendar fields, and route ID. Each chunk also confirmed missing speed wherever duration was non-positive or undefined.
- **Unexpected recorded results:** negative and very long durations, and an extreme maximum speed, remain visible in the descriptive summaries. The maximum-speed example uses a source distance of **240,830.74 miles** over **3 minutes**, producing **4,816,614.8 mph** under the requested formula. The zero-duration and negative-duration sample rows correctly have missing speed. These observations are not anomaly counts, thresholds, or cleaning decisions.
- **Preservation:** Steps 1-3 cells and outputs were preserved; source sizes and modification times were unchanged. No source values were imputed or modified.

**Stop after Step 4.** No anomaly counting, cleaning rules, feature contract, splitting, or machine learning was performed.

## Step 5: Anomaly measurement and inspection

Measure anomalies before making cleaning decisions. This section runs independently, preserves Steps 1-4, and processes all monthly CSVs in 200,000-row chunks. No source rows are removed, overwritten, or imputed. Calculated duration and speed are temporary audit fields; speed is defined only for positive duration.

All impact percentages use **48,601,782 source rows**. Checks overlap, and speed thresholds are nested: counts must not be added to estimate distinct affected rows. **80, 100, and 120 mph are inspection thresholds only**, not accepted cleaning cutoffs. Historical-year and out-of-month checks use both timestamps separately and also report an either-timestamp union to avoid double-counting within that union.

In [19]:
from pathlib import Path
import re
import tempfile
import numpy as np
import pandas as pd

m_root=next(p for p in [Path.cwd(), *Path.cwd().parents] if (p/"data"/"raw").is_dir())
m_files=sorted(p for p in (m_root/"data"/"raw").rglob("Urban_Flow_Analytics_Taxi_Dataset_*.csv") if p.is_file()
               and "__MACOSX" not in p.parts and not any(part.startswith("._") for part in p.parts))
assert len(m_files)==12
m_expected_rows=48_601_782
m_required=["pickup_timestamp","dropoff_timestamp","origin_loc_id","dest_loc_id","distance_miles","base_fare","rider_count"]
m_optional=["fare_settlement_method","provider_code","rate_class_id"]
m_usecols={}
for p in m_files:
    header=pd.read_csv(p,nrows=0).columns.tolist()
    missing=set(m_required)-set(header)
    if missing:
        raise ValueError(f"Missing essential columns in {p.name}: {sorted(missing)}")
    m_usecols[p]=m_required+[column for column in m_optional if column in header]
m_snapshot={str(p):(p.stat().st_size,p.stat().st_mtime_ns) for p in m_files}
m_notes={
    "Negative base_fare":"Observed signed fare; refund/reversal semantics require documentation.",
    "Negative distance_miles":"Negative physical trip distance; measure without deciding treatment.",
    "Zero distance with nonzero base_fare":"Requires observed non-missing fare; not automatically a trip error.",
    "rider_count == 0":"Zero recorded riders; semantics/treatment not decided.",
    "Duration <= 0":"Includes negative and zero duration; speed remains missing.",
    "Duration < 0":"Dropoff precedes pickup as recorded; subset of duration <= 0.",
    "Duration == 0":"Identical parsed timestamps; subset of duration <= 0.",
    "Speed > 80 mph":"Inspection only; defined speed on positive-duration rows.",
    "Speed > 100 mph":"Inspection only; nested within >80 mph.",
    "Speed > 120 mph":"Inspection only; nested within >100 mph.",
    "Pickup year 2008/2009":"Calendar year from parsed pickup; retain rows.",
    "Dropoff year 2008/2009":"Calendar year from parsed dropoff; retain rows.",
    "Either timestamp year 2008/2009":"Row union of historical pickup/dropoff checks.",
    "Pickup outside filename month":"Valid pickup before month start or on/after next month.",
    "Dropoff outside filename month":"May include legitimate month-boundary trips.",
    "Either timestamp outside filename month":"Row union of pickup/dropoff month mismatches.",
}
print("Verified columns:",m_required)
print("Optional inspection codes:",m_optional)
print("Exact source files:")
for p in m_files: print(p.name)

Verified columns: ['pickup_timestamp', 'dropoff_timestamp', 'origin_loc_id', 'dest_loc_id', 'distance_miles', 'base_fare', 'rider_count']
Optional inspection codes: ['fare_settlement_method', 'provider_code', 'rate_class_id']
Exact source files:
Urban_Flow_Analytics_Taxi_Dataset_2025-04.csv
Urban_Flow_Analytics_Taxi_Dataset_2025-05.csv
Urban_Flow_Analytics_Taxi_Dataset_2025-06.csv
Urban_Flow_Analytics_Taxi_Dataset_2025-07.csv
Urban_Flow_Analytics_Taxi_Dataset_2025-08.csv
Urban_Flow_Analytics_Taxi_Dataset_2025-09.csv
Urban_Flow_Analytics_Taxi_Dataset_2025-10.csv
Urban_Flow_Analytics_Taxi_Dataset_2025-11.csv
Urban_Flow_Analytics_Taxi_Dataset_2025-12.csv
Urban_Flow_Analytics_Taxi_Dataset_2026-01.csv
Urban_Flow_Analytics_Taxi_Dataset_2026-02.csv
Urban_Flow_Analytics_Taxi_Dataset_2026-03.csv

### Incremental measurements and representative examples

Recompute duration and speed with the Step 4 formulas. Missing inputs do not satisfy numerical comparisons; specifically, a missing fare is not treated as a nonzero fare. Parse timestamps with `errors="coerce"`, `format="mixed"`, without assigning a timezone. Filename-month checks compare valid timestamps to the calendar month in each source name.

For each check, retain up to **10 reproducible random-priority inspection examples** across all matching rows, with a fixed seed per check. These small samples are not proof of a cause. If fewer than 10 records exist, show every available record; if none exist, state that explicitly. Each example includes filename/month, a one-based source data-row number, original values, duration/speed, and available payment/provider/rate codes.

For exact speed percentiles, append only defined positive-duration speeds to one temporary numeric file, partition a disk-backed array at the required order statistics, and interpolate using NumPy's default linear quantile convention. The temporary file is removed afterward. No enriched or cleaned dataset is saved.

In [20]:
m_counts={name:0 for name in m_notes}
m_samples={name:pd.DataFrame() for name in m_notes}
m_rng={name:np.random.default_rng(20260500+i) for i,name in enumerate(m_notes)}
m_file_results=[]
m_rows=0
m_speed_n=0
m_parse_failures={"pickup":0,"dropoff":0}
m_source_dtypes={column:set() for column in m_required}
with tempfile.TemporaryDirectory(prefix="urban_flow_step5_speed_") as m_tmp:
    m_speed_path=Path(m_tmp)/"speed.bin"
    with m_speed_path.open("wb") as m_speed_output:
        for m_path in m_files:
            m_month=re.search(r"(\d{4}-\d{2})\.csv$",m_path.name).group(1)
            m_start=pd.Timestamp(m_month+"-01")
            m_end=m_start+pd.offsets.MonthBegin(1)
            m_result={"source_file":m_path.name,"source_month":m_month,"rows":0,**{name:0 for name in m_notes}}
            with pd.read_csv(m_path,usecols=m_usecols[m_path],parse_dates=False,chunksize=200_000) as m_reader:
                for frame in m_reader:
                    for column in m_required: m_source_dtypes[column].add(str(frame[column].dtype))
                    for column in ["base_fare","distance_miles","rider_count"]:
                        if not pd.api.types.is_numeric_dtype(frame[column]):
                            raise TypeError(f"Unexpected nonnumeric {column} in {m_path.name}; no coercion applied")
                    pickup=pd.to_datetime(frame["pickup_timestamp"],errors="coerce",format="mixed",utc=False)
                    dropoff=pd.to_datetime(frame["dropoff_timestamp"],errors="coerce",format="mixed",utc=False)
                    if pickup.dt.tz is not None or dropoff.dt.tz is not None:
                        raise TypeError("Timezone representation changed from earlier steps; review required")
                    m_parse_failures["pickup"]+=int(pickup.isna().sum())
                    m_parse_failures["dropoff"]+=int(dropoff.isna().sum())
                    frame["trip_duration_minutes"]=(dropoff-pickup).dt.total_seconds()/60
                    positive=frame["trip_duration_minutes"]>0
                    frame["speed_mph"]=np.nan
                    frame.loc[positive,"speed_mph"]=frame.loc[positive,"distance_miles"]/(frame.loc[positive,"trip_duration_minutes"]/60)
                    assert frame.loc[~positive,"speed_mph"].isna().all()
                    speeds=frame["speed_mph"].dropna().to_numpy(dtype="float64")
                    speeds.tofile(m_speed_output)
                    m_speed_n+=len(speeds)
                    del speeds
                    old_pickup=pickup.dt.year.isin([2008,2009])
                    old_dropoff=dropoff.dt.year.isin([2008,2009])
                    outside_pickup=(pickup<m_start)|(pickup>=m_end)
                    outside_dropoff=(dropoff<m_start)|(dropoff>=m_end)
                    masks={
                        "Negative base_fare":frame["base_fare"]<0,
                        "Negative distance_miles":frame["distance_miles"]<0,
                        "Zero distance with nonzero base_fare":(frame["distance_miles"]==0)&frame["base_fare"].notna()&(frame["base_fare"]!=0),
                        "rider_count == 0":frame["rider_count"]==0,
                        "Duration <= 0":frame["trip_duration_minutes"]<=0,
                        "Duration < 0":frame["trip_duration_minutes"]<0,
                        "Duration == 0":frame["trip_duration_minutes"]==0,
                        "Speed > 80 mph":frame["speed_mph"]>80,
                        "Speed > 100 mph":frame["speed_mph"]>100,
                        "Speed > 120 mph":frame["speed_mph"]>120,
                        "Pickup year 2008/2009":old_pickup,
                        "Dropoff year 2008/2009":old_dropoff,
                        "Either timestamp year 2008/2009":old_pickup|old_dropoff,
                        "Pickup outside filename month":outside_pickup,
                        "Dropoff outside filename month":outside_dropoff,
                        "Either timestamp outside filename month":outside_pickup|outside_dropoff,
                    }
                    for name,mask in masks.items():
                        positions=np.flatnonzero(mask.to_numpy(dtype=bool))
                        count=len(positions)
                        m_counts[name]+=count
                        m_result[name]+=count
                        if count:
                            priorities=m_rng[name].random(count)
                            chosen=np.argpartition(priorities, min(10,count)-1)[:10]
                            sample=frame.iloc[positions[chosen]].copy()
                            sample["source_file"]=m_path.name
                            sample["source_month"]=m_month
                            sample["source_row_1based"]=sample.index+1
                            sample["_priority"]=priorities[chosen]
                            previous=m_samples[name]
                            candidates=pd.concat([previous,sample],ignore_index=True) if not previous.empty else sample
                            m_samples[name]=candidates.nsmallest(10,"_priority").copy()
                    m_rows+=len(frame)
                    m_result["rows"]+=len(frame)
                    del frame,pickup,dropoff,masks
            m_file_results.append(m_result)
            print(f"Finished {m_path.name}: {m_result['rows']:,} rows inspected",flush=True)
    print("Computing exact speed percentiles",flush=True)
    m_quantiles=np.array([0.5,0.9,0.95,0.99,0.995,0.999,1.0])
    if not m_speed_n: raise ValueError("No defined positive-duration speeds to summarize")
    vector=np.memmap(m_speed_path,dtype="float64",mode="r+",shape=(m_speed_n,))
    try:
        ranks=(m_speed_n-1)*m_quantiles
        low=np.floor(ranks).astype("int64")
        high=np.ceil(ranks).astype("int64")
        vector.partition(np.unique(np.concatenate([low,high])))
        values=np.array([float(vector[l]) if l==h else float(vector[l])+(float(vector[h])-float(vector[l]))*(r-l)
                         for l,h,r in zip(low,high,ranks)])
        m_speed_percentiles=pd.DataFrame({"Percentile":["50th","90th","95th","99th","99.5th","99.9th","Maximum"],"Speed mph":values})
        vector.flush()
    finally:
        vector._mmap.close()
assert not Path(m_tmp).exists()
assert m_rows==m_expected_rows
m_by_file=pd.DataFrame(m_file_results)
for name in m_notes:
    assert int(m_by_file[name].sum())==m_counts[name]
    assert len(m_samples[name])==min(10,m_counts[name])
print("PASS: all source rows accounted for; per-file counts reconcile; temporary speed file removed.")

Finished Urban_Flow_Analytics_Taxi_Dataset_2025-04.csv: 3,970,553 rows inspected
Finished Urban_Flow_Analytics_Taxi_Dataset_2025-05.csv: 4,591,845 rows inspected
Finished Urban_Flow_Analytics_Taxi_Dataset_2025-06.csv: 4,322,960 rows inspected
Finished Urban_Flow_Analytics_Taxi_Dataset_2025-07.csv: 3,898,963 rows inspected
Finished Urban_Flow_Analytics_Taxi_Dataset_2025-08.csv: 3,574,091 rows inspected
Finished Urban_Flow_Analytics_Taxi_Dataset_2025-09.csv: 4,251,015 rows inspected
Finished Urban_Flow_Analytics_Taxi_Dataset_2025-10.csv: 4,428,699 rows inspected
Finished Urban_Flow_Analytics_Taxi_Dataset_2025-11.csv: 4,181,444 rows inspected
Finished Urban_Flow_Analytics_Taxi_Dataset_2025-12.csv: 4,305,006 rows inspected
Finished Urban_Flow_Analytics_Taxi_Dataset_2026-01.csv: 3,724,889 rows inspected
Finished Urban_Flow_Analytics_Taxi_Dataset_2026-02.csv: 3,399,866 rows inspected
Finished Urban_Flow_Analytics_Taxi_Dataset_2026-03.csv: 3,952,451 rows inspected
Computing exact speed percentiles
PASS: all source rows accounted for; per-file counts reconcile; temporary speed file removed.

### Speed distribution before threshold decisions

These exact percentiles describe defined speed values on positive-duration rows. Zero distances and extreme speeds remain included. Undefined speeds are excluded only from this distribution, never by removing source rows. Example threshold impacts follow in the table; no final speed threshold is selected.

In [21]:
print("Rows with defined positive-duration speed:",m_speed_n)
print(m_speed_percentiles.to_string(index=False,float_format=lambda x:f"{x:,.9f}"))

Rows with defined positive-duration speed: 47950172
Percentile           Speed mph
      50th         9.230769231
      90th        19.007462687
      95th        24.046547711
      99th        34.258064516
    99.5th        38.103382022
    99.9th        46.850574713
   Maximum 4,816,614.800000000

### Anomaly impact and monthly source counts

The impact table uses all 48,601,782 rows as denominator for every check. Counts overlap; historical and month-mismatch union rows are explicitly identified. Monthly counts refer to the source CSV, not the derived pickup month, so suspicious timestamps do not move a row between source-file groups.

In [22]:
m_impact=pd.DataFrame([{"Anomaly":name,"Count":m_counts[name],"Percent of Total":m_counts[name]/m_expected_rows*100,"Notes":note}
                       for name,note in m_notes.items()])
print(m_impact.to_string(index=False,float_format=lambda x:f"{x:.9f}"))
print("Source file row counts:")
print(m_by_file[["source_file","rows"]].to_string(index=False))
print("Anomaly counts by source month (full filenames listed above):")
print(m_by_file.set_index("source_month")[list(m_notes)].T.to_string())
print("Timestamp parsing failures (not assigned a year/month):",m_parse_failures)
print("Observed source dtypes:",{column:sorted(types) for column,types in m_source_dtypes.items()})

                                Anomaly   Count  Percent of Total                                                                  Notes
                     Negative base_fare 2400031       4.938154325 Observed signed fare; refund/reversal semantics require documentation.
                Negative distance_miles       0       0.000000000   Negative physical trip distance; measure without deciding treatment.
   Zero distance with nonzero base_fare 1471746       3.028172918    Requires observed non-missing fare; not automatically a trip error.
                       rider_count == 0  231578       0.476480471                 Zero recorded riders; semantics/treatment not decided.
                          Duration <= 0  651610       1.340712157            Includes negative and zero duration; speed remains missing.
                           Duration < 0    1942       0.003995738          Dropoff precedes pickup as recorded; subset of duration <= 0.
                          Duration == 0  649668       1.336716419                  Identical parsed timestamps; subset of duration <= 0.
                         Speed > 80 mph   13589       0.027959880              Inspection only; defined speed on positive-duration rows.
                        Speed > 100 mph   11899       0.024482641                                Inspection only; nested within >80 mph.
                        Speed > 120 mph   10672       0.021958043                               Inspection only; nested within >100 mph.
                  Pickup year 2008/2009       8       0.000016460                         Calendar year from parsed pickup; retain rows.
                 Dropoff year 2008/2009       8       0.000016460                        Calendar year from parsed dropoff; retain rows.
        Either timestamp year 2008/2009       8       0.000016460                         Row union of historical pickup/dropoff checks.
          Pickup outside filename month     170       0.000349781                Valid pickup before month start or on/after next month.
         Dropoff outside filename month   19538       0.040200172                           May include legitimate month-boundary trips.
Either timestamp outside filename month   19646       0.040422386                          Row union of pickup/dropoff month mismatches.
Source file row counts:
                                  source_file    rows
Urban_Flow_Analytics_Taxi_Dataset_2025-04.csv 3970553
Urban_Flow_Analytics_Taxi_Dataset_2025-05.csv 4591845
Urban_Flow_Analytics_Taxi_Dataset_2025-06.csv 4322960
Urban_Flow_Analytics_Taxi_Dataset_2025-07.csv 3898963
Urban_Flow_Analytics_Taxi_Dataset_2025-08.csv 3574091
Urban_Flow_Analytics_Taxi_Dataset_2025-09.csv 4251015
Urban_Flow_Analytics_Taxi_Dataset_2025-10.csv 4428699
Urban_Flow_Analytics_Taxi_Dataset_2025-11.csv 4181444
Urban_Flow_Analytics_Taxi_Dataset_2025-12.csv 4305006
Urban_Flow_Analytics_Taxi_Dataset_2026-01.csv 3724889
Urban_Flow_Analytics_Taxi_Dataset_2026-02.csv 3399866
Urban_Flow_Analytics_Taxi_Dataset_2026-03.csv 3952451
Anomaly counts by source month (full filenames listed above):
source_month                             2025-04  2025-05  2025-06  2025-07  2025-08  2025-09  2025-10  2025-11  2025-12  2026-01  2026-02  2026-03
Negative base_fare                        186720   325266   275565   247088   261191   252718   321307   395093    48175    39463    26721    20724
Negative distance_miles                        0        0        0        0        0        0        0        0        0        0        0        0
Zero distance with nonzero base_fare       90818   140346   134161   123320   104746   123958   125009   108786   151978   125237   122792   120595
rider_count == 0                           23101    23967    22791    20544    17272    22186    22310    19942    18827    14787    12884    12967
Duration <= 0                              34769    64272    68583    56064    47833    57179    67968    62120    58021    45070    40598    49133
Duration < 0                                 163      101      231        1        2        0        2     1435        2        1        2        2
Duration == 0                              34606    64171    68352    56063    47831    57179    67966    60685    58019    45069    40596    49131
Speed > 80 mph                              1095     1268     1522     1043     1070     1216     1292     1171     1150      874      762     1126
Speed > 100 mph                             1002     1175     1396      947      941     1059     1122     1001      974      732      620      930
Speed > 120 mph                              947     1097     1292      871      851      936     1005      869      847      642      519      796
Pickup year 2008/2009                          0        1        0        1        1        0        0        3        0        0        0        2
Dropoff year 2008/2009                         0        1        0        1        1        0        0        3        0        0        0        2
Either timestamp year 2008/2009                0        1        0        1        1        0        0        3        0        0        0        2
Pickup outside filename month                  7       24       20        7       17        7       13       24        9        7       16       19
Dropoff outside filename month              1103     2939      752     1217     1493      986     3989      809      778     2284     2338      850
Either timestamp outside filename month     1106     2951      765     1221     1507      991     3997      827      783     2288     2348      862
Timestamp parsing failures (not assigned a year/month): {'pickup': 0, 'dropoff': 0}
Observed source dtypes: {'pickup_timestamp': ['str'], 'dropoff_timestamp': ['str'], 'origin_loc_id': ['int64'], 'dest_loc_id': ['int64'], 'distance_miles': ['float64'], 'base_fare': ['float64'], 'rider_count': ['float64']}

### Representative anomaly records

Show up to ten seeded inspection examples per check, ordered by source file and row number for readability. Overlapping checks can show the same row. Fewer than five examples is possible when fewer than five records exist; zero-count checks have no examples to show. Source values are displayed unchanged, alongside temporary duration and speed calculations.

In [23]:
for name in m_notes:
    print("\nANOMALY:",name,"| total rows:",m_counts[name])
    if m_samples[name].empty:
        print("No matching records; no examples available.")
    else:
        shown=m_samples[name].drop(columns="_priority").sort_values(["source_file","source_row_1based"])
        leading=["source_file","source_month","source_row_1based"]
        print(shown[leading+[column for column in shown.columns if column not in leading]].to_string(index=False))
assert m_snapshot=={str(p):(p.stat().st_size,p.stat().st_mtime_ns) for p in m_files}
print("PASS: source sizes and modification times unchanged.")
print("STOP: Step 5 measurement and inspection only. No rows cleaned, removed, imputed, or saved as cleaned data.")

ANOMALY: Negative base_fare | total rows: 2400031
                                  source_file source_month  source_row_1based  provider_code    pickup_timestamp   dropoff_timestamp  rider_count  distance_miles  rate_class_id  origin_loc_id  dest_loc_id  fare_settlement_method  base_fare  trip_duration_minutes  speed_mph
Urban_Flow_Analytics_Taxi_Dataset_2025-04.csv      2025-04            3646483              2 2025-04-18 03:41:11 2025-04-18 03:47:12          NaN            0.70            NaN            234          164                       0      -4.75               6.016667   6.980609
Urban_Flow_Analytics_Taxi_Dataset_2025-05.csv      2025-05            4310201              2 2025-05-23 23:37:33 2025-05-23 23:45:46          NaN            1.32            NaN            211          231                       0      -3.22               8.216667   9.638945
Urban_Flow_Analytics_Taxi_Dataset_2025-06.csv      2025-06              32963              2 2025-06-01 12:02:54 2025-06-01 12:30:04          2.0            7.35            1.0            132           86                       4     -35.20              27.166667  16.233129
Urban_Flow_Analytics_Taxi_Dataset_2025-06.csv      2025-06             178047              2 2025-06-02 21:19:22 2025-06-02 21:28:41          1.0            1.98            1.0            151           74                       3     -11.40               9.316667  12.751342
Urban_Flow_Analytics_Taxi_Dataset_2025-07.csv      2025-07            3422394              2 2025-07-18 20:05:34 2025-07-18 20:19:35          NaN            3.21            NaN            233          238                       0      -4.75              14.016667  13.740785
Urban_Flow_Analytics_Taxi_Dataset_2025-09.csv      2025-09             177412              2 2025-09-03 08:47:27 2025-09-03 09:04:19          1.0            1.04            1.0             48          170                       4     -14.90              16.866667   3.699605
Urban_Flow_Analytics_Taxi_Dataset_2025-11.csv      2025-11            3398154              2 2025-11-07 05:11:21 2025-11-07 05:21:42          NaN            3.80            NaN            166          244                       0      -2.35              10.350000  22.028986
Urban_Flow_Analytics_Taxi_Dataset_2025-11.csv      2025-11            3549194              2 2025-11-11 22:01:00 2025-11-11 22:16:15          NaN            4.42            NaN            226          262                       0      -0.04              15.250000  17.390164
Urban_Flow_Analytics_Taxi_Dataset_2025-11.csv      2025-11            3610443              2 2025-11-13 22:02:17 2025-11-13 22:06:20          NaN            0.78            NaN            246          246                       0     -14.08               4.050000  11.555556
Urban_Flow_Analytics_Taxi_Dataset_2026-02.csv      2026-02             573922              2 2026-02-07 13:37:41 2026-02-07 13:41:15          1.0            0.43            1.0            236          236                       2      -5.10               3.566667   7.233645

ANOMALY: Negative distance_miles | total rows: 0
No matching records; no examples available.

ANOMALY: Zero distance with nonzero base_fare | total rows: 1471746
                                  source_file source_month  source_row_1based  provider_code    pickup_timestamp   dropoff_timestamp  rider_count  distance_miles  rate_class_id  origin_loc_id  dest_loc_id  fare_settlement_method  base_fare  trip_duration_minutes  speed_mph
Urban_Flow_Analytics_Taxi_Dataset_2025-05.csv      2025-05            1161241              2 2025-05-11 02:09:57 2025-05-11 02:10:05          4.0             0.0            5.0            169          169                       1      58.00               0.133333        0.0
Urban_Flow_Analytics_Taxi_Dataset_2025-05.csv      2025-05            1166280              1 2025-05-11 04:40:24 2025-05-11 04:40:49          1.0             0.0            5.0             37           37                       1      30.00               0.416667        0.0
Urban_Flow_Analytics_Taxi_Dataset_2025-05.csv      2025-05            3667216              2 2025-05-08 17:40:22 2025-05-08 17:52:14          NaN             0.0            NaN            231           13                       0      15.55              11.866667        0.0
Urban_Flow_Analytics_Taxi_Dataset_2025-05.csv      2025-05            4296688              2 2025-05-23 16:48:48 2025-05-23 17:13:04          NaN             0.0            NaN            164           48                       0       1.71              24.266667        0.0
Urban_Flow_Analytics_Taxi_Dataset_2025-09.csv      2025-09            4018431              2 2025-09-24 19:13:02 2025-09-24 19:18:51          NaN             0.0            NaN             42           41                       0       7.09               5.816667        0.0
Urban_Flow_Analytics_Taxi_Dataset_2025-12.csv      2025-12            3262185              2 2025-12-05 16:28:15 2025-12-05 16:45:40          NaN             0.0            NaN            107           88                       0      19.23              17.416667        0.0
Urban_Flow_Analytics_Taxi_Dataset_2026-01.csv      2026-01            3544406              2 2026-01-28 16:34:58 2026-01-28 16:55:24          NaN             0.0            NaN             41          239                       0      20.94              20.433333        0.0
Urban_Flow_Analytics_Taxi_Dataset_2026-03.csv      2026-03            3408501              2 2026-03-13 19:31:10 2026-03-13 19:54:59          NaN             0.0            NaN            163          148                       0      47.26              23.816667        0.0
Urban_Flow_Analytics_Taxi_Dataset_2026-03.csv      2026-03            3516195              2 2026-03-16 18:16:53 2026-03-16 18:43:18          NaN             0.0            NaN            262           48                       0      40.97              26.416667        0.0
Urban_Flow_Analytics_Taxi_Dataset_2026-03.csv      2026-03            3928507              2 2026-03-30 19:28:46 2026-03-30 19:39:54          NaN             0.0            NaN             68          107                       0       9.20              11.133333        0.0

ANOMALY: rider_count == 0 | total rows: 231578
                                  source_file source_month  source_row_1based  provider_code    pickup_timestamp   dropoff_timestamp  rider_count  distance_miles  rate_class_id  origin_loc_id  dest_loc_id  fare_settlement_method  base_fare  trip_duration_minutes  speed_mph
Urban_Flow_Analytics_Taxi_Dataset_2025-04.csv      2025-04            2532914              1 2025-04-24 19:02:00 2025-04-24 19:11:51          0.0             1.7            1.0            162          263                       1       11.4               9.850000  10.355330
Urban_Flow_Analytics_Taxi_Dataset_2025-06.csv      2025-06            1734148              1 2025-06-17 16:51:24 2025-06-17 16:58:29          0.0             1.2            1.0            237          236                       1        8.6               7.083333  10.164706
Urban_Flow_Analytics_Taxi_Dataset_2025-07.csv      2025-07            1436377              1 2025-07-17 08:49:17 2025-07-17 08:59:17          0.0             1.0            1.0            230           68                       1       10.0              10.000000   6.000000
Urban_Flow_Analytics_Taxi_Dataset_2025-07.csv      2025-07            2605559              1 2025-07-29 16:03:23 2025-07-29 16:13:32          0.0             1.3            1.0            141          236                       1        9.3              10.150000   7.684729
Urban_Flow_Analytics_Taxi_Dataset_2025-07.csv      2025-07            2643238              1 2025-07-29 21:17:36 2025-07-29 21:26:32          0.0             1.4            1.0            170          237                       1       10.7               8.933333   9.402985
Urban_Flow_Analytics_Taxi_Dataset_2025-09.csv      2025-09            1045049              1 2025-09-11 12:07:00 2025-09-11 12:41:19          0.0             2.7            1.0            107           87                       1       28.2              34.316667   4.720738
Urban_Flow_Analytics_Taxi_Dataset_2025-11.csv      2025-11            3114899              1 2025-11-30 12:04:38 2025-11-30 12:13:06          0.0             1.6            1.0            113          186                       1       10.7               8.466667  11.338583
Urban_Flow_Analytics_Taxi_Dataset_2025-12.csv      2025-12            2442437              1 2025-12-22 15:18:25 2025-12-22 15:31:22          0.0             0.6            1.0            186          164                       1       12.1              12.950000   2.779923
Urban_Flow_Analytics_Taxi_Dataset_2026-01.csv      2026-01            1739547              1 2026-01-21 09:52:14 2026-01-21 10:08:12          0.0             2.4            1.0            166          236                       1       17.0              15.966667   9.018789
Urban_Flow_Analytics_Taxi_Dataset_2026-03.csv      2026-03             105516              1 2026-03-02 12:48:25 2026-03-02 12:52:28          0.0             0.2            1.0            236          237                       1        5.8               4.050000   2.962963

ANOMALY: Duration <= 0 | total rows: 651610
                                  source_file source_month  source_row_1based  provider_code    pickup_timestamp   dropoff_timestamp  rider_count  distance_miles  rate_class_id  origin_loc_id  dest_loc_id  fare_settlement_method  base_fare  trip_duration_minutes  speed_mph
Urban_Flow_Analytics_Taxi_Dataset_2025-04.csv      2025-04             426582              7 2025-04-04 20:26:00 2025-04-04 20:26:00          1.0            1.76            1.0            142          141                       1       14.9                    0.0        NaN
Urban_Flow_Analytics_Taxi_Dataset_2025-04.csv      2025-04             778620              7 2025-04-08 10:57:51 2025-04-08 10:57:51          1.0            0.43            1.0            141          236                       1        5.1                    0.0        NaN
Urban_Flow_Analytics_Taxi_Dataset_2025-07.csv      2025-07            1444142              7 2025-07-17 10:16:14 2025-07-17 10:16:14          1.0            0.56            1.0            234          170                       1        5.8                    0.0        NaN
Urban_Flow_Analytics_Taxi_Dataset_2025-10.csv      2025-10            2134099              7 2025-10-20 14:00:58 2025-10-20 14:00:58          1.0            2.63            1.0            162          113                       1       17.0                    0.0        NaN
Urban_Flow_Analytics_Taxi_Dataset_2025-10.csv      2025-10            2504532              7 2025-10-23 18:54:32 2025-10-23 18:54:32          1.0            0.64            1.0            107          170                       1        5.1                    0.0        NaN
Urban_Flow_Analytics_Taxi_Dataset_2025-11.csv      2025-11            1162892              7 2025-11-11 16:24:36 2025-11-11 16:24:36          1.0            1.40            1.0            234           68                       1       15.6                    0.0        NaN
Urban_Flow_Analytics_Taxi_Dataset_2025-11.csv      2025-11            1354590              7 2025-11-13 11:35:21 2025-11-13 11:35:21          1.0            1.39            1.0            236          239                       1       10.7                    0.0        NaN
Urban_Flow_Analytics_Taxi_Dataset_2025-12.csv      2025-12            1288022              7 2025-12-11 23:22:27 2025-12-11 23:22:27          1.0            1.24            1.0             48          142                       1        7.2                    0.0        NaN
Urban_Flow_Analytics_Taxi_Dataset_2026-01.csv      2026-01            2521060              7 2026-01-30 19:54:03 2026-01-30 19:54:03          1.0            1.66            1.0            161           43                       1       10.0                    0.0        NaN
Urban_Flow_Analytics_Taxi_Dataset_2026-03.csv      2026-03            1076596              7 2026-03-12 10:03:08 2026-03-12 10:03:08          1.0            0.48            1.0            237          237                       2        5.8                    0.0        NaN

ANOMALY: Duration < 0 | total rows: 1942
                                  source_file source_month  source_row_1based  provider_code    pickup_timestamp   dropoff_timestamp  rider_count  distance_miles  rate_class_id  origin_loc_id  dest_loc_id  fare_settlement_method  base_fare  trip_duration_minutes  speed_mph
Urban_Flow_Analytics_Taxi_Dataset_2025-06.csv      2025-06            3992898              6 2025-06-22 16:06:43 2025-06-22 16:06:10          NaN           17.57            NaN             79           51                       0       2.90              -0.550000        NaN
Urban_Flow_Analytics_Taxi_Dataset_2025-11.csv      2025-11             125307              2 2025-11-02 01:55:20 2025-11-02 01:01:22          1.0            1.74            1.0             50          239                       1      10.00             -53.966667        NaN
Urban_Flow_Analytics_Taxi_Dataset_2025-11.csv      2025-11             125889              2 2025-11-02 01:52:32 2025-11-02 01:20:49          2.0            5.70            1.0            114          112                       1      31.70             -31.716667        NaN
Urban_Flow_Analytics_Taxi_Dataset_2025-11.csv      2025-11             126625              2 2025-11-02 01:58:24 2025-11-02 01:11:09          1.0            1.80            1.0            256          148                       1      14.90             -47.250000        NaN
Urban_Flow_Analytics_Taxi_Dataset_2025-11.csv      2025-11             127058              2 2025-11-02 01:44:08 2025-11-02 01:01:23          1.0            2.73            1.0            230           79                       1      17.70             -42.750000        NaN
Urban_Flow_Analytics_Taxi_Dataset_2025-11.csv      2025-11             127586              2 2025-11-02 01:53:53 2025-11-02 01:01:14          1.0            1.07            1.0            234           68                       1       8.60             -52.650000        NaN
Urban_Flow_Analytics_Taxi_Dataset_2025-11.csv      2025-11             128950              2 2025-11-02 01:55:35 2025-11-02 01:00:25          1.0            0.61            1.0            230           48                       1       6.50             -55.166667        NaN
Urban_Flow_Analytics_Taxi_Dataset_2025-11.csv      2025-11             128957              2 2025-11-02 01:44:14 2025-11-02 01:04:26          1.0            3.75            1.0            107          239                       1      21.20             -39.800000        NaN
Urban_Flow_Analytics_Taxi_Dataset_2025-11.csv      2025-11            3236004              1 2025-11-02 01:52:00 2025-11-02 01:01:34          NaN            2.10            NaN            229           75                       0      28.62             -50.433333        NaN
Urban_Flow_Analytics_Taxi_Dataset_2025-11.csv      2025-11            3238237              2 2025-11-02 01:51:17 2025-11-02 01:14:20          NaN            4.65            NaN             80           63                       0      30.37             -36.950000        NaN

ANOMALY: Duration == 0 | total rows: 649668
                                  source_file source_month  source_row_1based  provider_code    pickup_timestamp   dropoff_timestamp  rider_count  distance_miles  rate_class_id  origin_loc_id  dest_loc_id  fare_settlement_method  base_fare  trip_duration_minutes  speed_mph
Urban_Flow_Analytics_Taxi_Dataset_2025-05.csv      2025-05             150055              7 2025-05-02 10:05:22 2025-05-02 10:05:22          1.0            0.73            1.0            161          229                       1        6.5                    0.0        NaN
Urban_Flow_Analytics_Taxi_Dataset_2025-05.csv      2025-05            2839105              7 2025-05-26 22:51:17 2025-05-26 22:51:17          1.0            6.65            1.0            186           33                       1       31.0                    0.0        NaN
Urban_Flow_Analytics_Taxi_Dataset_2025-06.csv      2025-06             463829              7 2025-06-05 14:46:33 2025-06-05 14:46:33          1.0            3.48            1.0            246          236                       1       24.0                    0.0        NaN
Urban_Flow_Analytics_Taxi_Dataset_2025-07.csv      2025-07             378086              1 2025-07-05 22:26:05 2025-07-05 22:26:05          0.0            0.00           99.0             74          264                       3       24.0                    0.0        NaN
Urban_Flow_Analytics_Taxi_Dataset_2025-09.csv      2025-09             619832              7 2025-09-07 09:27:12 2025-09-07 09:27:12          1.0            3.22            1.0            107          262                       1       17.7                    0.0        NaN
Urban_Flow_Analytics_Taxi_Dataset_2025-09.csv      2025-09            3175550              7 2025-09-30 22:24:42 2025-09-30 22:24:42          2.0            1.75            1.0            230          234                       1       13.5                    0.0        NaN
Urban_Flow_Analytics_Taxi_Dataset_2025-11.csv      2025-11            1776727              7 2025-11-16 22:32:28 2025-11-16 22:32:28          1.0            1.10            1.0            230           90                       1        9.3                    0.0        NaN
Urban_Flow_Analytics_Taxi_Dataset_2025-12.csv      2025-12             684137              7 2025-12-06 20:34:31 2025-12-06 20:34:31          1.0            1.60            1.0             48          249                       1       12.1                    0.0        NaN
Urban_Flow_Analytics_Taxi_Dataset_2026-01.csv      2026-01             214819              7 2026-01-03 22:30:35 2026-01-03 22:30:35          1.0            2.29            1.0            238          161                       1       12.1                    0.0        NaN
Urban_Flow_Analytics_Taxi_Dataset_2026-03.csv      2026-03            2307537              7 2026-03-24 17:44:37 2026-03-24 17:44:37          1.0            2.61            1.0            162          249                       1       17.0                    0.0        NaN

ANOMALY: Speed > 80 mph | total rows: 13589
                                  source_file source_month  source_row_1based  provider_code    pickup_timestamp   dropoff_timestamp  rider_count  distance_miles  rate_class_id  origin_loc_id  dest_loc_id  fare_settlement_method  base_fare  trip_duration_minutes     speed_mph
Urban_Flow_Analytics_Taxi_Dataset_2025-06.csv      2025-06             676824              2 2025-06-07 11:56:59 2025-06-07 12:03:08          1.0            8.22            1.0            143          152                       1      15.60               6.150000     80.195122
Urban_Flow_Analytics_Taxi_Dataset_2025-06.csv      2025-06            1440391              1 2025-06-14 13:41:49 2025-06-14 13:43:27          1.0            2.80            1.0            170          170                       1       3.70               1.633333    102.857143
Urban_Flow_Analytics_Taxi_Dataset_2025-06.csv      2025-06            2505202              1 2025-06-25 01:59:56 2025-06-25 02:00:22          1.0            2.20            1.0            141          141                       3       3.00               0.433333    304.615385
Urban_Flow_Analytics_Taxi_Dataset_2025-06.csv      2025-06            4051423              2 2025-06-24 03:08:00 2025-06-24 03:16:00          NaN       128592.98            NaN             90          164                       0       9.98               8.000000 964447.350000

### Step 5 recorded findings and interpretation

All **48,601,782 rows across 12 files** were measured without cleaning or filtering. The impact table above contains exact counts, percentages, notes, and monthly source counts. Every nonempty check includes 10 reproducible inspection examples, except the historical-date checks, which show **all 8 records**. Negative distance has no records to show. Counts overlap and must not be summed.

| Check | Count | Percent of all rows |
|---|---:|---:|
| Negative base fare | 2,400,031 | 4.938154325% |
| Negative distance | 0 | 0% |
| Zero distance with nonzero fare | 1,471,746 | 3.028172918% |
| Zero rider count | 231,578 | 0.476480471% |
| Non-positive duration | 651,610 | 1.340712157% |
| Negative duration (subset) | 1,942 | 0.003995738% |
| Zero duration (subset) | 649,668 | 1.336716419% |
| Speed above 80 mph (inspection only) | 13,589 | 0.027959880% |
| Speed above 100 mph (inspection only) | 11,899 | 0.024482641% |
| Speed above 120 mph (inspection only) | 10,672 | 0.021958043% |

**Exact speed distribution**, using 47,950,172 defined speeds on positive-duration records: p50 **9.230769231**, p90 **19.007462687**, p95 **24.046547711**, p99 **34.258064516**, p99.5 **38.103382022**, p99.9 **46.850574713**, maximum **4,816,614.8 mph**. All defined speeds were retained, including zero and extreme values; no threshold was selected. The temporary numeric file was removed.

**Suspicious timestamps:** pickup year 2008/2009: **8**; dropoff year 2008/2009: **8**; either-timestamp union: **8 (0.000016460%)**. These are the same eight rows: May 2025 **1**, July **1**, August **1**, November **3**, and March 2026 **2**. Out-of-month pickups: **170 (0.000349781%)**; dropoffs: **19,538 (0.040200172%)**; either-timestamp union: **19,646 (0.040422386%)**. There were no timestamp parsing failures.

#### Values that appear inconsistent with the intended measurements

- The extreme implied speeds, including **4,816,614.8 mph**, cannot represent taxi road travel. At least one contributing value or its interpretation is wrong; this does not identify which source field to correct or establish a universal speed cutoff.
- Dates in **2008/2009** are incompatible with the stated 2025-2026 observation period. The audit cannot infer replacement dates or whether these represent intentionally included historical records.
- Negative calculated durations are unusable as elapsed travel times **as currently calculated**. Zero duration with positive distance is also inconsistent with a literal movement-time interpretation. This is not evidence that every underlying trip should be deleted.

#### Ambiguous cases needing documentation or a later policy decision

- **Negative fares:** possible financial adjustments, reversals, or source errors; no payment/rate code meanings are assumed. Source-month counts change substantially, including 395,093 in November and 48,175 in December; causes are untested.
- **Zero distance with nonzero fare:** samples include same and different origin/destination IDs and different rate/payment codes. The source does not establish whether these are special charges, incomplete measurements, or errors.
- **Zero riders:** possible recording conventions or data problems; zero is not imputed to a passenger count.
- **Non-positive duration:** samples include zero timestamps with positive distance. Several negative-duration examples occur on November 2 within the 01:00 hour; a backward-clock/timezone ambiguity is one possible explanation, **not verified**. The source is timezone-naive, so the audit does not assign a timezone or change timestamps. November contains 1,435 of the 1,942 negative-duration rows; no cause is inferred from that concentration.
- **Speeds above inspection thresholds:** examples range from just above a threshold to extreme values. Neither a percentile nor an example threshold determines final acceptability.
- **Month mismatches:** examples include ordinary trips crossing midnight at month-end. Source-file membership alone is not proof of an invalid trip; historical dates and other mismatches require separate interpretation.

Steps 1-4 remain unchanged. Monthly counts reconcile to the full row count, source sizes and modification times remain unchanged, and no source values were overwritten or imputed. **Stop after Step 5:** no final treatment, cleaning rules, cleaned Parquet output, splits, or modelling.

## Step 6: Investigation and proposed cleaning policy

Investigation and policy design only: no source values or rows are changed, and Steps 1-5 remain unchanged. All 12 files are processed sequentially in 200,000-row chunks. Subgroup selections below are temporary measurements, not cleaning. Counts, means, minima/maxima, missingness, code distributions, pairwise overlaps, and proposed-rule unions are exact. Subgroup p50/p95 values use reproducible random-priority samples of at most 5,000 records per subgroup and are explicitly approximate; the Step 5 full-data speed percentiles remain the exact reference.

Groups overlap. Compare zero riders with **positive recorded riders**, not an assumed clean population. Compare negative fares with nonnegative fares, and zero-distance charged rows with positive-distance rows. Missing riders are not silently classified as normal.

External context: the [TLC dictionary](https://www.nyc.gov/assets/tlc/downloads/pdf/data_dictionary_trip_records_yellow.pdf) distinguishes payment and rate types, but the competition's renamed columns are not documented as exact copies. Code meanings are therefore conditional, not assigned facts. [TLC fare rules](https://www.nyc.gov/site/tlc/passengers/taxi-fare.page) include time-based charging during slow movement or waiting, so a zero distance alone cannot invalidate a fare. [NIST clock-change rules](https://www.nist.gov/pml/time-and-frequency-division/popular-links/daylight-saving-time-dst) motivate inspection of the repeated November hour; no timezone is assigned or timestamps corrected here.

In [24]:
from pathlib import Path
from collections import Counter
import json
import numpy as np
import pandas as pd
s_root=next(p for p in [Path.cwd(),*Path.cwd().parents] if (p/"data"/"raw").is_dir())
s_files=sorted(p for p in (s_root/"data"/"raw").rglob("Urban_Flow_Analytics_Taxi_Dataset_*.csv") if p.is_file() and "__MACOSX" not in p.parts and not any(x.startswith("._") for x in p.parts))
assert len(s_files)==12
s_snapshot={str(p):(p.stat().st_size,p.stat().st_mtime_ns) for p in s_files}
s_required=["pickup_timestamp","dropoff_timestamp","distance_miles","base_fare","rider_count","origin_loc_id","dest_loc_id","charge_total","provider_code","fare_settlement_method","rate_class_id","offline_record_flag"]
for p in s_files:
    missing=set(s_required)-set(pd.read_csv(p,nrows=0).columns)
    if missing: raise ValueError(f"Missing fields in {p.name}: {missing}")
s_group_names=["negative_fare","nonnegative_fare","zero_distance_charged","positive_distance","zero_riders","positive_riders","negative_duration","zero_duration","speed_80_to_100","speed_100_to_120","speed_over_120"]
s_metrics=["base_fare","charge_total","distance_miles","trip_duration_minutes","speed_mph"]
s_code_cols=["fare_settlement_method","provider_code","rate_class_id","offline_record_flag"]
s_sizes=Counter(); s_codes={g:{col:Counter() for col in s_code_cols} for g in s_group_names}
s_missing={g:Counter() for g in s_group_names}
s_numeric={g:{col:{"n":0,"sum":0.,"min":float("inf"),"max":-float("inf")} for col in s_metrics} for g in s_group_names}
s_samples={g:pd.DataFrame() for g in s_group_names}
s_rng={g:np.random.default_rng(6000+i) for i,g in enumerate(s_group_names)}
s_rel={g:Counter() for g in s_group_names}
s_baseline_codes={col:Counter() for col in s_code_cols}
s_pair_codes=Counter(); s_hist=[]; s_boundary_samples={}; s_boundary_counts=Counter(); s_rules=Counter(); s_monthly=[]
s_anomaly_names=["negative_fare","negative_distance","zero_distance_charged","zero_riders","nonpositive_duration","speed_over_100","historical","out_of_month"]
s_combinations=np.zeros(256,dtype="int64")
s_rule_names=["historical_quarantine","outside_observation_nonhistorical","negative_fare_or_total_model","negative_distance_model","nonpositive_duration_model","speed_over_100_model"]
s_rule_combinations=np.zeros(64,dtype="int64")
s_rows=0

### Chunked investigation and proposal impact measurement

Inspect signed final charges, other monetary components, codes, missingness, location equality, and duration/distance distributions. Sign associations can support an operational-record hypothesis but cannot prove a refund, reversal, or void without linked transactions or a confirmed dictionary.

Month-mismatch partitions (inspection categories, not deletion rules): historical; nonhistorical records touching the adjacent month boundary with positive duration at most two hours and timestamps within two hours of that boundary; other adjacent-boundary records; remaining mismatches. The two-hour window is only an explanatory bucket; changing it does not change the proposed removal policy. Sample every partition that exists.

The proposed model-eligibility scenario measured here excludes out-of-observation pickups, negative base/final fares, negative distances, non-positive durations, and speeds above 100 mph. It retains zero riders and zero-distance charged trips unless another rule applies. All rules are Boolean measurements only. Historical quarantine and observation scope are separate from task-specific model exclusions; raw archives always retain everything.

In [25]:
for path in s_files:
    month=path.stem[-7:]; start=pd.Timestamp(month+"-01"); end=start+pd.offsets.MonthBegin(1)
    monthly=Counter(); monthly["source_month"]=month
    with pd.read_csv(path,chunksize=200_000,parse_dates=False) as reader:
        for f in reader:
            pickup=pd.to_datetime(f.pickup_timestamp,errors="coerce",format="mixed")
            dropoff=pd.to_datetime(f.dropoff_timestamp,errors="coerce",format="mixed")
            assert pickup.notna().all() and dropoff.notna().all() and pickup.dt.tz is None and dropoff.dt.tz is None
            f["trip_duration_minutes"]=(dropoff-pickup).dt.total_seconds()/60
            positive=f.trip_duration_minutes>0
            f["speed_mph"]=np.nan
            f.loc[positive,"speed_mph"]=f.loc[positive,"distance_miles"]/(f.loc[positive,"trip_duration_minutes"]/60)
            groups={"negative_fare":f.base_fare<0,"nonnegative_fare":f.base_fare>=0,
                "zero_distance_charged":f.distance_miles.eq(0)&f.base_fare.notna()&f.base_fare.ne(0),"positive_distance":f.distance_miles>0,
                "zero_riders":f.rider_count.eq(0),"positive_riders":f.rider_count>0,
                "negative_duration":f.trip_duration_minutes<0,"zero_duration":f.trip_duration_minutes.eq(0),
                "speed_80_to_100":(f.speed_mph>80)&(f.speed_mph<=100),"speed_100_to_120":(f.speed_mph>100)&(f.speed_mph<=120),"speed_over_120":f.speed_mph>120}
            for col in s_code_cols:
                s_baseline_codes[col].update({str(k):int(v) for k,v in f[col].value_counts(dropna=False).items()})
            for g,mask in groups.items():
                selected=f.loc[mask]; count=len(selected); s_sizes[g]+=count
                if not count: continue
                s_missing[g].update({k:int(v) for k,v in selected.isna().sum().items()})
                for col in s_code_cols: s_codes[g][col].update({str(k):int(v) for k,v in selected[col].value_counts(dropna=False).items()})
                for col in s_metrics:
                    vals=selected[col].dropna(); stat=s_numeric[g][col]
                    if len(vals):
                        stat["n"]+=len(vals); stat["sum"]+=float(vals.sum()); stat["min"]=min(stat["min"],float(vals.min())); stat["max"]=max(stat["max"],float(vals.max()))
                relationships={"same_origin_destination":selected.origin_loc_id.eq(selected.dest_loc_id),"positive_duration":selected.trip_duration_minutes>0,
                    "negative_final_charge":selected.charge_total<0,"zero_final_charge":selected.charge_total.eq(0),"positive_final_charge":selected.charge_total>0,
                    "positive_distance":selected.distance_miles>0,"duration_at_most_one_minute":selected.trip_duration_minutes.between(0,1,inclusive="right")}
                money_cols=[col for col in ["surcharge_misc","transit_tax","driver_tip_payment","toll_total","service_improvement_fee","zone_congestion_fee","Airport_fee","congestion_relief_fee"] if col in selected]
                relationships["any_negative_other_monetary_component"]=(selected[money_cols]<0).any(axis=1)
                for name,m in relationships.items(): s_rel[g][name]+=int(m.sum())
                priorities=s_rng[g].random(count); chosen=np.argpartition(priorities,min(5000,count)-1)[:5000]
                sample=selected.iloc[chosen].copy(); sample["source_file"]=path.name; sample["source_row_1based"]=sample.index+1; sample["_priority"]=priorities[chosen]
                candidates=pd.concat([s_samples[g],sample],ignore_index=True) if not s_samples[g].empty else sample
                s_samples[g]=candidates.nsmallest(5000,"_priority").copy()
                if g=="negative_fare":
                    s_pair_codes.update({str(k):int(v) for k,v in selected.groupby(["fare_settlement_method","provider_code"],dropna=False).size().items()})
            historical=pickup.dt.year.isin([2008,2009])|dropoff.dt.year.isin([2008,2009])
            outmonth=(pickup<start)|(pickup>=end)|(dropoff<start)|(dropoff>=end)
            if historical.any():
                h=f.loc[historical].copy(); h["source_file"]=path.name; h["source_row_1based"]=h.index+1; s_hist.append(h)
            near_boundary=pd.Series(False,index=f.index)
            for b in [start,end]:
                near_boundary|=(pickup-b).abs().le(pd.Timedelta(hours=2))&(dropoff-b).abs().le(pd.Timedelta(hours=2))
            short_boundary=outmonth&~historical&near_boundary&positive&f.trip_duration_minutes.le(120)
            adjacent_any=((pickup>=start-pd.Timedelta(days=1))&(pickup<end+pd.Timedelta(days=1))&(dropoff>=start-pd.Timedelta(days=1))&(dropoff<end+pd.Timedelta(days=1)))
            other_adjacent=outmonth&~historical&~short_boundary&adjacent_any
            remaining=outmonth&~historical&~short_boundary&~other_adjacent
            partitions={"historical":historical,"short_near_boundary":short_boundary,"other_adjacent_boundary":other_adjacent,"remaining_month_mismatch":remaining}
            for name,mask in partitions.items():
                s_boundary_counts[name]+=int(mask.sum())
                prior=s_boundary_samples.get(name,pd.DataFrame())
                if len(prior)<10 and mask.any():
                    sample=f.loc[mask].head(10-len(prior)).copy(); sample["source_file"]=path.name;sample["source_row_1based"]=sample.index+1
                    s_boundary_samples[name]=pd.concat([prior,sample],ignore_index=True) if len(prior) else sample
            dst=(f.trip_duration_minutes<0)&pickup.dt.normalize().eq(pd.Timestamp("2025-11-02"))&dropoff.dt.normalize().eq(pd.Timestamp("2025-11-02"))&pickup.dt.hour.eq(1)&dropoff.dt.hour.eq(1)&f.trip_duration_minutes.gt(-60)
            s_rules["negative_duration_repeated_hour_candidate"]+=int(dst.sum())
            outperiod=(pickup<pd.Timestamp("2025-04-01"))|(pickup>=pd.Timestamp("2026-04-01"))
            anomaly_masks=[groups["negative_fare"],f.distance_miles<0,groups["zero_distance_charged"],groups["zero_riders"],f.trip_duration_minutes<=0,f.speed_mph>100,historical,outmonth]
            bits=np.zeros(len(f),dtype="uint16")
            for i,mask in enumerate(anomaly_masks):bits|=mask.to_numpy(dtype="uint16")<<i
            s_combinations+=np.bincount(bits,minlength=256)
            rule_masks=[historical,outperiod&~historical,(f.base_fare<0)|(f.charge_total<0),f.distance_miles<0,f.trip_duration_minutes<=0,f.speed_mph>100]
            rbits=np.zeros(len(f),dtype="uint16")
            for i,(name,mask) in enumerate(zip(s_rule_names,rule_masks)):
                s_rules[name]+=int(mask.sum());monthly[name]+=int(mask.sum());rbits|=mask.to_numpy(dtype="uint16")<<i
            s_rule_combinations+=np.bincount(rbits,minlength=64)
            s_rules["zero_riders_in_retained_model_rows"]+=int((groups["zero_riders"]&(rbits==0)).sum())
            s_rules["zero_distance_charged_in_retained_model_rows"]+=int((groups["zero_distance_charged"]&(rbits==0)).sum())
            monthly["model_union"]+=int((rbits!=0).sum()); monthly["rows"]+=len(f);s_rows+=len(f)
            del f,selected,candidates,sample
    s_monthly.append(dict(monthly));print(f"Finished {path.name}: {monthly['rows']:,} rows investigated",flush=True)
assert s_rows==48_601_782 and s_combinations.sum()==s_rows and s_rule_combinations.sum()==s_rows
assert sum(s_boundary_counts.values())==19_646
print("PASS: counts reconcile; proposed rules measured only.")

step6_25:5: DtypeWarning: Columns (0: offline_record_flag) have mixed types. Specify dtype option on import or set low_memory=False.
Finished Urban_Flow_Analytics_Taxi_Dataset_2025-04.csv: 3,970,553 rows investigated
step6_25:5: DtypeWarning: Columns (0: offline_record_flag) have mixed types. Specify dtype option on import or set low_memory=False.
Finished Urban_Flow_Analytics_Taxi_Dataset_2025-05.csv: 4,591,845 rows investigated
step6_25:5: DtypeWarning: Columns (0: offline_record_flag) have mixed types. Specify dtype option on import or set low_memory=False.
Finished Urban_Flow_Analytics_Taxi_Dataset_2025-06.csv: 4,322,960 rows investigated
step6_25:5: DtypeWarning: Columns (0: offline_record_flag) have mixed types. Specify dtype option on import or set low_memory=False.
Finished Urban_Flow_Analytics_Taxi_Dataset_2025-07.csv: 3,898,963 rows investigated
step6_25:5: DtypeWarning: Columns (0: offline_record_flag) have mixed types. Specify dtype option on import or set low_memory=False.
Finished Urban_Flow_Analytics_Taxi_Dataset_2025-08.csv: 3,574,091 rows investigated
step6_25:5: DtypeWarning: Columns (0: offline_record_flag) have mixed types. Specify dtype option on import or set low_memory=False.
Finished Urban_Flow_Analytics_Taxi_Dataset_2025-09.csv: 4,251,015 rows investigated
step6_25:5: DtypeWarning: Columns (0: offline_record_flag) have mixed types. Specify dtype option on import or set low_memory=False.
Finished Urban_Flow_Analytics_Taxi_Dataset_2025-10.csv: 4,428,699 rows investigated
step6_25:5: DtypeWarning: Columns (0: offline_record_flag) have mixed types. Specify dtype option on import or set low_memory=False.
Finished Urban_Flow_Analytics_Taxi_Dataset_2025-11.csv: 4,181,444 rows investigated
step6_25:5: DtypeWarning: Columns (0: offline_record_flag) have mixed types. Specify dtype option on import or set low_memory=False.
Finished Urban_Flow_Analytics_Taxi_Dataset_2025-12.csv: 4,305,006 rows investigated
step6_25:5: DtypeWarning: Columns (0: offline_record_flag) have mixed types. Specify dtype option on import or set low_memory=False.
Finished Urban_Flow_Analytics_Taxi_Dataset_2026-01.csv: 3,724,889 rows investigated
step6_25:5: DtypeWarning: Columns (0: offline_record_flag) have mixed types. Specify dtype option on import or set low_memory=False.
Finished Urban_Flow_Analytics_Taxi_Dataset_2026-02.csv: 3,399,866 rows investigated
step6_25:5: DtypeWarning: Columns (0: offline_record_flag) have mixed types. Specify dtype option on import or set low_memory=False.
Finished Urban_Flow_Analytics_Taxi_Dataset_2026-03.csv: 3,952,451 rows investigated
PASS: counts reconcile; proposed rules measured only.

### Distributions, code relationships, and missingness

Code tables show subgroup counts, percent within subgroup, and percent of all rows having that code. Code labels stay numeric. Means/minima/maxima and missing counts are exact; sample p50/p95 are approximate and should not be used as precise cutoffs. Positive riders and nonnegative fares are comparison groups, not certified normal records.

In [26]:
s_distribution_rows=[];s_code_rows=[];s_missing_rows=[]
for g in s_group_names:
    for col,stat in s_numeric[g].items():
        sample=s_samples[g][col].dropna() if len(s_samples[g]) else pd.Series(dtype=float)
        s_distribution_rows.append({"group":g,"field":col,"defined_n":stat["n"],"min":stat["min"] if stat["n"] else np.nan,"mean":stat["sum"]/stat["n"] if stat["n"] else np.nan,
          "sample_p50":sample.quantile(.5),"sample_p95":sample.quantile(.95),"max":stat["max"] if stat["n"] else np.nan})
    for col in s_code_cols:
        for value,count in s_codes[g][col].items():
            s_code_rows.append({"group":g,"column":col,"code":value,"count":count,"percent_within_group":100*count/s_sizes[g],"percent_of_all_rows_with_code":100*count/s_baseline_codes[col][value]})
    for col,count in s_missing[g].items():
        s_missing_rows.append({"group":g,"column":col,"missing":count,"percent":100*count/s_sizes[g] if s_sizes[g] else np.nan})
s_distributions=pd.DataFrame(s_distribution_rows);s_code_table=pd.DataFrame(s_code_rows);s_missing_table=pd.DataFrame(s_missing_rows)
print("Exact subgroup sizes:",dict(s_sizes))
print(s_distributions.to_string(index=False))
print("Code relationships:");print(s_code_table.to_string(index=False))
print("Negative fare payment/provider combinations:",dict(s_pair_codes))
print("Missingness comparison, zero vs positive riders:");print(s_missing_table[s_missing_table.group.isin(["zero_riders","positive_riders"])].to_string(index=False))
print("Relationships: count and percent within each subgroup")
for g in s_group_names:
    print(g,{k:{"count":v,"percent":100*v/s_sizes[g]} for k,v in s_rel[g].items()})

Exact subgroup sizes: {'negative_fare': 2400031, 'nonnegative_fare': 46201751, 'zero_distance_charged': 1471746, 'positive_distance': 47123012, 'zero_riders': 231578, 'positive_riders': 35964936, 'negative_duration': 1942, 'zero_duration': 649668, 'speed_80_to_100': 1690, 'speed_100_to_120': 1227, 'speed_over_120': 10672}
                group                 field  defined_n          min         mean  sample_p50    sample_p95           max
        negative_fare             base_fare    2400031 -2555.200000   -10.294165   -4.750000     -1.040000 -1.000000e-02
        negative_fare          charge_total    2400031 -2560.200000    -6.552736    2.485000      8.210500  1.151500e+02
        negative_fare        distance_miles    2400031     0.000000    13.579385    2.300000     11.512000  3.212424e+05
        negative_fare trip_duration_minutes    2400031   -49.283333    18.194396   16.000000     40.166667  4.210117e+03
        negative_fare             speed_mph    2399838     0.000000    48.391415    9.878419     26.637929  2.442087e+06
     nonnegative_fare             base_fare   46201751     0.000000    20.874986   14.900000     56.915000  3.254780e+05
     nonnegative_fare          charge_total   46201751   -11.690000    29.639309   22.545000     75.385000  3.255285e+05
     nonnegative_fare        distance_miles   46201751     0.000000     6.504831    1.805000     12.100000  3.979944e+05
     nonnegative_fare trip_duration_minutes   46201751  -707.316667    17.778583   13.733333     44.233333  1.488077e+04
     nonnegative_fare             speed_mph   45550334     0.000000    23.040599    9.146050     23.483363  4.816615e+06
zero_distance_charged             base_fare    1471746  -999.000000    22.616557   17.605000     77.000000  3.237360e+03
zero_distance_charged          charge_total    1471746 -1147.170000    28.961535   22.995000     90.962000  3.240610e+03
zero_distance_charged        distance_miles    1471746     0.000000     0.000000    0.000000      0.000000  0.000000e+00
zero_distance_charged trip_duration_minutes    1471746  -120.583333    15.095036   12.966667     38.284167  9.265150e+03
zero_distance_charged             speed_mph    1455127     0.000000     0.000000    0.000000      0.000000  0.000000e+00
    positive_distance             base_fare   47123012 -2555.200000    19.236223   14.200000     57.253000  3.254780e+05
    positive_distance          charge_total   47123012 -2560.200000    27.821488   21.925000     76.761500  3.255285e+05
    positive_distance        distance_miles   47123012     0.010000     7.069275    1.900000     12.900000  3.979944e+05
    positive_distance trip_duration_minutes   47123012  -707.316667    17.885427   13.666667     46.201667  1.488077e+04
    positive_distance             speed_mph   46488457     0.000097    25.073720    9.395018     24.358573  4.816615e+06
          zero_riders             base_fare     231578  -885.000000    17.141074   12.725000     46.400000  2.500000e+03
          zero_riders          charge_total     231578  -886.000000    25.941110   20.200000     66.842500  2.500000e+03
          zero_riders        distance_miles     231578     0.000000     2.553954    1.500000      9.400000  9.007000e+02
          zero_riders trip_duration_minutes     231578  -707.316667    14.502233   11.300000     35.869167  1.439083e+03
          zero_riders             speed_mph     229453     0.000000    13.413570    8.571429     19.703139  3.960000e+04
      positive_riders             base_fare   35964936 -2555.200000    19.334335   13.500000     70.000000  3.254780e+05
      positive_riders          charge_total   35964936 -2560.200000    28.764630   21.795000     85.020000  3.255285e+05
      positive_riders        distance_miles   35964936     0.000000     3.577041    1.715000     15.300000  1.869676e+05
      positive_riders trip_duration_minutes   35964936  -208.883333    17.512584   12.775000     48.390833  9.265150e+03
      positive_riders             speed_mph   35317160     0.000000    11.216300    8.988235     24.639573  1.226017e+06
    negative_duration             base_fare       1942   -70.200000    16.297915   14.900000     42.900000  1.472000e+02
    negative_duration          charge_total       1942   -75.950000    27.815984   26.095000     54.687500  1.561300e+02
    negative_duration        distance_miles       1942     0.000000     5.088512    3.925000     13.699000  3.236000e+01
    negative_duration trip_duration_minutes       1942  -707.316667   -30.953999  -36.833333     -0.133333 -1.666667e-02
    negative_duration             speed_mph          0          NaN          NaN         NaN           NaN           NaN
        zero_duration             base_fare     649668   -13.560000    16.874591   12.100000     44.300000  2.500000e+03
        zero_duration          charge_total     649668    -8.560000    26.312830   20.580000     67.114500  2.500000e+03
        zero_duration        distance_miles     649668     0.000000     2.747827    1.530000      9.340500  2.204645e+04
        zero_duration trip_duration_minutes     649668     0.000000     0.000000    0.000000      0.000000  0.000000e+00
        zero_duration             speed_mph          0          NaN          NaN         NaN           NaN           NaN
      speed_80_to_100             base_fare       1690   -50.000000    27.314320   19.685000     86.000000  5.000000e+02
      speed_80_to_100          charge_total       1690   -51.000000    33.678189   23.795000    103.615000  5.010000e+02
      speed_80_to_100        distance_miles       1690     0.050000    17.685692   17.500000     45.455000  2.820300e+02
      speed_80_to_100 trip_duration_minutes       1690     0.033333    11.955611   11.800000     31.342500  2.047667e+02
      speed_80_to_100             speed_mph       1690    80.007805    89.132853   89.869844     98.803194  1.000000e+02
     speed_100_to_120             base_fare       1227   -70.000000    25.048639   18.060000     85.000000  2.970000e+02
     speed_100_to_120          charge_total       1227   -80.740000    31.280896   21.680000    101.610000  3.481900e+02
     speed_100_to_120        distance_miles       1227     0.030000    18.224099   17.400000     47.600000  9.370000e+01
     speed_100_to_120 trip_duration_minutes       1227     0.016667    10.019234    9.416667     26.315000  4.940000e+01
     speed_100_to_120             speed_mph       1227   100.025608   110.204409  109.134328    120.000000  1.200000e+02
       speed_over_120             base_fare      10672 -1508.700000    26.467528   14.775000     87.509500  2.588100e+03
       speed_over_120          charge_total      10672 -1514.450000    34.049039   20.545000    106.200000  2.593850e+03
       speed_over_120        distance_miles      10672     0.040000 15478.455321    7.495000 114670.734500  3.979944e+05
       speed_over_120 trip_duration_minutes      10672     0.016667     7.005043    0.433333     31.232500  4.650000e+02
       speed_over_120             speed_mph      10672   120.000000 61378.845837  639.346154 377037.983152  4.816615e+06
Code relationships:
                group                 column code    count  percent_within_group  percent_of_all_rows_with_code
        negative_fare fare_settlement_method    4   455956             18.997921                      46.537899
        negative_fare fare_settlement_method    2   162267              6.761038                       3.638446
        negative_fare fare_settlement_method    3    86005              3.583495                      30.996367
        negative_fare fare_settlement_method    1     1799              0.074957                       0.005902
        negative_fare fare_settlement_method    0  1694004             70.582588                      13.655521
        negative_fare          provider_code    2  2400031            100.000000                       6.223974
        negative_fare          rate_class_id  1.0   617483             25.728126                       1.861340
        negative_fare          rate_class_id  2.0    45455              1.893934                       3.615600
        negative_fare          rate_class_id  5.0    20155              0.839781                       4.396834
        negative_fare          rate_class_id  3.0    16389              0.682866                      10.391068
        negative_fare          rate_class_id  4.0     6542              0.272580                       5.516671
        negative_fare          rate_class_id  nan  1694004             70.582588                      13.655521
        negative_fare          rate_class_id  6.0        3              0.000125                       6.250000
        negative_fare    offline_record_flag    N   706001             29.416328                       1.954655
        negative_fare    offline_record_flag    Y       26              0.001083                       0.033522
        negative_fare    offline_record_flag  nan  1694004             70.582588                      13.655521
     nonnegative_fare fare_settlement_method    1 30477705             65.966558                      99.994098
     nonnegative_fare fare_settlement_method    2  4297521              9.301641                      96.361554
     nonnegative_fare fare_settlement_method    4   523796              1.133715                      53.462101
     nonnegative_fare fare_settlement_method    3   191463              0.414406                      69.003633
     nonnegative_fare fare_settlement_method    0 10711264             23.183675                      86.344479
     nonnegative_fare fare_settlement_method    5        2              0.000004                     100.000000
     nonnegative_fare          provider_code    2 36161038             78.267679                      93.776026
     nonnegative_fare          provider_code    1  9356276             20.250912                     100.000000
     nonnegative_fare          provider_code    7   642536              1.390718                     100.000000
     nonnegative_fare          provider_code    6    41901              0.090691                     100.000000
     nonnegative_fare          rate_class_id  1.0 32556620             70.466204                      98.138660
     nonnegative_fare          rate_class_id  2.0  1211736              2.622706                      96.384400
     nonnegative_fare          rate_class_id 99.0  1030466              2.230361                     100.000000
     nonnegative_fare          rate_class_id  5.0   438243              0.948542                      95.603166
     nonnegative_fare          rate_class_id  3.0   141333              0.305904                      89.608932
     nonnegative_fare          rate_class_id  4.0   112044              0.242510                      94.483329
     nonnegative_fare          rate_class_id  6.0       45              0.000097                      93.750000
     nonnegative_fare          rate_class_id  nan 10711264             23.183675                      86.344479
     nonnegative_fare    offline_record_flag    N 35412952             76.648506                      98.045345
     nonnegative_fare    offline_record_flag    Y    77535              0.167818                      99.966478
     nonnegative_fare    offline_record_flag  nan 10711264             23.183675                      86.344479
zero_distance_charged fare_settlement_method    1   254008             17.258956                       0.833373
zero_distance_charged fare_settlement_method    2   101725              6.911858                       2.280938
zero_distance_charged fare_settlement_method    4    64317              4.370115                       6.564620
zero_distance_charged fare_settlement_method    3    51973              3.531384                      18.731169
zero_distance_charged fare_settlement_method    0   999723             67.927686                       8.058859
zero_distance_charged          provider_code    2  1321309             89.778331                       3.426536
zero_distance_charged          provider_code    1   140009              9.513123                       1.496418
zero_distance_charged          provider_code    7    10428              0.708546                       1.622944
zero_distance_charged          rate_class_id  1.0   255597             17.366923                       0.770471
zero_distance_charged          rate_class_id  5.0   161122             10.947677                      35.148932
zero_distance_charged          rate_class_id 99.0     8997              0.611315                       0.873100
zero_distance_charged          rate_class_id  2.0    36459              2.477262                       2.900037
zero_distance_charged          rate_class_id  3.0     9549              0.648821                       6.054323
zero_distance_charged          rate_class_id  4.0      267              0.018142                       0.225153
zero_distance_charged          rate_class_id  6.0       32              0.002174                      66.666667
zero_distance_charged          rate_class_id  nan   999723             67.927686                       8.058859
zero_distance_charged    offline_record_flag    N   467420             31.759556                       1.294113
zero_distance_charged    offline_record_flag    Y     4603              0.312758                       5.934684
zero_distance_charged    offline_record_flag  nan   999723             67.927686                       8.058859
    positive_distance fare_settlement_method    1 30225341             64.141360                      99.166118
    positive_distance fare_settlement_method    2  4353920              9.239477                      97.626165
    positive_distance fare_settlement_method    4   914158              1.939940                      93.305040
    positive_distance fare_settlement_method    3   224372              0.476141                      80.864100
    positive_distance fare_settlement_method    0 11405220             24.203079                      91.938522
    positive_distance fare_settlement_method    5        1              0.000002                      50.000000
    positive_distance          provider_code    2 37235730             79.018145                      96.563013
    positive_distance          provider_code    1  9213273             19.551537                      98.471582
    positive_distance          provider_code    7   632108              1.341400                      98.377056
    positive_distance          provider_code    6    41901              0.088918                     100.000000
    positive_distance          rate_class_id  1.0 32913839             69.846637                      99.215460
    positive_distance          rate_class_id  2.0  1220170              2.589329                      97.055260
    positive_distance          rate_class_id 99.0  1020876              2.166407                      99.069353
    positive_distance          rate_class_id  5.0   296518              0.629242                      64.685710
    positive_distance          rate_class_id  3.0   148085              0.314252                      93.889882
    positive_distance          rate_class_id  4.0   118289              0.251022                      99.749549
    positive_distance          rate_class_id  6.0       15              0.000032                      31.250000
    positive_distance          rate_class_id  nan 11405220             24.203079                      91.938522
    positive_distance    offline_record_flag    N 35645159             75.642786                      98.688240
    positive_distance    offline_record_flag    Y    72633              0.154135                      93.646291
    positive_distance    offline_record_flag  nan 11405220             24.203079                      91.938522
          zero_riders fare_settlement_method    1   191660             82.762611                       0.628816
          zero_riders fare_settlement_method    2    32316             13.954693                       0.724608
          zero_riders fare_settlement_method    3     5408              2.335282                       1.949054
          zero_riders fare_settlement_method    4     2193              0.946981                       0.223832
          zero_riders fare_settlement_method    5        1              0.000432                      50.000000
          zero_riders          provider_code    1   215567             93.086131                       2.303983
          zero_riders          provider_code    2    16011              6.913869                       0.041521
          zero_riders          rate_class_id  1.0   220559             95.241776                       0.664853
          zero_riders          rate_class_id  2.0     4144              1.789462                       0.329624
          zero_riders          rate_class_id  5.0     2975              1.284664                       0.648999
          zero_riders          rate_class_id 99.0     1895              0.818299                       0.183897
          zero_riders          rate_class_id  4.0      330              0.142501                       0.278279
          zero_riders          rate_class_id  3.0     1666              0.719412                       1.056289
          zero_riders          rate_class_id  6.0        9              0.003886                      18.750000
          zero_riders    offline_record_flag    N   225681             97.453558                       0.624827
          zero_riders    offline_record_flag    Y     5897              2.546442                       7.603048
      positive_riders fare_settlement_method    1 30287844             84.214925                      99.371184
      positive_riders fare_settlement_method    2  4427472             12.310524                      99.275392
      positive_riders fare_settlement_method    4   977559              2.718089                      99.776168
      positive_riders fare_settlement_method    3   272060              0.756459                      98.050946
      positive_riders fare_settlement_method    5        1              0.000003                      50.000000
      positive_riders          provider_code    2 27808395             77.320852                      72.115208
      positive_riders          provider_code    1  7514005             20.892585                      80.309784
      positive_riders          provider_code    7   642536              1.786562                     100.000000
      positive_riders          rate_class_id  1.0 32953544             91.626867                      99.335147
      positive_riders          rate_class_id  2.0  1253047              3.484080                      99.670376
      positive_riders          rate_class_id 99.0  1028571              2.859927                      99.816103
      positive_riders          rate_class_id  5.0   455423              1.266297                      99.351001
      positive_riders          rate_class_id  3.0   156056              0.433912                      98.943711
      positive_riders          rate_class_id  4.0   118256              0.328809                      99.721721
      positive_riders          rate_class_id  6.0       39              0.000108                      81.250000
      positive_riders    offline_record_flag    N 35893272             99.800739                      99.375173
      positive_riders    offline_record_flag    Y    71664              0.199261                      92.396952
    negative_duration fare_settlement_method    1      943             48.558187                       0.003094
    negative_duration fare_settlement_method    2       74              3.810505                       0.001659
    negative_duration fare_settlement_method    0      903             46.498455                       0.007279
    negative_duration fare_settlement_method    3        6              0.308960                       0.002162

### Inspection records and timestamp partitions

Show ten seeded inspection records per investigated group when available, **all eight historical rows with every original column**, and available boundary-partition examples. A repeated-hour candidate is only a clock-ambiguity hypothesis, not a corrected trip. Month-boundary buckets do not select rows for deletion.

In [27]:
for g in ["negative_fare","zero_distance_charged","zero_riders","negative_duration","zero_duration","speed_80_to_100","speed_100_to_120","speed_over_120"]:
    print("\nInspection group:",g)
    if len(s_samples[g]):print(s_samples[g].head(10).drop(columns="_priority").to_string(index=False))
s_historical=pd.concat(s_hist,ignore_index=True)
assert len(s_historical)==8
print("ALL EIGHT HISTORICAL ROWS, ALL ORIGINAL FIELDS:");print(s_historical.to_string(index=False))
print("Month-mismatch partitions:",dict(s_boundary_counts))
for name,sample in s_boundary_samples.items():print(name);print(sample.to_string(index=False))
print("Negative-duration repeated-hour candidates:",s_rules["negative_duration_repeated_hour_candidate"])

Inspection group: negative_fare
 provider_code    pickup_timestamp   dropoff_timestamp  rider_count  distance_miles  rate_class_id offline_record_flag  origin_loc_id  dest_loc_id  fare_settlement_method  base_fare  surcharge_misc  transit_tax  driver_tip_payment  toll_total  service_improvement_fee  charge_total  zone_congestion_fee  Airport_fee  congestion_relief_fee  trip_duration_minutes  speed_mph                                   source_file  source_row_1based
             2 2025-07-12 21:03:49 2025-07-12 21:07:57          1.0            0.64            1.0                   N             41           42                       4      -6.50            -1.0         -0.5                 0.0         0.0                     -1.0         -9.00                  0.0         0.00                   0.00               4.133333   9.290323 Urban_Flow_Analytics_Taxi_Dataset_2025-07.csv            1016504
             2 2025-10-30 22:45:21 2025-10-30 23:05:06          NaN            1.33            NaN                 NaN            100          233                       0      -5.06             0.0          0.5                 0.0         0.0                      1.0          4.59                  NaN          NaN                   0.75              19.750000   4.040506 Urban_Flow_Analytics_Taxi_Dataset_2025-10.csv            4373878
             2 2025-10-02 02:23:41 2025-10-02 02:27:29          NaN            0.52            NaN                 NaN            189           61                       0      -1.50             0.0          0.5                 0.0         0.0                      1.0          1.00                  NaN          NaN                   0.00               3.800000   8.210526 Urban_Flow_Analytics_Taxi_Dataset_2025-10.csv            3464704
             2 2025-10-15 08:41:35 2025-10-15 08:41:43          2.0            0.00            5.0                   N            138          138                       4     -55.50            -5.0          0.0                 0.0         0.0                     -1.0        -63.25                  0.0        -1.75                   0.00               0.133333   0.000000 Urban_Flow_Analytics_Taxi_Dataset_2025-10.csv            1519650
             2 2025-09-08 18:11:36 2025-09-08 18:30:58          1.0            2.57            1.0                   N            140          239                       2     -18.40            -2.5         -0.5                 0.0         0.0                     -1.0        -24.90                 -2.5         0.00                   0.00              19.366667   7.962134 Urban_Flow_Analytics_Taxi_Dataset_2025-09.csv             758194
             2 2025-07-16 09:14:41 2025-07-16 09:42:55          NaN            1.86            NaN                 NaN            142          162                       0      -4.75             0.0          0.5                 0.0         0.0                      1.0          5.05                  NaN          NaN                   0.75              28.233333   3.952774 Urban_Flow_Analytics_Taxi_Dataset_2025-07.csv            3333641
             2 2025-11-08 19:39:41 2025-11-08 20:11:49          NaN            6.77            NaN                 NaN            161           66                       0      -0.07             0.0          0.5                 0.0         0.0                      1.0          4.68                  NaN          NaN                   0.75              32.133333  12.641079 Urban_Flow_Analytics_Taxi_Dataset_2025-11.csv            3452449
             2 2025-06-26 09:45:42 2025-06-26 09:58:01          NaN            1.85            NaN                 NaN            263          140                       0      -4.00             0.0          0.5                 0.0         0.0                      1.0          2.07                  NaN          NaN                   0.00              12.316667   9.012179 Urban_Flow_Analytics_Taxi_Dataset_2025-06.csv            4146551
             2 2025-07-16 18:20:25 2025-07-16 18:29:46          1.0            2.03            1.0                   N            231           65                       4     -12.10            -2.5         -0.5                 0.0         0.0                     -1.0        -19.35                 -2.5         0.00                  -0.75               9.350000  13.026738 Urban_Flow_Analytics_Taxi_Dataset_2025-07.csv            1391781
             2 2025-05-20 16:53:49 2025-05-20 17:03:35          NaN            0.00            NaN                 NaN            100          170                       0      -0.60             0.0          0.5                 0.0         0.0                      1.0          4.15                  NaN          NaN                   0.75               9.766667   0.000000 Urban_Flow_Analytics_Taxi_Dataset_2025-05.csv            4172718

Inspection group: zero_distance_charged
 provider_code    pickup_timestamp   dropoff_timestamp  rider_count  distance_miles  rate_class_id offline_record_flag  origin_loc_id  dest_loc_id  fare_settlement_method  base_fare  surcharge_misc  transit_tax  driver_tip_payment  toll_total  service_improvement_fee  charge_total  zone_congestion_fee  Airport_fee  congestion_relief_fee  trip_duration_minutes  speed_mph                                   source_file  source_row_1based
             2 2026-02-11 19:39:12 2026-02-11 19:55:46          NaN             0.0            NaN                 NaN            166          127                       0      24.46             0.0          0.5                0.00         0.0                      1.0         25.96                  NaN          NaN                   0.00              16.566667        0.0 Urban_Flow_Analytics_Taxi_Dataset_2026-02.csv            2814846
             2 2026-02-05 18:04:44 2026-02-05 18:36:51          NaN             0.0            NaN                 NaN            262           90                       0      38.43             0.0          0.5                4.32         0.0                      1.0         47.50                  NaN          NaN                   0.75              32.116667        0.0 Urban_Flow_Analytics_Taxi_Dataset_2026-02.csv            2549304
             2 2025-09-17 11:41:18 2025-09-17 11:44:13          1.0             0.0            1.0                   N             98           98                       2       4.40             0.0          0.5                0.00         0.0                      1.0          5.90                  0.0          0.0                   0.00               2.916667        0.0 Urban_Flow_Analytics_Taxi_Dataset_2025-09.csv            1697083
             2 2025-09-26 17:56:30 2025-09-26 18:14:11          NaN             0.0            NaN                 NaN            141          224                       0      -4.00             0.0          0.5                0.00         0.0                      1.0          2.53                  NaN          NaN                   0.00              17.683333        0.0 Urban_Flow_Analytics_Taxi_Dataset_2025-09.csv            4088174
             2 2025-06-19 18:22:43 2025-06-19 18:35:48          NaN             0.0            NaN                 NaN            238          237                       0      18.48             0.0          0.5                0.00         0.0                      1.0         22.48                  NaN          NaN                   0.00              13.083333        0.0 Urban_Flow_Analytics_Taxi_Dataset_2025-06.csv            3851674
             1 2025-04-22 11:19:11 2025-04-22 11:20:35          0.0             0.0            1.0                   N            145          145                       2       3.70             0.0          0.5                0.00         0.0                      1.0          5.20                  0.0          0.0                   0.00               1.400000        0.0 Urban_Flow_Analytics_Taxi_Dataset_2025-04.csv            2242724
             2 2025-05-22 18:48:43 2025-05-22 19:08:27          NaN             0.0            NaN                 NaN            230          164                       0     -11.20             0.0          0.5                0.00         0.0                      1.0          3.55                  NaN          NaN                   0.75              19.733333        0.0 Urban_Flow_Analytics_Taxi_Dataset_2025-05.csv            4265074
             2 2026-02-13 17:39:03 2026-02-13 17:50:29          NaN             0.0            NaN                 NaN             48          170                       0      20.08             0.0          0.5                0.00         0.0                      1.0         28.55                  NaN          NaN                   0.75              11.433333        0.0 Urban_Flow_Analytics_Taxi_Dataset_2026-02.csv            2889134
             2 2025-05-05 14:42:25 2025-05-05 14:42:35          1.0             0.0            1.0                   N            231          231                       1       3.00             0.0          0.5                2.33         0.0                      1.0         10.08                  2.5          0.0                   0.75               0.166667        0.0 Urban_Flow_Analytics_Taxi_Dataset_2025-05.csv             502159
             2 2025-06-12 19:30:07 2025-06-12 19:49:25          NaN             0.0            NaN                 NaN            107          263                       0      30.38             0.0          0.5                7.03         0.0                      1.0         42.16                  NaN          NaN                   0.75              19.300000        0.0 Urban_Flow_Analytics_Taxi_Dataset_2025-06.csv            3581032

Inspection group: zero_riders
 provider_code    pickup_timestamp   dropoff_timestamp  rider_count  distance_miles  rate_class_id offline_record_flag  origin_loc_id  dest_loc_id  fare_settlement_method  base_fare  surcharge_misc  transit_tax  driver_tip_payment  toll_total  service_improvement_fee  charge_total  zone_congestion_fee  Airport_fee  congestion_relief_fee  trip_duration_minutes  speed_mph                                   source_file  source_row_1based
             1 2025-12-19 17:02:54 2025-12-19 17:13:51          0.0            1.50            1.0                   N            229          262                       2       11.4            5.75          0.5                0.00         0.0                      1.0         18.65                  2.5          0.0                   0.75              10.950000   8.219178 Urban_Flow_Analytics_Taxi_Dataset_2025-12.csv            2155612
             1 2025-12-24 13:19:58 2025-12-24 13:34:53          0.0            0.80            1.0                   Y            230          161                       1       13.5            3.25          0.5                8.00         0.0                      1.0         26.25                  2.5          0.0                   0.75              14.916667   3.217877 Urban_Flow_Analytics_Taxi_Dataset_2025-12.csv            2591269
             1 2025-04-18 13:33:05 2025-04-18 13:33:27          0.0            0.10            1.0                   N            238          238                       2        3.0            2.50          0.5                0.00         0.0                      1.0          7.00                  2.5          0.0                   0.00               0.366667  16.363636 Urban_Flow_Analytics_Taxi_Dataset_2025-04.csv            1869091
             1 2026-02-12 20:58:38 2026-02-12 21:02:12          0.0            0.50            1.0                   N            113          114                       1        5.8            4.25          0.5                2.30         0.0                      1.0         13.85                  2.5          0.0                   0.75               3.566667   8.411215 Urban_Flow_Analytics_Taxi_Dataset_2026-02.csv            1050333
             2 2025-09-20 18:50:36 2025-09-20 19:01:01          0.0            1.25            1.0                   N             79          137                       1       10.7            0.00          0.5                2.00         0.0                      1.0         17.45                  2.5          0.0                   0.75              10.416667   7.200000 Urban_Flow_Analytics_Taxi_Dataset_2025-09.csv            2103871
             2 2025-11-16 00:43:14 2025-11-16 00:54:49          0.0            2.28            1.0                   N             68          163                       1       13.5            1.00          0.5                2.89         0.0                      1.0         22.14                  2.5          0.0                   0.75              11.583333  11.810072 Urban_Flow_Analytics_Taxi_Dataset_2025-11.csv            1686576
             1 2025-05-17 10:44:00 2025-05-17 11:00:51          0.0            6.60            1.0                   N            162           52                       1       27.5            3.25          0.5                6.45         0.0                      1.0         38.70                  2.5          0.0                   0.75              16.850000  23.501484 Urban_Flow_Analytics_Taxi_Dataset_2025-05.csv            1864131
             2 2026-03-12 17:00:34 2026-03-12 17:02:06          0.0            0.49            1.0                   N             68           68                       1        4.4            2.50          0.5                0.00         0.0                      1.0         11.65                  2.5          0.0                   0.75               1.533333  19.173913 Urban_Flow_Analytics_Taxi_Dataset_2026-03.csv            1129599
             1 2025-05-30 15:30:12 2025-05-30 15:49:13          0.0            2.20            1.0                   N            237           48                       1       18.4            3.25          0.5                4.63         0.0                      1.0         27.78                  2.5          0.0                   0.75              19.016667   6.941280 Urban_Flow_Analytics_Taxi_Dataset_2025-05.csv            3226835
             1 2025-08-19 10:04:10 2025-08-19 10:16:46          0.0            1.50            1.0                   N             50          186                       2       12.8            3.25          0.5                0.00         0.0                      1.0         17.55                  2.5          0.0                   0.75              12.600000   7.142857 Urban_Flow_Analytics_Taxi_Dataset_2025-08.csv            1575832

Inspection group: negative_duration
 provider_code    pickup_timestamp   dropoff_timestamp  rider_count  distance_miles  rate_class_id offline_record_flag  origin_loc_id  dest_loc_id  fare_settlement_method  base_fare  surcharge_misc  transit_tax  driver_tip_payment  toll_total  service_improvement_fee  charge_total  zone_congestion_fee  Airport_fee  congestion_relief_fee  trip_duration_minutes  speed_mph                                   source_file  source_row_1based
             2 2025-11-02 01:37:46 2025-11-02 01:04:10          2.0            6.58            1.0                   N            114           74                       2      31.70            1.00          0.5                0.00        0.00                      1.0         37.45                  2.5          0.0                   0.75             -33.600000        NaN Urban_Flow_Analytics_Taxi_Dataset_2025-11.csv             125455
             2 2025-11-02 01:41:56 2025-11-02 01:16:58          NaN           10.22            NaN                 NaN            114          116                       0      49.74            0.00          0.5                0.00        0.00                      1.0         54.49                  NaN          NaN                   0.75             -24.966667        NaN Urban_Flow_Analytics_Taxi_Dataset_2025-11.csv            3239337
             1 2025-11-02 01:48:14 2025-11-02 01:06:18          NaN            2.50            NaN                 NaN            249          233                       0      25.67            0.00          0.5                0.00        0.00                      1.0         30.42                  NaN          NaN                   0.75             -41.933333        NaN Urban_Flow_Analytics_Taxi_Dataset_2025-11.csv            3237783
             2 2025-11-02 01:34:57 2025-11-02 01:04:03          NaN            5.31            NaN                 NaN            100           25                       0      -4.30            0.00          0.5                0.00        0.00                      1.0          0.45                  NaN          NaN                   0.75             -30.900000        NaN Urban_Flow_Analytics_Taxi_Dataset_2025-11.csv            3239317
             2 2025-11-02 01:53:08 2025-11-02 01:50:10          1.0           28.29            1.0                   N            170          265                       1     109.40            1.00          0.5               25.81       13.88                      1.0        154.84                  2.5          0.0                   0.75              -2.966667        NaN Urban_Flow_Analytics_Taxi_Dataset_2025-11.csv             123763
             1 2025-11-02 01:43:03 2025-11-02 01:02:35          1.0            5.00            1.0                   N            186           42                       1      23.30            4.25          0.5                2.00        0.00                      1.0         31.05                  2.5          0.0                   0.75             -40.466667        NaN Urban_Flow_Analytics_Taxi_Dataset_2025-11.csv             129030
             1 2025-11-02 01:42:20 2025-11-02 01:10:11          NaN            5.40            NaN                 NaN             45           75                       0      33.82            0.00          0.5                0.00        0.00                      1.0         38.57                  NaN          NaN                   0.75             -32.150000        NaN Urban_Flow_Analytics_Taxi_Dataset_2025-11.csv            3237597
             6 2025-06-11 17:06:24 2025-06-11 17:06:05          NaN            4.09            NaN                 NaN             18          254                       0       2.90            0.00          0.5                0.00        0.00                      0.3         23.88                  NaN          NaN                   0.00              -0.316667        NaN Urban_Flow_Analytics_Taxi_Dataset_2025-06.csv            3535689
             2 2025-11-02 01:53:09 2025-11-02 01:09:28          1.0            5.86            1.0                   N             79           74                       1      26.10            1.00          0.5                4.00        0.00                      1.0         35.85                  2.5          0.0                   0.75             -43.683333        NaN Urban_Flow_Analytics_Taxi_Dataset_2025-11.csv             128874
             1 2025-11-02 01:58:25 2025-11-02 01:00:59          NaN            0.30            NaN                 NaN            186          100                       0      19.11            0.00          0.5                0.00        0.00                      1.0         23.86                  NaN          NaN                   0.75             -57.433333        NaN Urban_Flow_Analytics_Taxi_Dataset_2025-11.csv            3239044

Inspection group: zero_duration
 provider_code    pickup_timestamp   dropoff_timestamp  rider_count  distance_miles  rate_class_id offline_record_flag  origin_loc_id  dest_loc_id  fare_settlement_method  base_fare  surcharge_misc  transit_tax  driver_tip_payment  toll_total  service_improvement_fee  charge_total  zone_congestion_fee  Airport_fee  congestion_relief_fee  trip_duration_minutes  speed_mph                                   source_file  source_row_1based

### Overlap and proposed-rule union

Compute pairwise anomaly overlaps from exact bit-pattern counts. The proposed shared **model-eligibility** union includes all six listed rules; task-specific fare or duration views may choose narrower exclusions after team confirmation. Historical quarantine means exclusion from the analysis view while preserving raw records. Nonhistorical pickups outside the observation interval are scope exclusions, not automatically bad trips. Zero riders and zero-distance charged rows are retained unless another rule excludes them. No numeric values are proposed for imputation.

A **100 mph trip-average speed ceiling** is the conservative proposed model filter, with 80-100 mph retained for review. This is not a legal limit or a claim that every excluded trip is fraudulent. [NY DMV guidance](https://dmv.ny.gov/brochure/mv21.pdf) describes expressway limits normally 55 mph, with some posted at 65 mph. A 100 mph average is about 54% above 65 and more than twice the observed p99.9 of 46.85 mph, providing a substantial allowance for short-record timing/distance error and out-of-area trips. Threshold sensitivity at 80/100/120 and their examples are evaluated before selecting it. This is an explicit, conservative modelling tolerance rather than an estimated physical boundary; team approval remains appropriate.

In [28]:
s_overlap=np.zeros((8,8),dtype="int64")
for bits,count in enumerate(s_combinations):
    for i in range(8):
        for j in range(8):
            if bits&(1<<i) and bits&(1<<j):s_overlap[i,j]+=count
print("Pairwise anomaly overlap; diagonal is each anomaly count:")
print(pd.DataFrame(s_overlap,index=s_anomaly_names,columns=s_anomaly_names).to_string())
s_unique_anomalies=int(s_combinations[1:].sum());s_model_union=int(s_rule_combinations[1:].sum())
s_rule_table=pd.DataFrame([{"rule":name,"count":s_rules[name],"percent":100*s_rules[name]/s_rows} for name in s_rule_names])
print("Proposed rules (overlapping):");print(s_rule_table.to_string(index=False))
print("Unique rows meeting any measured anomaly:",s_unique_anomalies,100*s_unique_anomalies/s_rows)
print("Unique rows excluded from proposed shared model view:",s_model_union,100*s_model_union/s_rows)
print("Retained shared model rows:",s_rows-s_model_union)
print("Raw rows removed: 0. Proposed numeric-value alterations: 0. No rules applied.")
print(pd.DataFrame(s_monthly).to_string(index=False))
assert s_snapshot=={str(p):(p.stat().st_size,p.stat().st_mtime_ns) for p in s_files}
print("PASS: source sizes and modification times unchanged; Step 6 investigation only.")
# Compact evidence for the decision report; aggregate values only.
s_evidence={"rows":s_rows,"groups":dict(s_sizes),"relationships":{g:dict(x) for g,x in s_rel.items()},"rules":dict(s_rules),"boundary":dict(s_boundary_counts),"model_union":s_model_union,"anomaly_union":s_unique_anomalies}
print("EVIDENCE_JSON="+json.dumps(s_evidence))

Pairwise anomaly overlap; diagonal is each anomaly count:
                       negative_fare  negative_distance  zero_distance_charged  zero_riders  nonpositive_duration  speed_over_100  historical  out_of_month
negative_fare                2400031                  0                 204636          345                   193             478           0          1023
negative_distance                  0                  0                      0            0                     0               0           0             0
zero_distance_charged         204636                  0                1471746         8555                 16619               0           0            74
zero_riders                      345                  0                   8555       231578                  2125             500           0            56
nonpositive_duration             193                  0                  16619         2125                651610               0           0             1
speed_over_100                   478                  0                      0          500                     0           11899           1             3
historical                         0                  0                      0            0                     0               1           8             8
out_of_month                    1023                  0                     74           56                     1               3           8         19646
Proposed rules (overlapping):
                             rule   count  percent
            historical_quarantine       8 0.000016
outside_observation_nonhistorical       6 0.000012
     negative_fare_or_total_model 2405603 4.949619
          negative_distance_model       0 0.000000
       nonpositive_duration_model  651610 1.340712
             speed_over_100_model   11899 0.024483
Unique rows meeting any measured anomaly: 4554053 9.370135852220399
Unique rows excluded from proposed shared model view: 3068448 6.313447519269973
Retained shared model rows: 45533334
Raw rows removed: 0. Proposed numeric-value alterations: 0. No rules applied.
source_month  historical_quarantine  outside_observation_nonhistorical  negative_fare_or_total_model  negative_distance_model  nonpositive_duration_model  speed_over_100_model  model_union    rows
     2025-04                      0                                  4                        187018                        0                       34769                  1002       222743 3970553
     2025-05                      1                                  0                        325804                        0                       64272                  1175       391164 4591845
     2025-06                      0                                  0                        276056                        0                       68583                  1396       345956 4322960
     2025-07                      1                                  0                        247375                        0                       56064                   947       304338 3898963
     2025-08                      1                                  0                        261437                        0                       47833                   941       310153 3574091
     2025-09                      0                                  0                        253100                        0                       57179                  1059       311274 4251015
     2025-10                      0                                  0                        321716                        0                       67968                  1122       390732 4428699
     2025-11                      3                                  0                        395587                        0                       62120                  1001       458542 4181444
     2025-12                      0                                  0                         48887                        0                       58021                   974       107859 4305006
     2026-01                      0                                  0                         40002                        0                       45070                   732        85792 3724889
     2026-02                      0                                  0                         27304                        0                       40598                   620        68516 3399866
     2026-03                      2                                  2                         21317                        0                       49133                   930        71379 3952451
PASS: source sizes and modification times unchanged; Step 6 investigation only.
EVIDENCE_JSON={"rows": 48601782, "groups": {"negative_fare": 2400031, "nonnegative_fare": 46201751, "zero_distance_charged": 1471746, "positive_distance": 47123012, "zero_riders": 231578, "positive_riders": 35964936, "negative_duration": 1942, "zero_duration": 649668, "speed_80_to_100": 1690, "speed_100_to_120": 1227, "speed_over_120": 10672}, "relationships": {"negative_fare": {"same_origin_destination": 150805, "positive_duration": 2399838, "negative_final_charge": 869827, "zero_final_charge": 0, "positive_final_charge": 1530204, "positive_distance": 2195395, "duration_at_most_one_minute": 77195, "any_negative_other_monetary_component": 706187}, "nonnegative_fare": {"same_origin_destination": 2091002, "positive_duration": 45550334, "negative_final_charge": 5572, "zero_final_charge": 6699, "positive_final_charge": 46189480, "positive_distance": 44927617, "duration_at_most_one_minute": 467181, "any_negative_other_monetary_component": 7644}, "zero_distance_charged": {"same_origin_destination": 405252, "positive_duration": 1455127, "negative_final_charge": 64854, "zero_final_charge": 33, "positive_final_charge": 1406859, "positive_distance": 0, "duration_at_most_one_minute": 361317, "any_negative_other_monetary_component": 48656}, "positive_distance": {"same_origin_destination": 1830812, "positive_duration": 46488457, "negative_final_charge": 808895, "zero_final_charge": 3902, "positive_final_charge": 46310215, "positive_distance": 47123012, "duration_at_most_one_minute": 178406, "any_negative_other_monetary_component": 663525}, "zero_riders": {"same_origin_destination": 18172, "positive_duration": 229453, "negative_final_charge": 347, "zero_final_charge": 180, "positive_final_charge": 231051, "positive_distance": 222846, "duration_at_most_one_minute": 5956, "any_negative_other_monetary_component": 347}, "positive_riders": {"same_origin_destination": 1951072, "positive_duration": 35317160, "negative_final_charge": 711247, "zero_final_charge": 5575, "positive_final_charge": 35248114, "positive_distance": 35494946, "duration_at_most_one_minute": 501790, "any_negative_other_monetary_component": 711234}, "negative_duration": {"same_origin_destination": 39, "positive_duration": 0, "negative_final_charge": 50, "zero_final_charge": 31, "positive_final_charge": 1861, "positive_distance": 1930, "duration_at_most_one_minute": 0, "any_negative_other_monetary_component": 12}, "zero_duration": {"same_origin_destination": 33130, "positive_duration": 0, "negative_final_charge": 26, "zero_final_charge": 337, "positive_final_charge": 649305, "positive_distance": 632625, "duration_at_most_one_minute": 0, "any_negative_other_monetary_component": 21}, "speed_80_to_100": {"same_origin_destination": 449, "positive_duration": 1690, "negative_final_charge": 30, "zero_final_charge": 10, "positive_final_charge": 1650, "positive_distance": 1690, "duration_at_most_one_minute": 488, "any_negative_other_monetary_component": 30}, "speed_100_to_120": {"same_origin_destination": 369, "positive_duration": 1227, "negative_final_charge": 15, "zero_final_charge": 7, "positive_final_charge": 1205, "positive_distance": 1227, "duration_at_most_one_minute": 394, "any_negative_other_monetary_component": 14}, "speed_over_120": {"same_origin_destination": 5119, "positive_duration": 10672, "negative_final_charge": 213, "zero_final_charge": 103, "positive_final_charge": 10356, "positive_distance": 10672, "duration_at_most_one_minute": 6512, "any_negative_other_monetary_component": 187}}, "rules": {"negative_duration_repeated_hour_candidate": 1431, "historical_quarantine": 8, "outside_observation_nonhistorical": 6, "negative_fare_or_total_model": 2405603, "negative_distance_model": 0, "nonpositive_duration_model": 651610, "speed_over_100_model": 11899, "zero_riders_in_retained_model_rows": 228606, "zero_distance_charged_in_retained_model_rows": 1250568}, "boundary": {"historical": 8, "short_near_boundary": 19251, "other_adjacent_boundary": 374, "remaining_month_mismatch": 13}, "model_union": 3068448, "anomaly_union": 4554053}

# Data cleaning decisions: Step 6

**Status: proposed policy, not applied.** Investigation covers all **48,601,782 rows** in 12 monthly files. Raw data and Steps 1-5 remain unchanged. No cleaned dataset, splits, models, imputation, or corrections were produced. Notebook: `notebooks/01_data_audit_and_cleaning.ipynb`.

## Decisions

| Anomaly | Count | Percent | Proposed Treatment | Justification |
|---|---:|---:|---|---|
| Negative base_fare | 2,400,031 | 4.93815433% | KEEP raw; FILTER FOR FARE MODELLING | Mixed signed-charge behavior, not verified refunds; exclude negative targets from a nonnegative gross-fare model. |
| Negative final charge (additional evidence) | 875,399 | 1.80116647% | KEEP raw; FILTER FOR FARE MODELLING | Includes 5,572 rows with nonnegative base fare. Combined base-or-final-negative rule affects 2,405,603 rows. |
| Negative distance | 0 | 0.00000000% | FILTER FOR DISTANCE/TIME MODELLING if present | No observed rows; negative physical distance would require review. |
| Zero distance with nonzero base fare | 1,471,746 | 3.02817292% | KEEP; FLAG FOR REVIEW | Waiting/short trips or incomplete distance readings are plausible; no blanket removal. |
| rider_count == 0 | 231,578 | 0.47648047% | KEEP; NO IMPUTATION | Likely provider-specific recording behavior; unknown/default is plausible but unproven. |
| Negative duration | 1,942 | 0.00399574% | KEEP raw; FILTER FOR TIME/SPEED MODELLING pending review | 1,431 repeated-hour candidates; do not automatically add an hour or delete trips. |
| Zero duration | 649,668 | 1.33671642% | KEEP raw; FILTER FOR TIME/SPEED MODELLING | 632,625 have positive distance. Elapsed time is not usable as recorded. |
| Speed >100 mph | 11,899 | 0.02448264% | FILTER FOR TIME/SPEED MODEL VIEW; retain raw | Proposed conservative ceiling. Retain 80-100 mph for review; no winsorization. |
| Historical pickup/dropoff 2008/2009 | 8 | 0.00001646% | QUARANTINE FROM ANALYSIS; retain raw | All eight full records conflict with the stated observation period; do not invent replacement years. |
| Other pickup outside observation interval | 6 | 0.00001235% | KEEP master; EXCLUDE FROM PERIOD-SCOPED VIEW ONLY | Four March 31, 2025 pickups and two April 1, 2026 pickups. Scope exclusions, not invalid trips. |
| Either timestamp outside source month | 19,646 | 0.04042239% | KEEP; partition and review | 19,251 short boundary examples; 374 other adjacent cases; 13 remaining mismatches; 8 historical. No blanket file-month rule. |

These are view-specific policies, not universal deletion rules. Keep an intact raw/master archive. Financial adjustments may remain useful for accounting, while unusable duration measurements should not enter duration/speed targets. Do not automatically exclude a valid trip from demand analysis solely because its fare is negative or a timestamp needs interpretation.

## Investigation supporting the decisions

### Negative base fares and final charges

All **2,400,031 negative-base-fare rows are provider code 2**. Payment code 0 accounts for **1,694,004 (70.58%)**; code 4 for **455,956 (19.00%)**; code 2 for **162,267 (6.76%)**; code 3 for **86,005 (3.58%)**; and code 1 for **1,799 (0.07%)**. Rate class and offline flag are missing in 1,694,004 of these rows. Detailed counts, within-group percentages, code-conditioned percentages, and payment/provider combinations are in the notebook.

Only **869,827 (36.24%)** have a negative final charge; **1,530,204 (63.76%)** have a positive final charge. Another monetary component is negative in **706,187 (29.42%)**. Most have positive duration: **2,399,838**; **2,195,395** have positive distance. Mean base fare is **-10.2942**, mean final charge **-6.5527**, and mean duration **18.1944 minutes**. Sample median duration is about **16 minutes**, versus **13.73** for nonnegative fares.

This is a mixture of signed financial records and apparently active trips, not evidence that all negatives are refunds or voids. No transaction identifiers or matched reversal evidence establish such a classification. The [TLC dictionary](https://www.nyc.gov/assets/tlc/downloads/pdf/data_dictionary_trip_records_yellow.pdf) describes flex-fare, dispute, no-charge, and other payment types in TLC data; **the competition mapping is unconfirmed**, so these names are hypotheses for the observed codes. Do not take absolute values, replace negative fares with zero, or infer code meanings as facts.

**Policy:** retain raw and accounting records; exclude `base_fare < 0 OR charge_total < 0` from a nonnegative gross-fare training view. This catches **2,405,603** rows, including **5,572** additional negative-final-charge rows. If the team instead models net signed charges, this exclusion is inappropriate and must be changed. Avoid applying it automatically to demand-only or duration-only tasks.

### Zero distance with nonzero fare

**1,455,127 (98.87%)** have positive duration; **405,252 (27.54%)** have equal origin/destination IDs. Equal IDs establish the same zone, not the same physical point. Mean duration is **15.0950 minutes**, sample median **12.9667**, and sample p95 **38.2842**. Mean base fare is **22.6166**, sample median **17.605**, and sample p95 **77.00**. Payment code 0 represents **67.93%**, provider 2 **89.78%**, and rate code 5 **10.95%**; rate code is missing for **67.93%**.

[TLC fare rules](https://www.nyc.gov/site/tlc/passengers/taxi-fare.page) permit time-based charging while waiting or moving slowly. This supports retaining possible waiting/short trips but does not explain every different-zone zero-distance record. **KEEP and flag; no distance imputation or blanket removal.** Distance-sensitive models need an explicit later decision about these measurements. Under the combined eligibility scenario below, **1,250,568** remain after other exclusions.

### Zero riders compared with positive riders

Provider 1 accounts for **215,567 (93.09%)** of zero-rider rows, versus **20.89%** of positive-rider rows. Payment code 1 accounts for **82.76%** versus **84.21%**. **222,846 (96.23%)** zero-rider rows have positive distance and **229,453 (99.08%)** positive duration.

| Measure | Zero riders | Positive riders |
|---|---:|---:|
| Mean base fare | 17.1411 | 19.3343 |
| Mean distance, miles | 2.5540 | 3.5770 |
| Mean duration, minutes | 14.5022 | 17.5126 |
| Approximate sample median duration, minutes | 11.30 | 12.775 |

Neither group has missing original source fields. This means zero-rider records do **not** simply reproduce the known broadly missing-field pattern. Provider concentration and otherwise trip-like values support a recording/default hypothesis, but do not prove that zero means unknown. **KEEP and flag; do not replace with 1, a median, or missing without confirmed semantics.** Exclude the rider-count field from passenger-count interpretation until clarified, rather than discarding otherwise useful trips. **228,606** such rows remain under the combined eligibility scenario.

### Negative and zero durations

There are **1,942 negative** and **649,668 zero** durations. Of the negative durations, **1,431 (73.69%)** fall on November 2, 2025 with both timestamps in the repeated 01:00 hour and a difference between -60 and 0 minutes. [NIST](https://www.nist.gov/pml/time-and-frequency-division/popular-links/daylight-saving-time-dst) documents the clock rollback on the first Sunday in November. This is compatible with a clock ambiguity **if** these are applicable local times, but the source is timezone-naive and does not prove that interpretation.

**632,625 zero-duration records have positive distance**, making their elapsed travel time unusable as recorded. **KEEP raw; exclude all 651,610 non-positive durations from duration/speed model eligibility until resolved.** Do not add an hour, invent a duration, or calculate speed for them. They need not be removed from unrelated accounting/demand views.

### Proposed speed ceiling: 100 mph

Use **strictly greater than 100 mph** as the proposed time/speed modelling exclusion. Values equal to 100 remain eligible. No capping or rewriting. Keep 80-100 mph for review.

The exact p99.9 is **46.8506 mph**; p99 is **34.2581 mph**, while the maximum is **4,816,614.8 mph**. [NY DMV guidance](https://dmv.ny.gov/brochure/mv21.pdf) describes expressways normally at 55 mph and some at 65 mph. A **100 mph trip average is about 54% above 65 mph and 2.13 times the observed p99.9**, leaving a large tolerance for short-trip timing/distance error and out-of-area travel. It is an operational modelling tolerance, not a legal limit for every route or a learned physical boundary.

Threshold sensitivity: >80 affects **13,589**, >100 **11,899**, and >120 **10,672** rows. Choosing 100 retains **1,690** rows in (80,100] while excluding **1,227** in (100,120] plus the extreme tail. Within (80,100], **488/1,690** last at most a minute; above 120, **6,512/10,672** do. Short-record instability and physically extreme samples support a generous ceiling rather than a percentile-only cutoff. The value is a judgement with explicit tolerance, **not justified merely by roundness**; team confirmation is still needed for target-specific use and out-of-area exceptions.

### Historical timestamps and month boundaries

All eight historical rows are printed with every original field. All are provider 2, have positive fares, and contain dates in 2008/2009. Seven have durations from roughly 0.17 to 68 minutes; one spans about 921.53 minutes. They may be real operational records with bad dates, but their years clearly conflict with the observation period. **Quarantine all eight from analysis views; retain raw and do not guess replacement dates.**

Of **19,646** rows with either timestamp outside its source month:

- **19,251** are nonhistorical short near-boundary cases (both timestamps within two hours of a source-month boundary, positive duration at most two hours). These are plausible boundary activity, not certified valid in every other field.
- **374** are other adjacent-boundary cases. Samples include roughly 18-24-hour durations for short distances; review separately without a blanket filename rule.
- **13** are remaining nonhistorical mismatches. Examples span several days for small distances, such as 0.49 miles over about 4,062 minutes; these look implausible as ordinary metered trips and need targeted adjudication.
- **8** are historical.

**Retain legitimate boundary crossings.** The two-hour grouping is an inspection convention, not a cleaning cutoff. Flag the 374 and 13 groups for review; no new maximum-duration rule is inferred from a file-month mismatch. Their final duration-specific treatment remains unresolved and is **not an additional exclusion in the count below**.

Define a proposed period-scoped view by pickup in **[2025-04-01, 2026-04-01)**, retaining dropoffs after midnight or after the period end when pickup is in scope. This scopes out the eight historical pickups and **six additional legitimate boundary pickups** (four March 31, two April 1). Keep those six in the master; excluding them from this interval is not cleaning them as bad records. Confirm the intended pickup-based period with the team.

## Exact overlap and affected-row accounting

| Proposed exclusion rule | Rows | Percent of all rows |
|---|---:|---:|
| Historical analysis quarantine | 8 | 0.00001646% |
| Other out-of-period pickups (scope only) | 6 | 0.00001235% |
| Negative base fare OR negative final charge | 2,405,603 | 4.94961893% |
| Negative distance | 0 | 0.00000000% |
| Non-positive duration | 651,610 | 1.34071216% |
| Speed >100 mph | 11,899 | 0.02448264% |


These rules overlap. The notebook contains the full pairwise anomaly matrix and monthly proposed union counts. Examples: **204,636** negative-fare rows also have zero distance/nonzero fare; **16,619** zero-distance charged rows have non-positive duration; **500** zero-rider rows exceed 100 mph; one historical row exceeds 100 mph. There are **4,554,053 (9.37013585%)** distinct rows meeting any measured anomaly (using >100 mph for the speed category), but many are intentionally retained.

For a conservative shared fare/time model view using the **OR of all six proposed exclusion rules**:

- **Unique rows excluded or affected by at least one proposed exclusion: 3,068,448 (6.31344752%).**
- **Remaining rows: 45,533,334.**
- Sum of individual rule counts is **3,069,126**; that is **678** larger than the distinct union and must not be used as the removed-row count.
- **Raw/master rows proposed for deletion: 0. Numeric values proposed for alteration/imputation: 0. Actual changes applied: 0.**

The 3,068,448 union is an explicit scenario, not a universal mandate for every task. Target-specific views should use the relevant subset; no exclusions should silently carry into demand counts or net-accounting analysis. The unresolved long-duration boundary review could change a future policy and would require recomputing its union. This report does not claim the remaining rows are fully clean.

## Team confirmations before implementation

1. Confirm competition code meanings and whether signed fares represent net accounting, adjustments, or a nonnegative gross-fare target.
2. Confirm task-specific model eligibility versus a single shared model view, including the 100 mph ceiling and route coverage.
3. Confirm timezone/clock conventions before any repeated-hour correction; the 1,431 candidates are not proven repairs.
4. Confirm zero-rider semantics; retain without imputation until documented.
5. Confirm pickup-based observation scope and adjudicate the 374 adjacent/13 other timestamp cases before treating the duration view as final.

No approval is being requested to perform further work here: this step stops at documented recommendations. Applying any rule is a later task.

## Method and verification

Counts, code percentages, missingness, means, extrema, overlaps, and union sizes are exact over all input rows. Subgroup medians/p95 are approximate from fixed-seed random-priority samples (up to 5,000 per group); full-dataset speed percentiles are the exact Step 5 results. Source file sizes and modification times remained unchanged. All Step 6 code completed without errors and Steps 1-5 were compared unchanged. No cleaned Parquet, splits, or models were created.

## Step 7: Build the cleaned analytical dataset

The user's Step 7 instruction authorizes applying the **shared fare/time modelling scenario** already documented in `reports/data_cleaning_decisions.md`. That report and Steps 1-6 remain unchanged as historical records. This output is a period-scoped shared model view, not a complete demand or net-accounting population.

Apply exactly the six documented exclusions: historical timestamps; other pickups outside `[2025-04-01, 2026-04-01)`; negative base fare or final charge; negative distance; non-positive duration; and speed strictly above 100 mph. Keep eligible zero distances, zero riders, and month-boundary trips. No capping, correction, imputation, or new duration cutoff is introduced. The unresolved boundary categories remain flagged.

Read/write in 200,000-row chunks. Keep every original column and value in retained rows, original timestamp text, all eight derived fields, source-row provenance, six readable zone fields, and relevant audit flags. Hash every raw file before and after. Validate each join as many-to-one and verify retained original values are unchanged. Write a temporary Parquet file, reopen and scan it, and publish the final filename only after validation.

In [7]:
from pathlib import Path
from collections import Counter
import hashlib,json,re,shutil
import numpy as np
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq

b_root=next(p for p in [Path.cwd(),*Path.cwd().parents] if (p/"data"/"raw").is_dir())
b_policy_path=b_root/"reports"/"data_cleaning_decisions.md"
b_policy_bytes=b_policy_path.read_bytes();b_policy=b_policy_bytes.decode("utf-8")
b_policy_sha=hashlib.sha256(b_policy_bytes).hexdigest()
b_expected_rules={"historical_quarantine":8,"outside_observation_nonhistorical":6,"negative_fare_or_total_model":2_405_603,"negative_distance_model":0,"nonpositive_duration_model":651_610,"speed_over_100_model":11_899}
# Fail on a changed policy instead of silently substituting undocumented rules.
for text in ["3,068,448","45,533,334","2,405,603","651,610","11,899","strictly greater than 100 mph","[2025-04-01, 2026-04-01)"]:
    assert text in b_policy, f"Review changed cleaning policy: missing {text}"
b_expected_input=48_601_782;b_expected_retained=45_533_334;b_expected_excluded=3_068_448
b_raw=b_root/"data"/"raw"
b_all_raw=sorted(p for p in b_raw.rglob("*") if p.is_file())
b_files=sorted(p for p in b_all_raw if p.name.startswith("Urban_Flow_Analytics_Taxi_Dataset_") and p.suffix.lower()==".csv" and "__MACOSX" not in p.parts and not any(part.startswith("._") for part in p.parts))
b_zones=[p for p in b_all_raw if p.suffix.lower()==".csv" and "zone" in p.stem.lower() and "__MACOSX" not in p.parts and not any(part.startswith("._") for part in p.parts)]
assert len(b_files)==12 and len(b_zones)==1
b_output=b_root/"data"/"processed"/"clean_trips.parquet"
b_partial=b_output.with_name("clean_trips.parquet.partial")
if b_output.exists():
    print("Processed dataset already exists; skipping rebuild and continuing with verification.")
else:
    assert not b_partial.exists(), "Partial build exists; review before replacing"
b_output.parent.mkdir(parents=True,exist_ok=True)
print("Policy SHA-256:",b_policy_sha)
print("Free disk GB:",shutil.disk_usage(b_output.parent).free/1e9)
def b_sha(path):
    digest=hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda:stream.read(8*1024*1024),b""):digest.update(block)
    return digest.hexdigest()
print("Hashing raw files before processing",flush=True)
b_before={str(p.relative_to(b_root)): {"bytes":p.stat().st_size,"sha256":b_sha(p)} for p in b_all_raw}
print(json.dumps(b_before,indent=2))
b_zone=pd.read_csv(b_zones[0])
assert b_zone.loc_id.notna().all() and b_zone.loc_id.is_unique
b_zone_labels=["borough_name","zone_name","service_zone"]
assert all(col in b_zone for col in b_zone_labels)
b_pickup_lookup=b_zone.rename(columns={"loc_id":"origin_loc_id",**{col:"pickup_"+col for col in b_zone_labels}})
b_dropoff_lookup=b_zone.rename(columns={"loc_id":"dest_loc_id",**{col:"dropoff_"+col for col in b_zone_labels}})
b_original=pd.read_csv(b_files[0],nrows=0).columns.tolist()
for p in b_files:assert pd.read_csv(p,nrows=0).columns.tolist()==b_original
# Preserve source numeric widths; compact only derived calendar and Boolean columns.
b_ints=["provider_code","origin_loc_id","dest_loc_id","fare_settlement_method"]
b_strings=["pickup_timestamp","dropoff_timestamp","offline_record_flag"]
b_read_dtypes={col:"int64" if col in b_ints else "string" if col in b_strings else "float64" for col in b_original}

Processed dataset already exists; skipping rebuild and continuing with verification.
Policy SHA-256: 9e9938db705620460a8fd5f5c12fceef489c37fb535f77f255134296f079b43c
Free disk GB: 1.398714368
Hashing raw files before processing
{
  "data\\raw\\.gitkeep": {
    "bytes": 0,
    "sha256": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
  },
  "data\\raw\\Urban_Flow_Analytics_Taxi_Dataset_2025-04.csv": {
    "bytes": 429662745,
    "sha256": "dba50280078b3316ab6bf8fefb539e4b9d8c9f580c5f514ec4e9599165d503fd"
  },
  "data\\raw\\Urban_Flow_Analytics_Taxi_Dataset_2025-05.csv": {
    "bytes": 492535780,
    "sha256": "acc84c0f3aa8cc7cff779e8c359bad20ec88ffc9d9be08fdb8e42902fe65a2df"
  },
  "data\\raw\\Urban_Flow_Analytics_Taxi_Dataset_2025-06.csv": {
    "bytes": 462646895,
    "sha256": "a567e88093ad1feffd75d2b8f2422054fe76927ed57ea16e4a72f4fe6824ac74"
  },
  "data\\raw\\Urban_Flow_Analytics_Taxi_Dataset_2025-07.csv": {
    "bytes": 418006505,
    "sha256": "4c57cbc07f4cc3c4b1153aed950c2e9badd0786a9a5958343c8c3577cdbc0356"
  },
  "data\\raw\\Urban_Flow_Analytics_Taxi_Dataset_2025-08.csv": {
    "bytes": 383928038,
    "sha256": "a3dd30328ae2777aac529caf48853f1f984cb5326964fafd1982303f596acee0"
  },
  "data\\raw\\Urban_Flow_Analytics_Taxi_Dataset_2025-09.csv": {
    "bytes": 456686968,
    "sha256": "e65ee3a0dcc001b8ea190199c0997ef56e5d8a7c7fe3254d9c38851315b0d4c8"
  },
  "data\\raw\\Urban_Flow_Analytics_Taxi_Dataset_2025-10.csv": {
    "bytes": 477118702,
    "sha256": "c03fd6d84e623cd6afe8397c6e7c527542d7002b71ad31d31cae40becaf37de1"
  },
  "data\\raw\\Urban_Flow_Analytics_Taxi_Dataset_2025-11.csv": {
    "bytes": 449095149,
    "sha256": "c61f1ec057def05e001bf36cd2c71f6d0cb912135c4bd041e26a98af97d87de8"
  },
  "data\\raw\\Urban_Flow_Analytics_Taxi_Dataset_2025-12.csv": {
    "bytes": 460962917,
    "sha256": "66bfa2d5a1261643188d8dc74f13c0a97520c1805b2b798eb2e11d05ebb00943"
  },
  "data\\raw\\Urban_Flow_Analytics_Taxi_Dataset_2026-01.csv": {
    "bytes": 397895400,
    "sha256": "208bef3741f6df5f4716594b6a60d35dab0ba275074f6d0ddd4d10e7feb3bdb8"
  },
  "data\\raw\\Urban_Flow_Analytics_Taxi_Dataset_2026-02.csv": {
    "bytes": 362760959,
    "sha256": "b2245d4495d5948e0cfa7930090c72fd581b0623ce817b4060309c1c9500f775"
  },
  "data\\raw\\Urban_Flow_Analytics_Taxi_Dataset_2026-03.csv": {
    "bytes": 424665352,
    "sha256": "d3037ade4df1bb1046130f11f4e35f200ab718e8b669331d81aa18aeaa2efc58"
  },
  "data\\raw\\Urban_Flow_Analytics_Zone_Dataset (1).csv": {
    "bytes": 10739,
    "sha256": "f9e77526930e6d7e0bc4464e3e3c4e98af3effc74b2d178012ac2ff1ab28497b"
  }
}

In [4]:
from pathlib import Path
import pyarrow.parquet as pq

output_file = Path("../data/processed/clean_trips.parquet")

print("Exists:", output_file.exists())

if output_file.exists():
    parquet_file = pq.ParquetFile(output_file)

    print("Rows:", parquet_file.metadata.num_rows)
    print("Columns:", parquet_file.metadata.num_columns)
    print("Row groups:", parquet_file.metadata.num_row_groups)
    print("Size MB:", output_file.stat().st_size / (1024 ** 2))

Exists: True
Rows: 45533334
Columns: 45
Row groups: 247
Size MB: 1218.7746315002441

In [6]:
from pathlib import Path
import pyarrow.parquet as pq

root = next(path for path in [Path.cwd(), *Path.cwd().parents] if (path / "data" / "processed").is_dir())
output_file = root / "data" / "processed" / "clean_trips.parquet"
parquet_file = pq.ParquetFile(output_file)

print("Total rows:", parquet_file.metadata.num_rows)
print("Total columns:", parquet_file.metadata.num_columns)
print("Row groups:", parquet_file.metadata.num_row_groups)
print("File size (MB):", output_file.stat().st_size / 1_000_000)

assert parquet_file.metadata.num_row_groups > 0, "Parquet file has no row groups"
first_row_group = parquet_file.read_row_group(0)
sample = first_row_group.to_pandas().head(1000)

print("Sample shape:", sample.shape)
print("All sample columns:")
print(sample.columns.tolist())

required_fields = [
    "trip_duration_minutes", "speed_mph", "pickup_date",
    "pickup_hour", "day_of_week", "month", "weekend", "route_id",
]
print("Required fields present:")
print({field: field in sample.columns for field in required_fields})

print("Zone/borough columns:")
print([column for column in sample.columns if "zone" in column.lower() or "borough" in column.lower()])

flag_columns = [column for column in sample.columns if column.startswith("flag_")]
print("Flag columns:")
print(flag_columns)
print("Flag counts within sample:")
for column in flag_columns:
    print(f"{column}:")
    print(sample[column].value_counts(dropna=False).to_dict())

print("STOP: Step 7 verification only; no data was modified and Step 8 was not run.")

Total rows: 45533334
Total columns: 45
Row groups: 247
File size (MB): 1277.977828
Sample shape: (1000, 45)
All sample columns:
['provider_code', 'pickup_timestamp', 'dropoff_timestamp', 'rider_count', 'distance_miles', 'rate_class_id', 'offline_record_flag', 'origin_loc_id', 'dest_loc_id', 'fare_settlement_method', 'base_fare', 'surcharge_misc', 'transit_tax', 'driver_tip_payment', 'toll_total', 'service_improvement_fee', 'charge_total', 'zone_congestion_fee', 'Airport_fee', 'congestion_relief_fee', 'source_file', 'source_month', 'source_row_1based', 'trip_duration_minutes', 'speed_mph', 'pickup_date', 'pickup_hour', 'day_of_week', 'month', 'weekend', 'route_id', 'audit_zero_distance_nonzero_fare', 'audit_zero_riders', 'audit_speed_80_to_100', 'audit_pickup_outside_source_month', 'audit_dropoff_outside_source_month', 'audit_boundary_category', 'pickup_borough_name', 'pickup_zone_name', 'pickup_service_zone', 'dropoff_borough_name', 'dropoff_zone_name', 'dropoff_service_zone', 'audit_pickup_incomplete_zone_labels', 'audit_dropoff_incomplete_zone_labels']
Required fields present:
{'trip_duration_minutes': True, 'speed_mph': True, 'pickup_date': True, 'pickup_hour': True, 'day_of_week': True, 'month': True, 'weekend': True, 'route_id': True}
Zone/borough columns:
['zone_congestion_fee', 'pickup_borough_name', 'pickup_zone_name', 'pickup_service_zone', 'dropoff_borough_name', 'dropoff_zone_name', 'dropoff_service_zone', 'audit_pickup_incomplete_zone_labels', 'audit_dropoff_incomplete_zone_labels']
Flag columns:
[]
Flag counts within sample:
STOP: Step 7 verification only; no data was modified and Step 8 was not run.

## Step 9: Chronological train, validation, and test splits

The processed dataset was split incrementally by `pickup_timestamp` using PyArrow row groups. The full dataset was not loaded into pandas, rows were not shuffled, and `data/processed/clean_trips.parquet` and `data/feature_contract.md` were not modified.

### Pickup coverage and exact boundaries

- Overall pickup coverage: `2025-04-01 00:00:00` through `2026-03-31 23:59:59`.
- Train: timestamps `< 2025-12-11 00:00:00`.
- Validation: timestamps `>= 2025-12-11 00:00:00` and `< 2026-02-05 00:00:00`.
- Test: timestamps `>= 2026-02-05 00:00:00`.
- Boundaries are whole-day cut points selected from cumulative pickup-date counts near 70% and 85%; therefore the proportions are approximate rather than exact row percentages.

| Split | Rows | Percent | Start Timestamp | End Timestamp | File Size |
|---|---:|---:|---|---|---:|
| Train | 31,988,176 | 70.252216% | 2025-04-01 00:00:00 | 2025-12-10 23:59:59 | 894.731 MB |
| Validation | 6,814,901 | 14.966839% | 2025-12-11 00:00:00 | 2026-02-04 23:59:58 | 190.425 MB |
| Test | 6,730,257 | 14.780945% | 2026-02-05 00:00:01 | 2026-03-31 23:59:59 | 186.475 MB |

### Verification

- Output files: `data/splits/train.parquet`, `data/splits/validation.parquet`, and `data/splits/test.parquet`.
- Total row reconciliation: `31,988,176 + 6,814,901 + 6,730,257 = 45,533,334`; **PASS**.
- No rows were lost: **PASS**, based on one exclusive timestamp mask per source row and total-count reconciliation.
- Duplicate rows between splits: **none detected**; the exclusive, non-overlapping timestamp masks assign each source row to at most one split.
- Timestamp range overlap: **none**; train ends before validation starts, and validation ends before test starts.
- Latest-period test check: **PASS**; test contains the latest observed pickup timestamp, `2026-03-31 23:59:59`.
- Warning: files use compact Zstandard Parquet compression because the source and split files are large. The split contents retain all source columns and row values; physical row order from incremental source processing is preserved, with no random shuffle.

**STOP: Step 9 complete. No modelling or later-step processing was performed.**